/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestMessageContentPartImageImageUrl } from './ChatCompletionRequestMessageContentPartImageImageUrl';
import {
    ChatCompletionRequestMessageContentPartImageImageUrlFromJSON,
    ChatCompletionRequestMessageContentPartImageImageUrlFromJSONTyped,
    ChatCompletionRequestMessageContentPartImageImageUrlToJSON,
    ChatCompletionRequestMessageContentPartImageImageUrlToJSONTyped,
} from './ChatCompletionRequestMessageContentPartImageImageUrl';

/**
 * 画像コンテンツ。
 * @export
 * @interface ChatCompletionRequestMessageContentPartImage
 */
export interface ChatCompletionRequestMessageContentPartImage {
    /**
     * 
     * @type {ChatCompletionRequestMessageContentPartImageTypeEnum}
     * @memberof ChatCompletionRequestMessageContentPartImage
     */
    type: ChatCompletionRequestMessageContentPartImageTypeEnum;
    /**
     * 
     * @type {ChatCompletionRequestMessageContentPartImageImageUrl}
     * @memberof ChatCompletionRequestMessageContentPartImage
     */
    imageUrl: ChatCompletionRequestMessageContentPartImageImageUrl;
}


/**
 * @export
 */
export const ChatCompletionRequestMessageContentPartImageTypeEnum = {
    ImageUrl: 'image_url'
} as const;
export type ChatCompletionRequestMessageContentPartImageTypeEnum = typeof ChatCompletionRequestMessageContentPartImageTypeEnum[keyof typeof ChatCompletionRequestMessageContentPartImageTypeEnum];


/**
 * Check if a given object implements the ChatCompletionRequestMessageContentPartImage interface.
 */
export function instanceOfChatCompletionRequestMessageContentPartImage(value: object): value is ChatCompletionRequestMessageContentPartImage {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'image_url') return false;
    
    if ((!('imageUrl' in (value as Record<string, any>)) && !('image_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['imageUrl'] === undefined && (value as Record<string, any>)['image_url'] === undefined)) return false;
    return true;
}

export function ChatCompletionRequestMessageContentPartImageFromJSON(json: any): ChatCompletionRequestMessageContentPartImage {
    return ChatCompletionRequestMessageContentPartImageFromJSONTyped(json, false);
}

export function ChatCompletionRequestMessageContentPartImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestMessageContentPartImage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'imageUrl': ChatCompletionRequestMessageContentPartImageImageUrlFromJSON(json['image_url']),
    };
}

export function ChatCompletionRequestMessageContentPartImageToJSON(json: any): ChatCompletionRequestMessageContentPartImage {
    return ChatCompletionRequestMessageContentPartImageToJSONTyped(json, false);
}

export function ChatCompletionRequestMessageContentPartImageToJSONTyped(value?: ChatCompletionRequestMessageContentPartImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'image_url': ChatCompletionRequestMessageContentPartImageImageUrlToJSON(value['imageUrl']),
    };
}

