/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestToolMessageContent } from './ChatCompletionRequestToolMessageContent';
import {
    ChatCompletionRequestToolMessageContentFromJSON,
    ChatCompletionRequestToolMessageContentFromJSONTyped,
    ChatCompletionRequestToolMessageContentToJSON,
    ChatCompletionRequestToolMessageContentToJSONTyped,
} from './ChatCompletionRequestToolMessageContent';

/**
 * ツールの応答メッセージ。
 * @export
 * @interface ChatCompletionRequestToolMessage
 */
export interface ChatCompletionRequestToolMessage {
    /**
     * メッセージの発言者の役割。
     * @type {ChatCompletionRequestToolMessageRoleEnum}
     * @memberof ChatCompletionRequestToolMessage
     */
    role: ChatCompletionRequestToolMessageRoleEnum;
    /**
     * 
     * @type {ChatCompletionRequestToolMessageContent}
     * @memberof ChatCompletionRequestToolMessage
     */
    content: ChatCompletionRequestToolMessageContent;
    /**
     * ツール呼び出しの一意な識別子。
     * @type {string}
     * @memberof ChatCompletionRequestToolMessage
     */
    toolCallId: string;
}


/**
 * @export
 */
export const ChatCompletionRequestToolMessageRoleEnum = {
    Tool: 'tool'
} as const;
export type ChatCompletionRequestToolMessageRoleEnum = typeof ChatCompletionRequestToolMessageRoleEnum[keyof typeof ChatCompletionRequestToolMessageRoleEnum];


/**
 * Check if a given object implements the ChatCompletionRequestToolMessage interface.
 */
export function instanceOfChatCompletionRequestToolMessage(value: object): value is ChatCompletionRequestToolMessage {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (value['role'] !== 'tool') return false;
    
    if (!('content' in value) || value['content'] === undefined) return false;
    if ((!('toolCallId' in (value as Record<string, any>)) && !('tool_call_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolCallId'] === undefined && (value as Record<string, any>)['tool_call_id'] === undefined)) return false;
    return true;
}

export function ChatCompletionRequestToolMessageFromJSON(json: any): ChatCompletionRequestToolMessage {
    return ChatCompletionRequestToolMessageFromJSONTyped(json, false);
}

export function ChatCompletionRequestToolMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestToolMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': ChatCompletionRequestToolMessageContentFromJSON(json['content']),
        'toolCallId': json['tool_call_id'],
    };
}

export function ChatCompletionRequestToolMessageToJSON(json: any): ChatCompletionRequestToolMessage {
    return ChatCompletionRequestToolMessageToJSONTyped(json, false);
}

export function ChatCompletionRequestToolMessageToJSONTyped(value?: ChatCompletionRequestToolMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': ChatCompletionRequestToolMessageContentToJSON(value['content']),
        'tool_call_id': value['toolCallId'],
    };
}

