/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestMessageContentPartText } from './ChatCompletionRequestMessageContentPartText';
import {
    ChatCompletionRequestMessageContentPartTextFromJSON,
    ChatCompletionRequestMessageContentPartTextFromJSONTyped,
    ChatCompletionRequestMessageContentPartTextToJSON,
    ChatCompletionRequestMessageContentPartTextToJSONTyped,
} from './ChatCompletionRequestMessageContentPartText';

/**
 * 
 * @export
 * @interface ChatCompletionRequestDeveloperMessageContent
 */
export interface ChatCompletionRequestDeveloperMessageContent {
}

/**
 * Check if a given object implements the ChatCompletionRequestDeveloperMessageContent interface.
 */
export function instanceOfChatCompletionRequestDeveloperMessageContent(value: object): value is ChatCompletionRequestDeveloperMessageContent {
    return true;
}

export function ChatCompletionRequestDeveloperMessageContentFromJSON(json: any): ChatCompletionRequestDeveloperMessageContent {
    return ChatCompletionRequestDeveloperMessageContentFromJSONTyped(json, false);
}

export function ChatCompletionRequestDeveloperMessageContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestDeveloperMessageContent {
    return json;
}

export function ChatCompletionRequestDeveloperMessageContentToJSON(json: any): ChatCompletionRequestDeveloperMessageContent {
    return ChatCompletionRequestDeveloperMessageContentToJSONTyped(json, false);
}

export function ChatCompletionRequestDeveloperMessageContentToJSONTyped(value?: ChatCompletionRequestDeveloperMessageContent | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

