/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionNamedToolChoice } from './ChatCompletionNamedToolChoice';
import {
    ChatCompletionNamedToolChoiceFromJSON,
    ChatCompletionNamedToolChoiceFromJSONTyped,
    ChatCompletionNamedToolChoiceToJSON,
    ChatCompletionNamedToolChoiceToJSONTyped,
} from './ChatCompletionNamedToolChoice';
import type { ChatCompletionNamedToolChoiceFunction } from './ChatCompletionNamedToolChoiceFunction';
import {
    ChatCompletionNamedToolChoiceFunctionFromJSON,
    ChatCompletionNamedToolChoiceFunctionFromJSONTyped,
    ChatCompletionNamedToolChoiceFunctionToJSON,
    ChatCompletionNamedToolChoiceFunctionToJSONTyped,
} from './ChatCompletionNamedToolChoiceFunction';

/**
 * 
 * @export
 * @interface ChatCompletionToolChoiceOption
 */
export interface ChatCompletionToolChoiceOption {
    /**
     * 
     * @type {ChatCompletionToolChoiceOptionTypeEnum}
     * @memberof ChatCompletionToolChoiceOption
     */
    type: ChatCompletionToolChoiceOptionTypeEnum;
    /**
     * 
     * @type {ChatCompletionNamedToolChoiceFunction}
     * @memberof ChatCompletionToolChoiceOption
     */
    _function: ChatCompletionNamedToolChoiceFunction;
}


/**
 * @export
 */
export const ChatCompletionToolChoiceOptionTypeEnum = {
    Function: 'function'
} as const;
export type ChatCompletionToolChoiceOptionTypeEnum = typeof ChatCompletionToolChoiceOptionTypeEnum[keyof typeof ChatCompletionToolChoiceOptionTypeEnum];


/**
 * Check if a given object implements the ChatCompletionToolChoiceOption interface.
 */
export function instanceOfChatCompletionToolChoiceOption(value: object): value is ChatCompletionToolChoiceOption {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'function') return false;
    
    if ((!('_function' in (value as Record<string, any>)) && !('function' in (value as Record<string, any>))) || ((value as Record<string, any>)['_function'] === undefined && (value as Record<string, any>)['function'] === undefined)) return false;
    return true;
}

export function ChatCompletionToolChoiceOptionFromJSON(json: any): ChatCompletionToolChoiceOption {
    return ChatCompletionToolChoiceOptionFromJSONTyped(json, false);
}

export function ChatCompletionToolChoiceOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionToolChoiceOption {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        '_function': ChatCompletionNamedToolChoiceFunctionFromJSON(json['function']),
    };
}

export function ChatCompletionToolChoiceOptionToJSON(json: any): ChatCompletionToolChoiceOption {
    return ChatCompletionToolChoiceOptionToJSONTyped(json, false);
}

export function ChatCompletionToolChoiceOptionToJSONTyped(value?: ChatCompletionToolChoiceOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'function': ChatCompletionNamedToolChoiceFunctionToJSON(value['_function']),
    };
}

