/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestUserMessageContent } from './ChatCompletionRequestUserMessageContent';
import {
    ChatCompletionRequestUserMessageContentFromJSON,
    ChatCompletionRequestUserMessageContentFromJSONTyped,
    ChatCompletionRequestUserMessageContentToJSON,
    ChatCompletionRequestUserMessageContentToJSONTyped,
} from './ChatCompletionRequestUserMessageContent';

/**
 * ユーザーからのメッセージ。
 * @export
 * @interface ChatCompletionRequestUserMessage
 */
export interface ChatCompletionRequestUserMessage {
    /**
     * 
     * @type {ChatCompletionRequestUserMessageContent}
     * @memberof ChatCompletionRequestUserMessage
     */
    content: ChatCompletionRequestUserMessageContent;
    /**
     * メッセージの発言者の役割。
     * @type {ChatCompletionRequestUserMessageRoleEnum}
     * @memberof ChatCompletionRequestUserMessage
     */
    role: ChatCompletionRequestUserMessageRoleEnum;
}


/**
 * @export
 */
export const ChatCompletionRequestUserMessageRoleEnum = {
    User: 'user'
} as const;
export type ChatCompletionRequestUserMessageRoleEnum = typeof ChatCompletionRequestUserMessageRoleEnum[keyof typeof ChatCompletionRequestUserMessageRoleEnum];


/**
 * Check if a given object implements the ChatCompletionRequestUserMessage interface.
 */
export function instanceOfChatCompletionRequestUserMessage(value: object): value is ChatCompletionRequestUserMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (value['role'] !== 'user') return false;
    
    return true;
}

export function ChatCompletionRequestUserMessageFromJSON(json: any): ChatCompletionRequestUserMessage {
    return ChatCompletionRequestUserMessageFromJSONTyped(json, false);
}

export function ChatCompletionRequestUserMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestUserMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': ChatCompletionRequestUserMessageContentFromJSON(json['content']),
        'role': json['role'],
    };
}

export function ChatCompletionRequestUserMessageToJSON(json: any): ChatCompletionRequestUserMessage {
    return ChatCompletionRequestUserMessageToJSONTyped(json, false);
}

export function ChatCompletionRequestUserMessageToJSONTyped(value?: ChatCompletionRequestUserMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': ChatCompletionRequestUserMessageContentToJSON(value['content']),
        'role': value['role'],
    };
}

