/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestSystemMessageContent } from './ChatCompletionRequestSystemMessageContent';
import {
    ChatCompletionRequestSystemMessageContentFromJSON,
    ChatCompletionRequestSystemMessageContentFromJSONTyped,
    ChatCompletionRequestSystemMessageContentToJSON,
    ChatCompletionRequestSystemMessageContentToJSONTyped,
} from './ChatCompletionRequestSystemMessageContent';

/**
 * モデルに対する開発者からの指示メッセージ。
 * @export
 * @interface ChatCompletionRequestSystemMessage
 */
export interface ChatCompletionRequestSystemMessage {
    /**
     * 
     * @type {ChatCompletionRequestSystemMessageContent}
     * @memberof ChatCompletionRequestSystemMessage
     */
    content: ChatCompletionRequestSystemMessageContent;
    /**
     * メッセージの発言者の役割。
     * @type {ChatCompletionRequestSystemMessageRoleEnum}
     * @memberof ChatCompletionRequestSystemMessage
     */
    role: ChatCompletionRequestSystemMessageRoleEnum;
}


/**
 * @export
 */
export const ChatCompletionRequestSystemMessageRoleEnum = {
    System: 'system'
} as const;
export type ChatCompletionRequestSystemMessageRoleEnum = typeof ChatCompletionRequestSystemMessageRoleEnum[keyof typeof ChatCompletionRequestSystemMessageRoleEnum];


/**
 * Check if a given object implements the ChatCompletionRequestSystemMessage interface.
 */
export function instanceOfChatCompletionRequestSystemMessage(value: object): value is ChatCompletionRequestSystemMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (value['role'] !== 'system') return false;
    
    return true;
}

export function ChatCompletionRequestSystemMessageFromJSON(json: any): ChatCompletionRequestSystemMessage {
    return ChatCompletionRequestSystemMessageFromJSONTyped(json, false);
}

export function ChatCompletionRequestSystemMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestSystemMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': ChatCompletionRequestSystemMessageContentFromJSON(json['content']),
        'role': json['role'],
    };
}

export function ChatCompletionRequestSystemMessageToJSON(json: any): ChatCompletionRequestSystemMessage {
    return ChatCompletionRequestSystemMessageToJSONTyped(json, false);
}

export function ChatCompletionRequestSystemMessageToJSONTyped(value?: ChatCompletionRequestSystemMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': ChatCompletionRequestSystemMessageContentToJSON(value['content']),
        'role': value['role'],
    };
}

