/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestUserMessageContentPart } from './ChatCompletionRequestUserMessageContentPart';
import {
    ChatCompletionRequestUserMessageContentPartFromJSON,
    ChatCompletionRequestUserMessageContentPartFromJSONTyped,
    ChatCompletionRequestUserMessageContentPartToJSON,
    ChatCompletionRequestUserMessageContentPartToJSONTyped,
} from './ChatCompletionRequestUserMessageContentPart';

/**
 * 
 * @export
 * @interface ChatCompletionRequestUserMessageContent
 */
export interface ChatCompletionRequestUserMessageContent {
}

/**
 * Check if a given object implements the ChatCompletionRequestUserMessageContent interface.
 */
export function instanceOfChatCompletionRequestUserMessageContent(value: object): value is ChatCompletionRequestUserMessageContent {
    return true;
}

export function ChatCompletionRequestUserMessageContentFromJSON(json: any): ChatCompletionRequestUserMessageContent {
    return ChatCompletionRequestUserMessageContentFromJSONTyped(json, false);
}

export function ChatCompletionRequestUserMessageContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestUserMessageContent {
    return json;
}

export function ChatCompletionRequestUserMessageContentToJSON(json: any): ChatCompletionRequestUserMessageContent {
    return ChatCompletionRequestUserMessageContentToJSONTyped(json, false);
}

export function ChatCompletionRequestUserMessageContentToJSONTyped(value?: ChatCompletionRequestUserMessageContent | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

