/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestMessageContentPartText } from './ChatCompletionRequestMessageContentPartText';
import {
    ChatCompletionRequestMessageContentPartTextFromJSON,
    ChatCompletionRequestMessageContentPartTextFromJSONTyped,
    ChatCompletionRequestMessageContentPartTextToJSON,
    ChatCompletionRequestMessageContentPartTextToJSONTyped,
} from './ChatCompletionRequestMessageContentPartText';

/**
 * ツールの応答メッセージの内容。
 * @export
 * @interface ChatCompletionRequestToolMessageContent
 */
export interface ChatCompletionRequestToolMessageContent {
}

/**
 * Check if a given object implements the ChatCompletionRequestToolMessageContent interface.
 */
export function instanceOfChatCompletionRequestToolMessageContent(value: object): value is ChatCompletionRequestToolMessageContent {
    return true;
}

export function ChatCompletionRequestToolMessageContentFromJSON(json: any): ChatCompletionRequestToolMessageContent {
    return ChatCompletionRequestToolMessageContentFromJSONTyped(json, false);
}

export function ChatCompletionRequestToolMessageContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestToolMessageContent {
    return json;
}

export function ChatCompletionRequestToolMessageContentToJSON(json: any): ChatCompletionRequestToolMessageContent {
    return ChatCompletionRequestToolMessageContentToJSONTyped(json, false);
}

export function ChatCompletionRequestToolMessageContentToJSONTyped(value?: ChatCompletionRequestToolMessageContent | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

