/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestAssistantMessageContent } from './ChatCompletionRequestAssistantMessageContent';
import {
    ChatCompletionRequestAssistantMessageContentFromJSON,
    ChatCompletionRequestAssistantMessageContentFromJSONTyped,
    ChatCompletionRequestAssistantMessageContentToJSON,
    ChatCompletionRequestAssistantMessageContentToJSONTyped,
} from './ChatCompletionRequestAssistantMessageContent';

/**
 * モデルからの応答メッセージ。
 * @export
 * @interface ChatCompletionRequestAssistantMessage
 */
export interface ChatCompletionRequestAssistantMessage {
    /**
     * 
     * @type {ChatCompletionRequestAssistantMessageContent}
     * @memberof ChatCompletionRequestAssistantMessage
     */
    content?: ChatCompletionRequestAssistantMessageContent;
    /**
     * メッセージの発言者の役割。
     * @type {ChatCompletionRequestAssistantMessageRoleEnum}
     * @memberof ChatCompletionRequestAssistantMessage
     */
    role: ChatCompletionRequestAssistantMessageRoleEnum;
}


/**
 * @export
 */
export const ChatCompletionRequestAssistantMessageRoleEnum = {
    Assistant: 'assistant'
} as const;
export type ChatCompletionRequestAssistantMessageRoleEnum = typeof ChatCompletionRequestAssistantMessageRoleEnum[keyof typeof ChatCompletionRequestAssistantMessageRoleEnum];


/**
 * Check if a given object implements the ChatCompletionRequestAssistantMessage interface.
 */
export function instanceOfChatCompletionRequestAssistantMessage(value: object): value is ChatCompletionRequestAssistantMessage {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (value['role'] !== 'assistant') return false;
    
    return true;
}

export function ChatCompletionRequestAssistantMessageFromJSON(json: any): ChatCompletionRequestAssistantMessage {
    return ChatCompletionRequestAssistantMessageFromJSONTyped(json, false);
}

export function ChatCompletionRequestAssistantMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestAssistantMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ChatCompletionRequestAssistantMessageContentFromJSON(json['content']),
        'role': json['role'],
    };
}

export function ChatCompletionRequestAssistantMessageToJSON(json: any): ChatCompletionRequestAssistantMessage {
    return ChatCompletionRequestAssistantMessageToJSONTyped(json, false);
}

export function ChatCompletionRequestAssistantMessageToJSONTyped(value?: ChatCompletionRequestAssistantMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': ChatCompletionRequestAssistantMessageContentToJSON(value['content']),
        'role': value['role'],
    };
}

