/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionRequestUserMessage } from './ChatCompletionRequestUserMessage';
import {
    ChatCompletionRequestUserMessageFromJSON,
    ChatCompletionRequestUserMessageFromJSONTyped,
    ChatCompletionRequestUserMessageToJSON,
    ChatCompletionRequestUserMessageToJSONTyped,
} from './ChatCompletionRequestUserMessage';
import type { ChatCompletionRequestToolMessageContent } from './ChatCompletionRequestToolMessageContent';
import {
    ChatCompletionRequestToolMessageContentFromJSON,
    ChatCompletionRequestToolMessageContentFromJSONTyped,
    ChatCompletionRequestToolMessageContentToJSON,
    ChatCompletionRequestToolMessageContentToJSONTyped,
} from './ChatCompletionRequestToolMessageContent';
import type { ChatCompletionRequestAssistantMessage } from './ChatCompletionRequestAssistantMessage';
import {
    ChatCompletionRequestAssistantMessageFromJSON,
    ChatCompletionRequestAssistantMessageFromJSONTyped,
    ChatCompletionRequestAssistantMessageToJSON,
    ChatCompletionRequestAssistantMessageToJSONTyped,
} from './ChatCompletionRequestAssistantMessage';
import type { ChatCompletionRequestDeveloperMessage } from './ChatCompletionRequestDeveloperMessage';
import {
    ChatCompletionRequestDeveloperMessageFromJSON,
    ChatCompletionRequestDeveloperMessageFromJSONTyped,
    ChatCompletionRequestDeveloperMessageToJSON,
    ChatCompletionRequestDeveloperMessageToJSONTyped,
} from './ChatCompletionRequestDeveloperMessage';
import type { ChatCompletionRequestToolMessage } from './ChatCompletionRequestToolMessage';
import {
    ChatCompletionRequestToolMessageFromJSON,
    ChatCompletionRequestToolMessageFromJSONTyped,
    ChatCompletionRequestToolMessageToJSON,
    ChatCompletionRequestToolMessageToJSONTyped,
} from './ChatCompletionRequestToolMessage';
import type { ChatCompletionRequestSystemMessage } from './ChatCompletionRequestSystemMessage';
import {
    ChatCompletionRequestSystemMessageFromJSON,
    ChatCompletionRequestSystemMessageFromJSONTyped,
    ChatCompletionRequestSystemMessageToJSON,
    ChatCompletionRequestSystemMessageToJSONTyped,
} from './ChatCompletionRequestSystemMessage';

/**
 * 
 * @export
 * @interface CreateChatCompletionRequestMessagesInner
 */
export interface CreateChatCompletionRequestMessagesInner {
    /**
     * 
     * @type {ChatCompletionRequestToolMessageContent}
     * @memberof CreateChatCompletionRequestMessagesInner
     */
    content: ChatCompletionRequestToolMessageContent;
    /**
     * メッセージの発言者の役割。
     * @type {CreateChatCompletionRequestMessagesInnerRoleEnum}
     * @memberof CreateChatCompletionRequestMessagesInner
     */
    role: CreateChatCompletionRequestMessagesInnerRoleEnum;
    /**
     * ツール呼び出しの一意な識別子。
     * @type {string}
     * @memberof CreateChatCompletionRequestMessagesInner
     */
    toolCallId: string;
}


/**
 * @export
 */
export const CreateChatCompletionRequestMessagesInnerRoleEnum = {
    Tool: 'tool'
} as const;
export type CreateChatCompletionRequestMessagesInnerRoleEnum = typeof CreateChatCompletionRequestMessagesInnerRoleEnum[keyof typeof CreateChatCompletionRequestMessagesInnerRoleEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestMessagesInner interface.
 */
export function instanceOfCreateChatCompletionRequestMessagesInner(value: object): value is CreateChatCompletionRequestMessagesInner {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (value['role'] !== 'tool') return false;
    
    if ((!('toolCallId' in (value as Record<string, any>)) && !('tool_call_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolCallId'] === undefined && (value as Record<string, any>)['tool_call_id'] === undefined)) return false;
    return true;
}

export function CreateChatCompletionRequestMessagesInnerFromJSON(json: any): CreateChatCompletionRequestMessagesInner {
    return CreateChatCompletionRequestMessagesInnerFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestMessagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestMessagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'content': ChatCompletionRequestToolMessageContentFromJSON(json['content']),
        'role': json['role'],
        'toolCallId': json['tool_call_id'],
    };
}

export function CreateChatCompletionRequestMessagesInnerToJSON(json: any): CreateChatCompletionRequestMessagesInner {
    return CreateChatCompletionRequestMessagesInnerToJSONTyped(json, false);
}

export function CreateChatCompletionRequestMessagesInnerToJSONTyped(value?: CreateChatCompletionRequestMessagesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': ChatCompletionRequestToolMessageContentToJSON(value['content']),
        'role': value['role'],
        'tool_call_id': value['toolCallId'],
    };
}

