/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateEmbeddingsRequestInput } from './CreateEmbeddingsRequestInput';
import {
    CreateEmbeddingsRequestInputFromJSON,
    CreateEmbeddingsRequestInputFromJSONTyped,
    CreateEmbeddingsRequestInputToJSON,
    CreateEmbeddingsRequestInputToJSONTyped,
} from './CreateEmbeddingsRequestInput';

/**
 * 
 * @export
 * @interface CreateEmbeddingsRequest
 */
export interface CreateEmbeddingsRequest {
    /**
     * 利用する埋め込みモデル名。利用可能なモデルはコントロールパネル等をご確認ください。
     * @type {string}
     * @memberof CreateEmbeddingsRequest
     */
    model: string;
    /**
     * 
     * @type {CreateEmbeddingsRequestInput}
     * @memberof CreateEmbeddingsRequest
     */
    input: CreateEmbeddingsRequestInput;
}

/**
 * Check if a given object implements the CreateEmbeddingsRequest interface.
 */
export function instanceOfCreateEmbeddingsRequest(value: object): value is CreateEmbeddingsRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function CreateEmbeddingsRequestFromJSON(json: any): CreateEmbeddingsRequest {
    return CreateEmbeddingsRequestFromJSONTyped(json, false);
}

export function CreateEmbeddingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmbeddingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'input': CreateEmbeddingsRequestInputFromJSON(json['input']),
    };
}

export function CreateEmbeddingsRequestToJSON(json: any): CreateEmbeddingsRequest {
    return CreateEmbeddingsRequestToJSONTyped(json, false);
}

export function CreateEmbeddingsRequestToJSONTyped(value?: CreateEmbeddingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'input': CreateEmbeddingsRequestInputToJSON(value['input']),
    };
}

