/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateResponseRequestInputOneOfInner } from './CreateResponseRequestInputOneOfInner';
import {
    instanceOfCreateResponseRequestInputOneOfInner,
    CreateResponseRequestInputOneOfInnerFromJSON,
    CreateResponseRequestInputOneOfInnerFromJSONTyped,
    CreateResponseRequestInputOneOfInnerToJSON,
} from './CreateResponseRequestInputOneOfInner';

/**
 * @type CreateResponseRequestInput
 * モデルへの入力。文字列またはメッセージオブジェクトの配列を指定できます
 * 
 * @export
 */
export type CreateResponseRequestInput = Array<CreateResponseRequestInputOneOfInner> | string;

export function CreateResponseRequestInputFromJSON(json: any): CreateResponseRequestInput {
    return CreateResponseRequestInputFromJSONTyped(json, false);
}

export function CreateResponseRequestInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestInput {
    if (json == null) {
        return json;
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfCreateResponseRequestInputOneOfInner(item))) {
                return json.map(value => CreateResponseRequestInputOneOfInnerFromJSONTyped(value, true));
            }
        }
    }
    if (Array.isArray(json)) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function CreateResponseRequestInputToJSON(json: any): any {
    return CreateResponseRequestInputToJSONTyped(json, false);
}

export function CreateResponseRequestInputToJSONTyped(value?: CreateResponseRequestInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfCreateResponseRequestInputOneOfInner(item))) {
                return value.map(value => CreateResponseRequestInputOneOfInnerToJSON(value as CreateResponseRequestInputOneOfInner));
            }
        }
    }
    if (Array.isArray(value)) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

