/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageRequestToolChoiceOneOf1
 */
export interface CreateMessageRequestToolChoiceOneOf1 {
    /**
     * 
     * @type {CreateMessageRequestToolChoiceOneOf1TypeEnum}
     * @memberof CreateMessageRequestToolChoiceOneOf1
     */
    type?: CreateMessageRequestToolChoiceOneOf1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateMessageRequestToolChoiceOneOf1
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMessageRequestToolChoiceOneOf1
     */
    disableParallelToolUse?: boolean;
}


/**
 * @export
 */
export const CreateMessageRequestToolChoiceOneOf1TypeEnum = {
    Tool: 'tool'
} as const;
export type CreateMessageRequestToolChoiceOneOf1TypeEnum = typeof CreateMessageRequestToolChoiceOneOf1TypeEnum[keyof typeof CreateMessageRequestToolChoiceOneOf1TypeEnum];


/**
 * Check if a given object implements the CreateMessageRequestToolChoiceOneOf1 interface.
 */
export function instanceOfCreateMessageRequestToolChoiceOneOf1(value: object): value is CreateMessageRequestToolChoiceOneOf1 {
    return true;
}

export function CreateMessageRequestToolChoiceOneOf1FromJSON(json: any): CreateMessageRequestToolChoiceOneOf1 {
    return CreateMessageRequestToolChoiceOneOf1FromJSONTyped(json, false);
}

export function CreateMessageRequestToolChoiceOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageRequestToolChoiceOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'disableParallelToolUse': json['disable_parallel_tool_use'] == null ? undefined : json['disable_parallel_tool_use'],
    };
}

export function CreateMessageRequestToolChoiceOneOf1ToJSON(json: any): CreateMessageRequestToolChoiceOneOf1 {
    return CreateMessageRequestToolChoiceOneOf1ToJSONTyped(json, false);
}

export function CreateMessageRequestToolChoiceOneOf1ToJSONTyped(value?: CreateMessageRequestToolChoiceOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'disable_parallel_tool_use': value['disableParallelToolUse'],
    };
}

