/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMessageRequestMetadata } from './CreateMessageRequestMetadata';
import {
    CreateMessageRequestMetadataFromJSON,
    CreateMessageRequestMetadataFromJSONTyped,
    CreateMessageRequestMetadataToJSON,
    CreateMessageRequestMetadataToJSONTyped,
} from './CreateMessageRequestMetadata';
import type { CreateMessageRequestToolsInner } from './CreateMessageRequestToolsInner';
import {
    CreateMessageRequestToolsInnerFromJSON,
    CreateMessageRequestToolsInnerFromJSONTyped,
    CreateMessageRequestToolsInnerToJSON,
    CreateMessageRequestToolsInnerToJSONTyped,
} from './CreateMessageRequestToolsInner';
import type { CreateMessageRequestMessagesInner } from './CreateMessageRequestMessagesInner';
import {
    CreateMessageRequestMessagesInnerFromJSON,
    CreateMessageRequestMessagesInnerFromJSONTyped,
    CreateMessageRequestMessagesInnerToJSON,
    CreateMessageRequestMessagesInnerToJSONTyped,
} from './CreateMessageRequestMessagesInner';
import type { CreateMessageRequestToolChoice } from './CreateMessageRequestToolChoice';
import {
    CreateMessageRequestToolChoiceFromJSON,
    CreateMessageRequestToolChoiceFromJSONTyped,
    CreateMessageRequestToolChoiceToJSON,
    CreateMessageRequestToolChoiceToJSONTyped,
} from './CreateMessageRequestToolChoice';

/**
 * 
 * @export
 * @interface CreateMessageRequest
 */
export interface CreateMessageRequest {
    /**
     * 使用するモデル名
     * @type {string}
     * @memberof CreateMessageRequest
     */
    model: string;
    /**
     * 会話を構成するメッセージオブジェクトのリスト
     * @type {Array<CreateMessageRequestMessagesInner>}
     * @memberof CreateMessageRequest
     */
    messages: Array<CreateMessageRequestMessagesInner>;
    /**
     * 生成する最大トークン数
     * @type {number}
     * @memberof CreateMessageRequest
     */
    maxTokens: number;
    /**
     * システムプロンプト
     * @type {string}
     * @memberof CreateMessageRequest
     */
    system?: string;
    /**
     * ストリーミング応答を有効にするかどうか
     * @type {boolean}
     * @memberof CreateMessageRequest
     */
    stream?: boolean;
    /**
     * 生成の多様性を制御するパラメータ。値が高いほど多様な応答が生成され、値が低いほど決定的な応答が生成されます。
     * @type {number}
     * @memberof CreateMessageRequest
     */
    temperature?: number;
    /**
     * Nucleus sampling の確率質量
     * @type {number}
     * @memberof CreateMessageRequest
     */
    topP?: number;
    /**
     * Top-k サンプリングのパラメータ
     * @type {number}
     * @memberof CreateMessageRequest
     */
    topK?: number;
    /**
     * 生成を停止すべきシーケンスのリスト
     * @type {Array<string>}
     * @memberof CreateMessageRequest
     */
    stopSequences?: Array<string>;
    /**
     * モデルが呼び出し可能なツールのリスト
     * @type {Array<CreateMessageRequestToolsInner>}
     * @memberof CreateMessageRequest
     */
    tools?: Array<CreateMessageRequestToolsInner>;
    /**
     * 
     * @type {CreateMessageRequestToolChoice}
     * @memberof CreateMessageRequest
     */
    toolChoice?: CreateMessageRequestToolChoice;
    /**
     * 
     * @type {CreateMessageRequestMetadata}
     * @memberof CreateMessageRequest
     */
    metadata?: CreateMessageRequestMetadata;
}

/**
 * Check if a given object implements the CreateMessageRequest interface.
 */
export function instanceOfCreateMessageRequest(value: object): value is CreateMessageRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if ((!('maxTokens' in (value as Record<string, any>)) && !('max_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxTokens'] === undefined && (value as Record<string, any>)['max_tokens'] === undefined)) return false;
    return true;
}

export function CreateMessageRequestFromJSON(json: any): CreateMessageRequest {
    return CreateMessageRequestFromJSONTyped(json, false);
}

export function CreateMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'messages': ((json['messages'] as Array<any>).map(CreateMessageRequestMessagesInnerFromJSON)),
        'maxTokens': json['max_tokens'],
        'system': json['system'] == null ? undefined : json['system'],
        'stream': json['stream'] == null ? undefined : json['stream'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'topP': json['top_p'] == null ? undefined : json['top_p'],
        'topK': json['top_k'] == null ? undefined : json['top_k'],
        'stopSequences': json['stop_sequences'] == null ? undefined : json['stop_sequences'],
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(CreateMessageRequestToolsInnerFromJSON)),
        'toolChoice': json['tool_choice'] == null ? undefined : CreateMessageRequestToolChoiceFromJSON(json['tool_choice']),
        'metadata': json['metadata'] == null ? undefined : CreateMessageRequestMetadataFromJSON(json['metadata']),
    };
}

export function CreateMessageRequestToJSON(json: any): CreateMessageRequest {
    return CreateMessageRequestToJSONTyped(json, false);
}

export function CreateMessageRequestToJSONTyped(value?: CreateMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'messages': ((value['messages'] as Array<any>).map(CreateMessageRequestMessagesInnerToJSON)),
        'max_tokens': value['maxTokens'],
        'system': value['system'],
        'stream': value['stream'],
        'temperature': value['temperature'],
        'top_p': value['topP'],
        'top_k': value['topK'],
        'stop_sequences': value['stopSequences'],
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(CreateMessageRequestToolsInnerToJSON)),
        'tool_choice': CreateMessageRequestToolChoiceToJSON(value['toolChoice']),
        'metadata': CreateMessageRequestMetadataToJSON(value['metadata']),
    };
}

