/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageRequestMessagesInnerContentOneOfInnerSource
 */
export interface CreateMessageRequestMessagesInnerContentOneOfInnerSource {
    /**
     * 
     * @type {CreateMessageRequestMessagesInnerContentOneOfInnerSourceTypeEnum}
     * @memberof CreateMessageRequestMessagesInnerContentOneOfInnerSource
     */
    type?: CreateMessageRequestMessagesInnerContentOneOfInnerSourceTypeEnum;
    /**
     * 
     * @type {CreateMessageRequestMessagesInnerContentOneOfInnerSourceMediaTypeEnum}
     * @memberof CreateMessageRequestMessagesInnerContentOneOfInnerSource
     */
    mediaType?: CreateMessageRequestMessagesInnerContentOneOfInnerSourceMediaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateMessageRequestMessagesInnerContentOneOfInnerSource
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMessageRequestMessagesInnerContentOneOfInnerSource
     */
    url?: string;
}


/**
 * @export
 */
export const CreateMessageRequestMessagesInnerContentOneOfInnerSourceTypeEnum = {
    Base64: 'base64',
    Url: 'url'
} as const;
export type CreateMessageRequestMessagesInnerContentOneOfInnerSourceTypeEnum = typeof CreateMessageRequestMessagesInnerContentOneOfInnerSourceTypeEnum[keyof typeof CreateMessageRequestMessagesInnerContentOneOfInnerSourceTypeEnum];

/**
 * @export
 */
export const CreateMessageRequestMessagesInnerContentOneOfInnerSourceMediaTypeEnum = {
    ImageJpeg: 'image/jpeg',
    ImagePng: 'image/png',
    ImageGif: 'image/gif',
    ImageWebp: 'image/webp'
} as const;
export type CreateMessageRequestMessagesInnerContentOneOfInnerSourceMediaTypeEnum = typeof CreateMessageRequestMessagesInnerContentOneOfInnerSourceMediaTypeEnum[keyof typeof CreateMessageRequestMessagesInnerContentOneOfInnerSourceMediaTypeEnum];


/**
 * Check if a given object implements the CreateMessageRequestMessagesInnerContentOneOfInnerSource interface.
 */
export function instanceOfCreateMessageRequestMessagesInnerContentOneOfInnerSource(value: object): value is CreateMessageRequestMessagesInnerContentOneOfInnerSource {
    return true;
}

export function CreateMessageRequestMessagesInnerContentOneOfInnerSourceFromJSON(json: any): CreateMessageRequestMessagesInnerContentOneOfInnerSource {
    return CreateMessageRequestMessagesInnerContentOneOfInnerSourceFromJSONTyped(json, false);
}

export function CreateMessageRequestMessagesInnerContentOneOfInnerSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageRequestMessagesInnerContentOneOfInnerSource {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'mediaType': json['media_type'] == null ? undefined : json['media_type'],
        'data': json['data'] == null ? undefined : json['data'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function CreateMessageRequestMessagesInnerContentOneOfInnerSourceToJSON(json: any): CreateMessageRequestMessagesInnerContentOneOfInnerSource {
    return CreateMessageRequestMessagesInnerContentOneOfInnerSourceToJSONTyped(json, false);
}

export function CreateMessageRequestMessagesInnerContentOneOfInnerSourceToJSONTyped(value?: CreateMessageRequestMessagesInnerContentOneOfInnerSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'media_type': value['mediaType'],
        'data': value['data'],
        'url': value['url'],
    };
}

