/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateMessageRequestToolChoiceOneOf } from './CreateMessageRequestToolChoiceOneOf';
import {
    instanceOfCreateMessageRequestToolChoiceOneOf,
    CreateMessageRequestToolChoiceOneOfFromJSON,
    CreateMessageRequestToolChoiceOneOfFromJSONTyped,
    CreateMessageRequestToolChoiceOneOfToJSON,
} from './CreateMessageRequestToolChoiceOneOf';
import type { CreateMessageRequestToolChoiceOneOf1 } from './CreateMessageRequestToolChoiceOneOf1';
import {
    instanceOfCreateMessageRequestToolChoiceOneOf1,
    CreateMessageRequestToolChoiceOneOf1FromJSON,
    CreateMessageRequestToolChoiceOneOf1FromJSONTyped,
    CreateMessageRequestToolChoiceOneOf1ToJSON,
} from './CreateMessageRequestToolChoiceOneOf1';

/**
 * @type CreateMessageRequestToolChoice
 * モデルがツールを使用する方法の制御
 * @export
 */
export type CreateMessageRequestToolChoice = CreateMessageRequestToolChoiceOneOf | CreateMessageRequestToolChoiceOneOf1;

export function CreateMessageRequestToolChoiceFromJSON(json: any): CreateMessageRequestToolChoice {
    return CreateMessageRequestToolChoiceFromJSONTyped(json, false);
}

export function CreateMessageRequestToolChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageRequestToolChoice {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCreateMessageRequestToolChoiceOneOf(json)) {
        return CreateMessageRequestToolChoiceOneOfFromJSONTyped(json, true);
    }
    if (instanceOfCreateMessageRequestToolChoiceOneOf1(json)) {
        return CreateMessageRequestToolChoiceOneOf1FromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateMessageRequestToolChoiceToJSON(json: any): any {
    return CreateMessageRequestToolChoiceToJSONTyped(json, false);
}

export function CreateMessageRequestToolChoiceToJSONTyped(value?: CreateMessageRequestToolChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCreateMessageRequestToolChoiceOneOf(value)) {
        return CreateMessageRequestToolChoiceOneOfToJSON(value as CreateMessageRequestToolChoiceOneOf);
    }
    if (instanceOfCreateMessageRequestToolChoiceOneOf1(value)) {
        return CreateMessageRequestToolChoiceOneOf1ToJSON(value as CreateMessageRequestToolChoiceOneOf1);
    }
    return {};
}

