/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateMessageRequestMessagesInnerContentOneOfInner } from './CreateMessageRequestMessagesInnerContentOneOfInner';
import {
    instanceOfCreateMessageRequestMessagesInnerContentOneOfInner,
    CreateMessageRequestMessagesInnerContentOneOfInnerFromJSON,
    CreateMessageRequestMessagesInnerContentOneOfInnerFromJSONTyped,
    CreateMessageRequestMessagesInnerContentOneOfInnerToJSON,
} from './CreateMessageRequestMessagesInnerContentOneOfInner';

/**
 * @type CreateMessageRequestMessagesInnerContent
 * メッセージの内容（文字列またはコンテンツブロックの配列）
 * @export
 */
export type CreateMessageRequestMessagesInnerContent = Array<CreateMessageRequestMessagesInnerContentOneOfInner> | string;

export function CreateMessageRequestMessagesInnerContentFromJSON(json: any): CreateMessageRequestMessagesInnerContent {
    return CreateMessageRequestMessagesInnerContentFromJSONTyped(json, false);
}

export function CreateMessageRequestMessagesInnerContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageRequestMessagesInnerContent {
    if (json == null) {
        return json;
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfCreateMessageRequestMessagesInnerContentOneOfInner(item))) {
                return json.map(value => CreateMessageRequestMessagesInnerContentOneOfInnerFromJSONTyped(value, true));
            }
        }
    }
    if (Array.isArray(json)) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function CreateMessageRequestMessagesInnerContentToJSON(json: any): any {
    return CreateMessageRequestMessagesInnerContentToJSONTyped(json, false);
}

export function CreateMessageRequestMessagesInnerContentToJSONTyped(value?: CreateMessageRequestMessagesInnerContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfCreateMessageRequestMessagesInnerContentOneOfInner(item))) {
                return value.map(value => CreateMessageRequestMessagesInnerContentOneOfInnerToJSON(value as CreateMessageRequestMessagesInnerContentOneOfInner));
            }
        }
    }
    if (Array.isArray(value)) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

