/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageRequestToolsInner
 */
export interface CreateMessageRequestToolsInner {
    /**
     * ツールの名前
     * @type {string}
     * @memberof CreateMessageRequestToolsInner
     */
    name?: string;
    /**
     * ツールの説明
     * @type {string}
     * @memberof CreateMessageRequestToolsInner
     */
    description?: string;
    /**
     * ツールの入力スキーマ
     * @type {object}
     * @memberof CreateMessageRequestToolsInner
     */
    inputSchema?: object;
}

/**
 * Check if a given object implements the CreateMessageRequestToolsInner interface.
 */
export function instanceOfCreateMessageRequestToolsInner(value: object): value is CreateMessageRequestToolsInner {
    return true;
}

export function CreateMessageRequestToolsInnerFromJSON(json: any): CreateMessageRequestToolsInner {
    return CreateMessageRequestToolsInnerFromJSONTyped(json, false);
}

export function CreateMessageRequestToolsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageRequestToolsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'inputSchema': json['input_schema'] == null ? undefined : json['input_schema'],
    };
}

export function CreateMessageRequestToolsInnerToJSON(json: any): CreateMessageRequestToolsInner {
    return CreateMessageRequestToolsInnerToJSONTyped(json, false);
}

export function CreateMessageRequestToolsInnerToJSONTyped(value?: CreateMessageRequestToolsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'input_schema': value['inputSchema'],
    };
}

