/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddingResponseDataInner } from './EmbeddingResponseDataInner';
import {
    EmbeddingResponseDataInnerFromJSON,
    EmbeddingResponseDataInnerFromJSONTyped,
    EmbeddingResponseDataInnerToJSON,
    EmbeddingResponseDataInnerToJSONTyped,
} from './EmbeddingResponseDataInner';

/**
 * 
 * @export
 * @interface EmbeddingResponse
 */
export interface EmbeddingResponse {
    /**
     * Model used.
     * @type {string}
     * @memberof EmbeddingResponse
     */
    model: string;
    /**
     * 
     * @type {Array<EmbeddingResponseDataInner>}
     * @memberof EmbeddingResponse
     */
    data: Array<EmbeddingResponseDataInner>;
}

/**
 * Check if a given object implements the EmbeddingResponse interface.
 */
export function instanceOfEmbeddingResponse(value: object): value is EmbeddingResponse {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EmbeddingResponseFromJSON(json: any): EmbeddingResponse {
    return EmbeddingResponseFromJSONTyped(json, false);
}

export function EmbeddingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'data': ((json['data'] as Array<any>).map(EmbeddingResponseDataInnerFromJSON)),
    };
}

export function EmbeddingResponseToJSON(json: any): EmbeddingResponse {
    return EmbeddingResponseToJSONTyped(json, false);
}

export function EmbeddingResponseToJSONTyped(value?: EmbeddingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'data': ((value['data'] as Array<any>).map(EmbeddingResponseDataInnerToJSON)),
    };
}

