/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FunctionObject
 */
export interface FunctionObject {
    /**
     * ツールの説明。
     * @type {string}
     * @memberof FunctionObject
     */
    description?: string;
    /**
     * ツールの名前。英数字、アンダースコア、ハイフンのみ使用可能で、最大64文字まで指定できます。
     * @type {string}
     * @memberof FunctionObject
     */
    name: string;
    /**
     * ツールのパラメータ仕様。
     * @type {object}
     * @memberof FunctionObject
     */
    parameters?: object;
}

/**
 * Check if a given object implements the FunctionObject interface.
 */
export function instanceOfFunctionObject(value: object): value is FunctionObject {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FunctionObjectFromJSON(json: any): FunctionObject {
    return FunctionObjectFromJSONTyped(json, false);
}

export function FunctionObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionObject {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function FunctionObjectToJSON(json: any): FunctionObject {
    return FunctionObjectToJSONTyped(json, false);
}

export function FunctionObjectToJSONTyped(value?: FunctionObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'parameters': value['parameters'],
    };
}

