/* tslint:disable */
/* eslint-disable */
/**
 * さくらの AI Engine Inference API
 * --- Copyright SAKURA internet Inc.  # さくらの AI Engine チャット生成 / 音声文字起こし / 音声合成 エンドポイント  ### 基本的な使い方 <div class=\"warning\">   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/ai-engine/02-howto.html\">さくらのAI Engine 利用手順 | さくらのクラウド マニュアル</a></li></ul> </div>  ### APIエンドポイント https://api.ai.sakura.ad.jp  ---
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TtsSynthesisRequest
 */
export interface TtsSynthesisRequest {
    [key: string]: any | any;
    /**
     * アクセント句のリスト
     * @type {Array<{ [key: string]: any; }>}
     * @memberof TtsSynthesisRequest
     */
    accentPhrases: Array<{ [key: string]: any; }>;
    /**
     * 全体の話速
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    speedScale: number;
    /**
     * 全体の音高
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    pitchScale: number;
    /**
     * 全体の抑揚
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    intonationScale: number;
    /**
     * 全体の音量
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    volumeScale: number;
    /**
     * 音声の前の無音時間
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    prePhonemeLength: number;
    /**
     * 音声の後の無音時間
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    postPhonemeLength: number;
    /**
     * 句読点などの無音時間。nullのときは無視される。デフォルト値はnull
     * 
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    pauseLength?: number | null;
    /**
     * 句読点などの無音時間（倍率）。デフォルト値は1
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    pauseLengthScale?: number;
    /**
     * 音声データの出力サンプリングレート
     * @type {number}
     * @memberof TtsSynthesisRequest
     */
    outputSamplingRate: number;
    /**
     * 音声データをステレオ出力するか否か
     * @type {boolean}
     * @memberof TtsSynthesisRequest
     */
    outputStereo: boolean;
    /**
     * 読み（かな）。
     * [読み取り専用] AquesTalk風記法によるテキスト。音声合成用のクエリとしては無視される
     * 
     * @type {string}
     * @memberof TtsSynthesisRequest
     */
    kana: string;
}

/**
 * Check if a given object implements the TtsSynthesisRequest interface.
 */
export function instanceOfTtsSynthesisRequest(value: object): value is TtsSynthesisRequest {
    if ((!('accentPhrases' in (value as Record<string, any>)) && !('accent_phrases' in (value as Record<string, any>))) || ((value as Record<string, any>)['accentPhrases'] === undefined && (value as Record<string, any>)['accent_phrases'] === undefined)) return false;
    if (!('speedScale' in value) || value['speedScale'] === undefined) return false;
    if (!('pitchScale' in value) || value['pitchScale'] === undefined) return false;
    if (!('intonationScale' in value) || value['intonationScale'] === undefined) return false;
    if (!('volumeScale' in value) || value['volumeScale'] === undefined) return false;
    if (!('prePhonemeLength' in value) || value['prePhonemeLength'] === undefined) return false;
    if (!('postPhonemeLength' in value) || value['postPhonemeLength'] === undefined) return false;
    if (!('outputSamplingRate' in value) || value['outputSamplingRate'] === undefined) return false;
    if (!('outputStereo' in value) || value['outputStereo'] === undefined) return false;
    if (!('kana' in value) || value['kana'] === undefined) return false;
    return true;
}

export function TtsSynthesisRequestFromJSON(json: any): TtsSynthesisRequest {
    return TtsSynthesisRequestFromJSONTyped(json, false);
}

export function TtsSynthesisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TtsSynthesisRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'accentPhrases': json['accent_phrases'],
        'speedScale': json['speedScale'],
        'pitchScale': json['pitchScale'],
        'intonationScale': json['intonationScale'],
        'volumeScale': json['volumeScale'],
        'prePhonemeLength': json['prePhonemeLength'],
        'postPhonemeLength': json['postPhonemeLength'],
        'pauseLength': json['pauseLength'] === undefined ? undefined : json['pauseLength'] === null ? null : json['pauseLength'],
        'pauseLengthScale': json['pauseLengthScale'] == null ? undefined : json['pauseLengthScale'],
        'outputSamplingRate': json['outputSamplingRate'],
        'outputStereo': json['outputStereo'],
        'kana': json['kana'],
    };
}

export function TtsSynthesisRequestToJSON(json: any): TtsSynthesisRequest {
    return TtsSynthesisRequestToJSONTyped(json, false);
}

export function TtsSynthesisRequestToJSONTyped(value?: TtsSynthesisRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'accent_phrases': value['accentPhrases'],
        'speedScale': value['speedScale'],
        'pitchScale': value['pitchScale'],
        'intonationScale': value['intonationScale'],
        'volumeScale': value['volumeScale'],
        'prePhonemeLength': value['prePhonemeLength'],
        'postPhonemeLength': value['postPhonemeLength'],
        'pauseLength': value['pauseLength'],
        'pauseLengthScale': value['pauseLengthScale'],
        'outputSamplingRate': value['outputSamplingRate'],
        'outputStereo': value['outputStereo'],
        'kana': value['kana'],
    };
}

