/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthConditionsIpRestrictionOneOf
 */
export interface AuthConditionsIpRestrictionOneOf {
    /**
     * allow_all = すべて許可
     * allow_list = source_networkで許可リスト指定
     * 
     * @type {AuthConditionsIpRestrictionOneOfModeEnum}
     * @memberof AuthConditionsIpRestrictionOneOf
     */
    mode?: AuthConditionsIpRestrictionOneOfModeEnum;
}


/**
 * @export
 */
export const AuthConditionsIpRestrictionOneOfModeEnum = {
    AllowAll: 'allow_all'
} as const;
export type AuthConditionsIpRestrictionOneOfModeEnum = typeof AuthConditionsIpRestrictionOneOfModeEnum[keyof typeof AuthConditionsIpRestrictionOneOfModeEnum];


/**
 * Check if a given object implements the AuthConditionsIpRestrictionOneOf interface.
 */
export function instanceOfAuthConditionsIpRestrictionOneOf(value: object): value is AuthConditionsIpRestrictionOneOf {
    return true;
}

export function AuthConditionsIpRestrictionOneOfFromJSON(json: any): AuthConditionsIpRestrictionOneOf {
    return AuthConditionsIpRestrictionOneOfFromJSONTyped(json, false);
}

export function AuthConditionsIpRestrictionOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthConditionsIpRestrictionOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function AuthConditionsIpRestrictionOneOfToJSON(json: any): AuthConditionsIpRestrictionOneOf {
    return AuthConditionsIpRestrictionOneOfToJSONTyped(json, false);
}

export function AuthConditionsIpRestrictionOneOfToJSONTyped(value?: AuthConditionsIpRestrictionOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
    };
}

