/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSsoProfileRequest
 */
export interface CreateSsoProfileRequest {
    /**
     * SSOプロファイル名
     * @type {string}
     * @memberof CreateSsoProfileRequest
     */
    name: string;
    /**
     * SSOプロファイルの説明
     * @type {string}
     * @memberof CreateSsoProfileRequest
     */
    description: string;
    /**
     * IdPのエンティティID
     * @type {string}
     * @memberof CreateSsoProfileRequest
     */
    idpEntityId: string;
    /**
     * IdPのログインURL
     * @type {string}
     * @memberof CreateSsoProfileRequest
     */
    idpLoginUrl: string;
    /**
     * IdPのログアウトURL
     * @type {string}
     * @memberof CreateSsoProfileRequest
     */
    idpLogoutUrl: string;
    /**
     * IdPのX.509証明書
     * @type {string}
     * @memberof CreateSsoProfileRequest
     */
    idpCertificate: string;
}

/**
 * Check if a given object implements the CreateSsoProfileRequest interface.
 */
export function instanceOfCreateSsoProfileRequest(value: object): value is CreateSsoProfileRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('idpEntityId' in (value as Record<string, any>)) && !('idp_entity_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['idpEntityId'] === undefined && (value as Record<string, any>)['idp_entity_id'] === undefined)) return false;
    if ((!('idpLoginUrl' in (value as Record<string, any>)) && !('idp_login_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['idpLoginUrl'] === undefined && (value as Record<string, any>)['idp_login_url'] === undefined)) return false;
    if ((!('idpLogoutUrl' in (value as Record<string, any>)) && !('idp_logout_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['idpLogoutUrl'] === undefined && (value as Record<string, any>)['idp_logout_url'] === undefined)) return false;
    if ((!('idpCertificate' in (value as Record<string, any>)) && !('idp_certificate' in (value as Record<string, any>))) || ((value as Record<string, any>)['idpCertificate'] === undefined && (value as Record<string, any>)['idp_certificate'] === undefined)) return false;
    return true;
}

export function CreateSsoProfileRequestFromJSON(json: any): CreateSsoProfileRequest {
    return CreateSsoProfileRequestFromJSONTyped(json, false);
}

export function CreateSsoProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSsoProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'idpEntityId': json['idp_entity_id'],
        'idpLoginUrl': json['idp_login_url'],
        'idpLogoutUrl': json['idp_logout_url'],
        'idpCertificate': json['idp_certificate'],
    };
}

export function CreateSsoProfileRequestToJSON(json: any): CreateSsoProfileRequest {
    return CreateSsoProfileRequestToJSONTyped(json, false);
}

export function CreateSsoProfileRequestToJSONTyped(value?: CreateSsoProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'idp_entity_id': value['idpEntityId'],
        'idp_login_url': value['idpLoginUrl'],
        'idp_logout_url': value['idpLogoutUrl'],
        'idp_certificate': value['idpCertificate'],
    };
}

