/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateServicePrincipalRequest
 */
export interface CreateServicePrincipalRequest {
    /**
     * プロジェクトID
     * @type {number}
     * @memberof CreateServicePrincipalRequest
     */
    projectId: number;
    /**
     * サービスプリンシパル名
     * @type {string}
     * @memberof CreateServicePrincipalRequest
     */
    name: string;
    /**
     * サービスプリンシパルの説明
     * @type {string}
     * @memberof CreateServicePrincipalRequest
     */
    description: string;
}

/**
 * Check if a given object implements the CreateServicePrincipalRequest interface.
 */
export function instanceOfCreateServicePrincipalRequest(value: object): value is CreateServicePrincipalRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateServicePrincipalRequestFromJSON(json: any): CreateServicePrincipalRequest {
    return CreateServicePrincipalRequestFromJSONTyped(json, false);
}

export function CreateServicePrincipalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServicePrincipalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function CreateServicePrincipalRequestToJSON(json: any): CreateServicePrincipalRequest {
    return CreateServicePrincipalRequestToJSONTyped(json, false);
}

export function CreateServicePrincipalRequestToJSONTyped(value?: CreateServicePrincipalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'name': value['name'],
        'description': value['description'],
    };
}

