/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiKeyRequest
 */
export interface CreateApiKeyRequest {
    /**
     * プロジェクトID
     * @type {number}
     * @memberof CreateApiKeyRequest
     */
    projectId: number;
    /**
     * APIキー名
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    name: string;
    /**
     * APIキーの説明
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    description: string;
    /**
     * APIキーがシングルサーバコントロールパネルで利用される場合は必須
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    serverResourceId?: string;
    /**
     * IAMのロール
     * @type {Array<string>}
     * @memberof CreateApiKeyRequest
     */
    iamRoles: Array<string>;
    /**
     * ゾーンを指定。APIキーがシングルサーバコントロールパネルで利用される場合は必須。
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    zoneId?: string;
}

/**
 * Check if a given object implements the CreateApiKeyRequest interface.
 */
export function instanceOfCreateApiKeyRequest(value: object): value is CreateApiKeyRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('iamRoles' in (value as Record<string, any>)) && !('iam_roles' in (value as Record<string, any>))) || ((value as Record<string, any>)['iamRoles'] === undefined && (value as Record<string, any>)['iam_roles'] === undefined)) return false;
    return true;
}

export function CreateApiKeyRequestFromJSON(json: any): CreateApiKeyRequest {
    return CreateApiKeyRequestFromJSONTyped(json, false);
}

export function CreateApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'name': json['name'],
        'description': json['description'],
        'serverResourceId': json['server_resource_id'] == null ? undefined : json['server_resource_id'],
        'iamRoles': json['iam_roles'],
        'zoneId': json['zone_id'] == null ? undefined : json['zone_id'],
    };
}

export function CreateApiKeyRequestToJSON(json: any): CreateApiKeyRequest {
    return CreateApiKeyRequestToJSONTyped(json, false);
}

export function CreateApiKeyRequestToJSONTyped(value?: CreateApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'name': value['name'],
        'description': value['description'],
        'server_resource_id': value['serverResourceId'],
        'iam_roles': value['iamRoles'],
        'zone_id': value['zoneId'],
    };
}

