/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * ユーザの名前
     * @type {string}
     * @memberof CreateUserRequest
     */
    name: string;
    /**
     * ユーザのパスワード
     * 英数字とASCII標準文字における記号 !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ のみ受け付ける
     * 英字と数字を必ず含める必要がある
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    password: string;
    /**
     * ユーザコード
     * @type {string}
     * @memberof CreateUserRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    description: string;
    /**
     * SSOプロファイル有効時に外部IdPのログインで利用するメールアドレス
     * @type {string}
     * @memberof CreateUserRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(value: object): value is CreateUserRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
    return CreateUserRequestFromJSONTyped(json, false);
}

export function CreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'password': json['password'],
        'code': json['code'],
        'description': json['description'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function CreateUserRequestToJSON(json: any): CreateUserRequest {
    return CreateUserRequestToJSONTyped(json, false);
}

export function CreateUserRequestToJSONTyped(value?: CreateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'password': value['password'],
        'code': value['code'],
        'description': value['description'],
        'email': value['email'],
    };
}

