/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Folder
 */
export interface Folder {
    /**
     * フォルダID
     * @type {number}
     * @memberof Folder
     */
    readonly id: number;
    /**
     * フォルダ名
     * @type {string}
     * @memberof Folder
     */
    name: string;
    /**
     * 親フォルダID
     * @type {number}
     * @memberof Folder
     */
    parentId: number | null;
    /**
     * フォルダの説明
     * @type {string}
     * @memberof Folder
     */
    description: string;
    /**
     * 作成日時
     * @type {string}
     * @memberof Folder
     */
    readonly createdAt: string;
    /**
     * 更新日時
     * @type {string}
     * @memberof Folder
     */
    readonly updatedAt: string;
}

/**
 * Check if a given object implements the Folder interface.
 */
export function instanceOfFolder(value: object): value is Folder {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('parentId' in (value as Record<string, any>)) && !('parent_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['parentId'] === undefined && (value as Record<string, any>)['parent_id'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function FolderFromJSON(json: any): Folder {
    return FolderFromJSONTyped(json, false);
}

export function FolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Folder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'parentId': json['parent_id'],
        'description': json['description'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function FolderToJSON(json: any): Folder {
    return FolderToJSONTyped(json, false);
}

export function FolderToJSONTyped(value?: Omit<Folder, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'parent_id': value['parentId'],
        'description': value['description'],
    };
}

