/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Http400BadRequestErrorsNonFieldErrorsInner
 */
export interface Http400BadRequestErrorsNonFieldErrorsInner {
    /**
     * エラー内容を説明した文字列
     * @type {string}
     * @memberof Http400BadRequestErrorsNonFieldErrorsInner
     */
    message: string;
    /**
     * エラーの内容を表す文字列
     * @type {string}
     * @memberof Http400BadRequestErrorsNonFieldErrorsInner
     */
    code: string;
}

/**
 * Check if a given object implements the Http400BadRequestErrorsNonFieldErrorsInner interface.
 */
export function instanceOfHttp400BadRequestErrorsNonFieldErrorsInner(value: object): value is Http400BadRequestErrorsNonFieldErrorsInner {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function Http400BadRequestErrorsNonFieldErrorsInnerFromJSON(json: any): Http400BadRequestErrorsNonFieldErrorsInner {
    return Http400BadRequestErrorsNonFieldErrorsInnerFromJSONTyped(json, false);
}

export function Http400BadRequestErrorsNonFieldErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Http400BadRequestErrorsNonFieldErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'code': json['code'],
    };
}

export function Http400BadRequestErrorsNonFieldErrorsInnerToJSON(json: any): Http400BadRequestErrorsNonFieldErrorsInner {
    return Http400BadRequestErrorsNonFieldErrorsInnerToJSONTyped(json, false);
}

export function Http400BadRequestErrorsNonFieldErrorsInnerToJSONTyped(value?: Http400BadRequestErrorsNonFieldErrorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
    };
}

