/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Http503ServiceUnavailable
 */
export interface Http503ServiceUnavailable {
    /**
     * 問題を説明するドキュメントへのURI（基本的にはabout:blank）
     * @type {string}
     * @memberof Http503ServiceUnavailable
     */
    type: string;
    /**
     * HTTPステータスコード
     * @type {number}
     * @memberof Http503ServiceUnavailable
     */
    status: number;
    /**
     * 問題を表す簡単な文字列
     * @type {string}
     * @memberof Http503ServiceUnavailable
     */
    title: string;
    /**
     * 問題の詳細を説明した文字列（人が読んで問題解決に繋がるような説明）
     * @type {string}
     * @memberof Http503ServiceUnavailable
     */
    detail: string;
}

/**
 * Check if a given object implements the Http503ServiceUnavailable interface.
 */
export function instanceOfHttp503ServiceUnavailable(value: object): value is Http503ServiceUnavailable {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function Http503ServiceUnavailableFromJSON(json: any): Http503ServiceUnavailable {
    return Http503ServiceUnavailableFromJSONTyped(json, false);
}

export function Http503ServiceUnavailableFromJSONTyped(json: any, ignoreDiscriminator: boolean): Http503ServiceUnavailable {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'status': json['status'],
        'title': json['title'],
        'detail': json['detail'],
    };
}

export function Http503ServiceUnavailableToJSON(json: any): Http503ServiceUnavailable {
    return Http503ServiceUnavailableToJSONTyped(json, false);
}

export function Http503ServiceUnavailableToJSONTyped(value?: Http503ServiceUnavailable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'status': value['status'],
        'title': value['title'],
        'detail': value['detail'],
    };
}

