/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IamPolicyRole
 */
export interface IamPolicyRole {
    /**
     * 
     * @type {IamPolicyRoleTypeEnum}
     * @memberof IamPolicyRole
     */
    type?: IamPolicyRoleTypeEnum;
    /**
     * IAMロールID
     * @type {string}
     * @memberof IamPolicyRole
     */
    id?: string;
}


/**
 * @export
 */
export const IamPolicyRoleTypeEnum = {
    Preset: 'preset'
} as const;
export type IamPolicyRoleTypeEnum = typeof IamPolicyRoleTypeEnum[keyof typeof IamPolicyRoleTypeEnum];


/**
 * Check if a given object implements the IamPolicyRole interface.
 */
export function instanceOfIamPolicyRole(value: object): value is IamPolicyRole {
    return true;
}

export function IamPolicyRoleFromJSON(json: any): IamPolicyRole {
    return IamPolicyRoleFromJSONTyped(json, false);
}

export function IamPolicyRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): IamPolicyRole {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function IamPolicyRoleToJSON(json: any): IamPolicyRole {
    return IamPolicyRoleToJSONTyped(json, false);
}

export function IamPolicyRoleToJSONTyped(value?: IamPolicyRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

