/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdPolicyRole } from './IdPolicyRole';
import {
    IdPolicyRoleFromJSON,
    IdPolicyRoleFromJSONTyped,
    IdPolicyRoleToJSON,
    IdPolicyRoleToJSONTyped,
} from './IdPolicyRole';
import type { Principal } from './Principal';
import {
    PrincipalFromJSON,
    PrincipalFromJSONTyped,
    PrincipalToJSON,
    PrincipalToJSONTyped,
} from './Principal';

/**
 * 
 * @export
 * @interface IdPolicy
 */
export interface IdPolicy {
    /**
     * 
     * @type {IdPolicyRole}
     * @memberof IdPolicy
     */
    role?: IdPolicyRole;
    /**
     * 
     * @type {Array<Principal>}
     * @memberof IdPolicy
     */
    principals?: Array<Principal>;
}

/**
 * Check if a given object implements the IdPolicy interface.
 */
export function instanceOfIdPolicy(value: object): value is IdPolicy {
    return true;
}

export function IdPolicyFromJSON(json: any): IdPolicy {
    return IdPolicyFromJSONTyped(json, false);
}

export function IdPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : IdPolicyRoleFromJSON(json['role']),
        'principals': json['principals'] == null ? undefined : ((json['principals'] as Array<any>).map(PrincipalFromJSON)),
    };
}

export function IdPolicyToJSON(json: any): IdPolicy {
    return IdPolicyToJSONTyped(json, false);
}

export function IdPolicyToJSONTyped(value?: IdPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': IdPolicyRoleToJSON(value['role']),
        'principals': value['principals'] == null ? undefined : ((value['principals'] as Array<any>).map(PrincipalToJSON)),
    };
}

