/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Folder } from './Folder';
import {
    FolderFromJSON,
    FolderFromJSONTyped,
    FolderToJSON,
    FolderToJSONTyped,
} from './Folder';

/**
 * 
 * @export
 * @interface ListFolders200Response
 */
export interface ListFolders200Response {
    /**
     * データ総数
     * @type {number}
     * @memberof ListFolders200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof ListFolders200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof ListFolders200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<Folder>}
     * @memberof ListFolders200Response
     */
    items: Array<Folder>;
}

/**
 * Check if a given object implements the ListFolders200Response interface.
 */
export function instanceOfListFolders200Response(value: object): value is ListFolders200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListFolders200ResponseFromJSON(json: any): ListFolders200Response {
    return ListFolders200ResponseFromJSONTyped(json, false);
}

export function ListFolders200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFolders200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'items': ((json['items'] as Array<any>).map(FolderFromJSON)),
    };
}

export function ListFolders200ResponseToJSON(json: any): ListFolders200Response {
    return ListFolders200ResponseToJSONTyped(json, false);
}

export function ListFolders200ResponseToJSONTyped(value?: ListFolders200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'items': ((value['items'] as Array<any>).map(FolderToJSON)),
    };
}

