/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IamRole } from './IamRole';
import {
    IamRoleFromJSON,
    IamRoleFromJSONTyped,
    IamRoleToJSON,
    IamRoleToJSONTyped,
} from './IamRole';

/**
 * 
 * @export
 * @interface ListIamRoles200Response
 */
export interface ListIamRoles200Response {
    /**
     * データ総数
     * @type {number}
     * @memberof ListIamRoles200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof ListIamRoles200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof ListIamRoles200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<IamRole>}
     * @memberof ListIamRoles200Response
     */
    items: Array<IamRole>;
}

/**
 * Check if a given object implements the ListIamRoles200Response interface.
 */
export function instanceOfListIamRoles200Response(value: object): value is ListIamRoles200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListIamRoles200ResponseFromJSON(json: any): ListIamRoles200Response {
    return ListIamRoles200ResponseFromJSONTyped(json, false);
}

export function ListIamRoles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIamRoles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'items': ((json['items'] as Array<any>).map(IamRoleFromJSON)),
    };
}

export function ListIamRoles200ResponseToJSON(json: any): ListIamRoles200Response {
    return ListIamRoles200ResponseToJSONTyped(json, false);
}

export function ListIamRoles200ResponseToJSONTyped(value?: ListIamRoles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'items': ((value['items'] as Array<any>).map(IamRoleToJSON)),
    };
}

