/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScimConfigurationPublic } from './ScimConfigurationPublic';
import {
    ScimConfigurationPublicFromJSON,
    ScimConfigurationPublicFromJSONTyped,
    ScimConfigurationPublicToJSON,
    ScimConfigurationPublicToJSONTyped,
} from './ScimConfigurationPublic';

/**
 * 
 * @export
 * @interface ListScimConfigurations200Response
 */
export interface ListScimConfigurations200Response {
    /**
     * データ総数
     * @type {number}
     * @memberof ListScimConfigurations200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof ListScimConfigurations200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof ListScimConfigurations200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<ScimConfigurationPublic>}
     * @memberof ListScimConfigurations200Response
     */
    items: Array<ScimConfigurationPublic>;
}

/**
 * Check if a given object implements the ListScimConfigurations200Response interface.
 */
export function instanceOfListScimConfigurations200Response(value: object): value is ListScimConfigurations200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListScimConfigurations200ResponseFromJSON(json: any): ListScimConfigurations200Response {
    return ListScimConfigurations200ResponseFromJSONTyped(json, false);
}

export function ListScimConfigurations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListScimConfigurations200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'items': ((json['items'] as Array<any>).map(ScimConfigurationPublicFromJSON)),
    };
}

export function ListScimConfigurations200ResponseToJSON(json: any): ListScimConfigurations200Response {
    return ListScimConfigurations200ResponseToJSONTyped(json, false);
}

export function ListScimConfigurations200ResponseToJSONTyped(value?: ListScimConfigurations200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'items': ((value['items'] as Array<any>).map(ScimConfigurationPublicToJSON)),
    };
}

