/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectApiKey } from './ProjectApiKey';
import {
    ProjectApiKeyFromJSON,
    ProjectApiKeyFromJSONTyped,
    ProjectApiKeyToJSON,
    ProjectApiKeyToJSONTyped,
} from './ProjectApiKey';

/**
 * 
 * @export
 * @interface ListApiKeys200Response
 */
export interface ListApiKeys200Response {
    /**
     * データ総数
     * @type {number}
     * @memberof ListApiKeys200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof ListApiKeys200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof ListApiKeys200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<ProjectApiKey>}
     * @memberof ListApiKeys200Response
     */
    items: Array<ProjectApiKey>;
}

/**
 * Check if a given object implements the ListApiKeys200Response interface.
 */
export function instanceOfListApiKeys200Response(value: object): value is ListApiKeys200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListApiKeys200ResponseFromJSON(json: any): ListApiKeys200Response {
    return ListApiKeys200ResponseFromJSONTyped(json, false);
}

export function ListApiKeys200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApiKeys200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'items': ((json['items'] as Array<any>).map(ProjectApiKeyFromJSON)),
    };
}

export function ListApiKeys200ResponseToJSON(json: any): ListApiKeys200Response {
    return ListApiKeys200ResponseToJSONTyped(json, false);
}

export function ListApiKeys200ResponseToJSONTyped(value?: ListApiKeys200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'items': ((value['items'] as Array<any>).map(ProjectApiKeyToJSON)),
    };
}

