/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServicePrincipalKey } from './ServicePrincipalKey';
import {
    ServicePrincipalKeyFromJSON,
    ServicePrincipalKeyFromJSONTyped,
    ServicePrincipalKeyToJSON,
    ServicePrincipalKeyToJSONTyped,
} from './ServicePrincipalKey';

/**
 * 
 * @export
 * @interface ListServicePrincipalKeys200Response
 */
export interface ListServicePrincipalKeys200Response {
    /**
     * データ総数
     * @type {number}
     * @memberof ListServicePrincipalKeys200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof ListServicePrincipalKeys200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof ListServicePrincipalKeys200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<ServicePrincipalKey>}
     * @memberof ListServicePrincipalKeys200Response
     */
    items: Array<ServicePrincipalKey>;
}

/**
 * Check if a given object implements the ListServicePrincipalKeys200Response interface.
 */
export function instanceOfListServicePrincipalKeys200Response(value: object): value is ListServicePrincipalKeys200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListServicePrincipalKeys200ResponseFromJSON(json: any): ListServicePrincipalKeys200Response {
    return ListServicePrincipalKeys200ResponseFromJSONTyped(json, false);
}

export function ListServicePrincipalKeys200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListServicePrincipalKeys200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'items': ((json['items'] as Array<any>).map(ServicePrincipalKeyFromJSON)),
    };
}

export function ListServicePrincipalKeys200ResponseToJSON(json: any): ListServicePrincipalKeys200Response {
    return ListServicePrincipalKeys200ResponseToJSONTyped(json, false);
}

export function ListServicePrincipalKeys200ResponseToJSONTyped(value?: ListServicePrincipalKeys200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'items': ((value['items'] as Array<any>).map(ServicePrincipalKeyToJSON)),
    };
}

