/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdRole } from './IdRole';
import {
    IdRoleFromJSON,
    IdRoleFromJSONTyped,
    IdRoleToJSON,
    IdRoleToJSONTyped,
} from './IdRole';

/**
 * 
 * @export
 * @interface ListIdRoles200Response
 */
export interface ListIdRoles200Response {
    /**
     * データ総数
     * @type {number}
     * @memberof ListIdRoles200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof ListIdRoles200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof ListIdRoles200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<IdRole>}
     * @memberof ListIdRoles200Response
     */
    items: Array<IdRole>;
}

/**
 * Check if a given object implements the ListIdRoles200Response interface.
 */
export function instanceOfListIdRoles200Response(value: object): value is ListIdRoles200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListIdRoles200ResponseFromJSON(json: any): ListIdRoles200Response {
    return ListIdRoles200ResponseFromJSONTyped(json, false);
}

export function ListIdRoles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIdRoles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'items': ((json['items'] as Array<any>).map(IdRoleFromJSON)),
    };
}

export function ListIdRoles200ResponseToJSON(json: any): ListIdRoles200Response {
    return ListIdRoles200ResponseToJSONTyped(json, false);
}

export function ListIdRoles200ResponseToJSONTyped(value?: ListIdRoles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'items': ((value['items'] as Array<any>).map(IdRoleToJSON)),
    };
}

