/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SSOProfile } from './SSOProfile';
import {
    SSOProfileFromJSON,
    SSOProfileFromJSONTyped,
    SSOProfileToJSON,
    SSOProfileToJSONTyped,
} from './SSOProfile';

/**
 * 
 * @export
 * @interface ListSsoProfiles200Response
 */
export interface ListSsoProfiles200Response {
    /**
     * データ総数
     * @type {number}
     * @memberof ListSsoProfiles200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof ListSsoProfiles200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof ListSsoProfiles200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<SSOProfile>}
     * @memberof ListSsoProfiles200Response
     */
    items: Array<SSOProfile>;
}

/**
 * Check if a given object implements the ListSsoProfiles200Response interface.
 */
export function instanceOfListSsoProfiles200Response(value: object): value is ListSsoProfiles200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListSsoProfiles200ResponseFromJSON(json: any): ListSsoProfiles200Response {
    return ListSsoProfiles200ResponseFromJSONTyped(json, false);
}

export function ListSsoProfiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSsoProfiles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'items': ((json['items'] as Array<any>).map(SSOProfileFromJSON)),
    };
}

export function ListSsoProfiles200ResponseToJSON(json: any): ListSsoProfiles200Response {
    return ListSsoProfiles200ResponseToJSONTyped(json, false);
}

export function ListSsoProfiles200ResponseToJSONTyped(value?: ListSsoProfiles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'items': ((value['items'] as Array<any>).map(SSOProfileToJSON)),
    };
}

