/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveProjects
 */
export interface MoveProjects {
    /**
     * 移動するプロジェクトID
     * @type {Array<number>}
     * @memberof MoveProjects
     */
    projectIds: Array<number>;
    /**
     * 移動先のフォルダID
     * @type {number}
     * @memberof MoveProjects
     */
    parentFolderId: number | null;
}

/**
 * Check if a given object implements the MoveProjects interface.
 */
export function instanceOfMoveProjects(value: object): value is MoveProjects {
    if ((!('projectIds' in (value as Record<string, any>)) && !('project_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectIds'] === undefined && (value as Record<string, any>)['project_ids'] === undefined)) return false;
    if ((!('parentFolderId' in (value as Record<string, any>)) && !('parent_folder_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['parentFolderId'] === undefined && (value as Record<string, any>)['parent_folder_id'] === undefined)) return false;
    return true;
}

export function MoveProjectsFromJSON(json: any): MoveProjects {
    return MoveProjectsFromJSONTyped(json, false);
}

export function MoveProjectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveProjects {
    if (json == null) {
        return json;
    }
    return {
        
        'projectIds': json['project_ids'],
        'parentFolderId': json['parent_folder_id'],
    };
}

export function MoveProjectsToJSON(json: any): MoveProjects {
    return MoveProjectsToJSONTyped(json, false);
}

export function MoveProjectsToJSONTyped(value?: MoveProjects | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_ids': value['projectIds'],
        'parent_folder_id': value['parentFolderId'],
    };
}

