/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordPolicy
 */
export interface PasswordPolicy {
    /**
     * パスワードの最小文字数 (8文字以上64文字以下; デフォルトは`8`)
     * @type {number}
     * @memberof PasswordPolicy
     */
    minLength: number;
    /**
     * 大文字を必須とするか (デフォルトは`false`)
     * `false` であっても英字自体は必須
     * 
     * @type {boolean}
     * @memberof PasswordPolicy
     */
    requireUppercase: boolean;
    /**
     * 小文字を必須とするか (デフォルトは`false`)
     * `false` であっても英字自体は必須
     * 
     * @type {boolean}
     * @memberof PasswordPolicy
     */
    requireLowercase: boolean;
    /**
     * 記号を必須とするか (デフォルトは`false`)
     * @type {boolean}
     * @memberof PasswordPolicy
     */
    requireSymbols: boolean;
}

/**
 * Check if a given object implements the PasswordPolicy interface.
 */
export function instanceOfPasswordPolicy(value: object): value is PasswordPolicy {
    if ((!('minLength' in (value as Record<string, any>)) && !('min_length' in (value as Record<string, any>))) || ((value as Record<string, any>)['minLength'] === undefined && (value as Record<string, any>)['min_length'] === undefined)) return false;
    if ((!('requireUppercase' in (value as Record<string, any>)) && !('require_uppercase' in (value as Record<string, any>))) || ((value as Record<string, any>)['requireUppercase'] === undefined && (value as Record<string, any>)['require_uppercase'] === undefined)) return false;
    if ((!('requireLowercase' in (value as Record<string, any>)) && !('require_lowercase' in (value as Record<string, any>))) || ((value as Record<string, any>)['requireLowercase'] === undefined && (value as Record<string, any>)['require_lowercase'] === undefined)) return false;
    if ((!('requireSymbols' in (value as Record<string, any>)) && !('require_symbols' in (value as Record<string, any>))) || ((value as Record<string, any>)['requireSymbols'] === undefined && (value as Record<string, any>)['require_symbols'] === undefined)) return false;
    return true;
}

export function PasswordPolicyFromJSON(json: any): PasswordPolicy {
    return PasswordPolicyFromJSONTyped(json, false);
}

export function PasswordPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'minLength': json['min_length'],
        'requireUppercase': json['require_uppercase'],
        'requireLowercase': json['require_lowercase'],
        'requireSymbols': json['require_symbols'],
    };
}

export function PasswordPolicyToJSON(json: any): PasswordPolicy {
    return PasswordPolicyToJSONTyped(json, false);
}

export function PasswordPolicyToJSONTyped(value?: PasswordPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_length': value['minLength'],
        'require_uppercase': value['requireUppercase'],
        'require_lowercase': value['requireLowercase'],
        'require_symbols': value['requireSymbols'],
    };
}

