/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Principal
 */
export interface Principal {
    /**
     * プリンシパルのタイプ
     * @type {string}
     * @memberof Principal
     */
    type?: string;
    /**
     * プリンシパルのID
     * @type {number}
     * @memberof Principal
     */
    id?: number;
}

/**
 * Check if a given object implements the Principal interface.
 */
export function instanceOfPrincipal(value: object): value is Principal {
    return true;
}

export function PrincipalFromJSON(json: any): Principal {
    return PrincipalFromJSONTyped(json, false);
}

export function PrincipalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Principal {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PrincipalToJSON(json: any): Principal {
    return PrincipalToJSONTyped(json, false);
}

export function PrincipalToJSONTyped(value?: Principal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

