/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectApiKey
 */
export interface ProjectApiKey {
    /**
     * APIキーID
     * @type {number}
     * @memberof ProjectApiKey
     */
    readonly id: number;
    /**
     * プロジェクトID
     * @type {number}
     * @memberof ProjectApiKey
     */
    projectId: number;
    /**
     * APIキー名
     * @type {string}
     * @memberof ProjectApiKey
     */
    name: string;
    /**
     * APIキーの説明
     * @type {string}
     * @memberof ProjectApiKey
     */
    description: string;
    /**
     * アクセストークン
     * @type {string}
     * @memberof ProjectApiKey
     */
    accessToken: string;
    /**
     * APIキーがシングルサーバコントロールパネルで利用される場合は必須。
     * @type {string}
     * @memberof ProjectApiKey
     */
    serverResourceId?: string | null;
    /**
     * IAMのロール。
     * @type {Array<string>}
     * @memberof ProjectApiKey
     */
    iamRoles: Array<string>;
    /**
     * ゾーンを指定。APIキーがシングルサーバコントロールパネルで利用される場合は必須。
     * @type {string}
     * @memberof ProjectApiKey
     */
    zoneId?: string | null;
    /**
     * 作成日時
     * @type {string}
     * @memberof ProjectApiKey
     */
    createdAt?: string;
    /**
     * 更新日時
     * @type {string}
     * @memberof ProjectApiKey
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ProjectApiKey interface.
 */
export function instanceOfProjectApiKey(value: object): value is ProjectApiKey {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('accessToken' in (value as Record<string, any>)) && !('access_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['accessToken'] === undefined && (value as Record<string, any>)['access_token'] === undefined)) return false;
    if ((!('iamRoles' in (value as Record<string, any>)) && !('iam_roles' in (value as Record<string, any>))) || ((value as Record<string, any>)['iamRoles'] === undefined && (value as Record<string, any>)['iam_roles'] === undefined)) return false;
    return true;
}

export function ProjectApiKeyFromJSON(json: any): ProjectApiKey {
    return ProjectApiKeyFromJSONTyped(json, false);
}

export function ProjectApiKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectApiKey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'name': json['name'],
        'description': json['description'],
        'accessToken': json['access_token'],
        'serverResourceId': json['server_resource_id'] === undefined ? undefined : json['server_resource_id'] === null ? null : json['server_resource_id'],
        'iamRoles': json['iam_roles'],
        'zoneId': json['zone_id'] === undefined ? undefined : json['zone_id'] === null ? null : json['zone_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ProjectApiKeyToJSON(json: any): ProjectApiKey {
    return ProjectApiKeyToJSONTyped(json, false);
}

export function ProjectApiKeyToJSONTyped(value?: Omit<ProjectApiKey, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'name': value['name'],
        'description': value['description'],
        'access_token': value['accessToken'],
        'server_resource_id': value['serverResourceId'],
        'iam_roles': value['iamRoles'],
        'zone_id': value['zoneId'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

