/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuleResponse } from './RuleResponse';
import {
    RuleResponseFromJSON,
    RuleResponseFromJSONTyped,
    RuleResponseToJSON,
    RuleResponseToJSONTyped,
} from './RuleResponse';

/**
 * 
 * @export
 * @interface ReadOrganizationServicePolicy200Response
 */
export interface ReadOrganizationServicePolicy200Response {
    /**
     * 
     * @type {Array<RuleResponse>}
     * @memberof ReadOrganizationServicePolicy200Response
     */
    rules?: Array<RuleResponse>;
}

/**
 * Check if a given object implements the ReadOrganizationServicePolicy200Response interface.
 */
export function instanceOfReadOrganizationServicePolicy200Response(value: object): value is ReadOrganizationServicePolicy200Response {
    return true;
}

export function ReadOrganizationServicePolicy200ResponseFromJSON(json: any): ReadOrganizationServicePolicy200Response {
    return ReadOrganizationServicePolicy200ResponseFromJSONTyped(json, false);
}

export function ReadOrganizationServicePolicy200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadOrganizationServicePolicy200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'rules': json['rules'] == null ? undefined : ((json['rules'] as Array<any>).map(RuleResponseFromJSON)),
    };
}

export function ReadOrganizationServicePolicy200ResponseToJSON(json: any): ReadOrganizationServicePolicy200Response {
    return ReadOrganizationServicePolicy200ResponseToJSONTyped(json, false);
}

export function ReadOrganizationServicePolicy200ResponseToJSONTyped(value?: ReadOrganizationServicePolicy200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rules': value['rules'] == null ? undefined : ((value['rules'] as Array<any>).map(RuleResponseToJSON)),
    };
}

