/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterEmailRequest
 */
export interface RegisterEmailRequest {
    /**
     * メールアドレス
     * @type {string}
     * @memberof RegisterEmailRequest
     */
    email: string;
}

/**
 * Check if a given object implements the RegisterEmailRequest interface.
 */
export function instanceOfRegisterEmailRequest(value: object): value is RegisterEmailRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RegisterEmailRequestFromJSON(json: any): RegisterEmailRequest {
    return RegisterEmailRequestFromJSONTyped(json, false);
}

export function RegisterEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RegisterEmailRequestToJSON(json: any): RegisterEmailRequest {
    return RegisterEmailRequestToJSONTyped(json, false);
}

export function RegisterEmailRequestToJSONTyped(value?: RegisterEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

