/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuleSpec } from './RuleSpec';
import {
    RuleSpecFromJSON,
    RuleSpecFromJSONTyped,
    RuleSpecToJSON,
    RuleSpecToJSONTyped,
} from './RuleSpec';

/**
 * 
 * @export
 * @interface Rule
 */
export interface Rule {
    /**
     * ルールが有効かどうか
     * @type {boolean}
     * @memberof Rule
     */
    isActive: boolean;
    /**
     * ルールがドライランかどうか
     * @type {boolean}
     * @memberof Rule
     */
    isDryRun: boolean;
    /**
     * ルールテンプレートのコード
     * @type {string}
     * @memberof Rule
     */
    code: string;
    /**
     * 
     * @type {RuleSpec}
     * @memberof Rule
     */
    spec?: RuleSpec;
    /**
     * 
     * @type {RuleSpec}
     * @memberof Rule
     */
    dryRunSpec?: RuleSpec;
}

/**
 * Check if a given object implements the Rule interface.
 */
export function instanceOfRule(value: object): value is Rule {
    if ((!('isActive' in (value as Record<string, any>)) && !('is_active' in (value as Record<string, any>))) || ((value as Record<string, any>)['isActive'] === undefined && (value as Record<string, any>)['is_active'] === undefined)) return false;
    if ((!('isDryRun' in (value as Record<string, any>)) && !('is_dry_run' in (value as Record<string, any>))) || ((value as Record<string, any>)['isDryRun'] === undefined && (value as Record<string, any>)['is_dry_run'] === undefined)) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function RuleFromJSON(json: any): Rule {
    return RuleFromJSONTyped(json, false);
}

export function RuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rule {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['is_active'],
        'isDryRun': json['is_dry_run'],
        'code': json['code'],
        'spec': json['spec'] == null ? undefined : RuleSpecFromJSON(json['spec']),
        'dryRunSpec': json['dry_run_spec'] == null ? undefined : RuleSpecFromJSON(json['dry_run_spec']),
    };
}

export function RuleToJSON(json: any): Rule {
    return RuleToJSONTyped(json, false);
}

export function RuleToJSONTyped(value?: Rule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_active': value['isActive'],
        'is_dry_run': value['isDryRun'],
        'code': value['code'],
        'spec': RuleSpecToJSON(value['spec']),
        'dry_run_spec': RuleSpecToJSON(value['dryRunSpec']),
    };
}

