/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuleTemplate
 */
export interface RuleTemplate {
    /**
     * ルールテンプレートコード
     * @type {string}
     * @memberof RuleTemplate
     */
    code?: string;
    /**
     * ルールテンプレートの説明
     * @type {string}
     * @memberof RuleTemplate
     */
    description?: string;
    /**
     * ルールテンプレート名
     * @type {string}
     * @memberof RuleTemplate
     */
    name?: string;
    /**
     * ルールテンプレートのタイプ
     * @type {string}
     * @memberof RuleTemplate
     */
    type?: string;
    /**
     * ドライランがサポートされているかどうか
     * @type {boolean}
     * @memberof RuleTemplate
     */
    supportsDryRun?: boolean;
    /**
     * ルールテンプレートのプレフィックス
     * @type {Array<string>}
     * @memberof RuleTemplate
     */
    prefixes?: Array<string>;
}

/**
 * Check if a given object implements the RuleTemplate interface.
 */
export function instanceOfRuleTemplate(value: object): value is RuleTemplate {
    return true;
}

export function RuleTemplateFromJSON(json: any): RuleTemplate {
    return RuleTemplateFromJSONTyped(json, false);
}

export function RuleTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'supportsDryRun': json['supports_dry_run'] == null ? undefined : json['supports_dry_run'],
        'prefixes': json['prefixes'] == null ? undefined : json['prefixes'],
    };
}

export function RuleTemplateToJSON(json: any): RuleTemplate {
    return RuleTemplateToJSONTyped(json, false);
}

export function RuleTemplateToJSONTyped(value?: RuleTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'name': value['name'],
        'type': value['type'],
        'supports_dry_run': value['supportsDryRun'],
        'prefixes': value['prefixes'],
    };
}

