/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuleSpec } from './RuleSpec';
import {
    RuleSpecFromJSON,
    RuleSpecFromJSONTyped,
    RuleSpecToJSON,
    RuleSpecToJSONTyped,
} from './RuleSpec';

/**
 * 
 * @export
 * @interface RuleResponse
 */
export interface RuleResponse {
    /**
     * ルールが有効かどうか
     * @type {boolean}
     * @memberof RuleResponse
     */
    isActive?: boolean;
    /**
     * ルールがドライランかどうか
     * @type {boolean}
     * @memberof RuleResponse
     */
    isDryRun?: boolean;
    /**
     * ルールテンプレートのコード
     * @type {string}
     * @memberof RuleResponse
     */
    code?: string;
    /**
     * ルール名
     * @type {string}
     * @memberof RuleResponse
     */
    name?: string;
    /**
     * 
     * @type {RuleSpec}
     * @memberof RuleResponse
     */
    spec?: RuleSpec;
    /**
     * 
     * @type {RuleSpec}
     * @memberof RuleResponse
     */
    dryRunSpec?: RuleSpec;
}

/**
 * Check if a given object implements the RuleResponse interface.
 */
export function instanceOfRuleResponse(value: object): value is RuleResponse {
    return true;
}

export function RuleResponseFromJSON(json: any): RuleResponse {
    return RuleResponseFromJSONTyped(json, false);
}

export function RuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isDryRun': json['is_dry_run'] == null ? undefined : json['is_dry_run'],
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'spec': json['spec'] == null ? undefined : RuleSpecFromJSON(json['spec']),
        'dryRunSpec': json['dry_run_spec'] == null ? undefined : RuleSpecFromJSON(json['dry_run_spec']),
    };
}

export function RuleResponseToJSON(json: any): RuleResponse {
    return RuleResponseToJSONTyped(json, false);
}

export function RuleResponseToJSONTyped(value?: RuleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_active': value['isActive'],
        'is_dry_run': value['isDryRun'],
        'code': value['code'],
        'name': value['name'],
        'spec': RuleSpecToJSON(value['spec']),
        'dry_run_spec': RuleSpecToJSON(value['dryRunSpec']),
    };
}

