/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScimConfigurationPublic
 */
export interface ScimConfigurationPublic {
    /**
     * ユーザープロビジョニングID
     * @type {string}
     * @memberof ScimConfigurationPublic
     */
    readonly id: string;
    /**
     * ユーザープロビジョニング名
     * @type {string}
     * @memberof ScimConfigurationPublic
     */
    name: string;
    /**
     * ユーザープロビジョニングエンドポイントのベースURL（ユーザープロビジョニングIDを含む）
     * @type {string}
     * @memberof ScimConfigurationPublic
     */
    readonly baseUrl: string;
    /**
     * 作成日時
     * @type {string}
     * @memberof ScimConfigurationPublic
     */
    readonly createdAt: string;
    /**
     * 更新日時
     * @type {string}
     * @memberof ScimConfigurationPublic
     */
    readonly updatedAt: string;
}

/**
 * Check if a given object implements the ScimConfigurationPublic interface.
 */
export function instanceOfScimConfigurationPublic(value: object): value is ScimConfigurationPublic {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('baseUrl' in (value as Record<string, any>)) && !('base_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['baseUrl'] === undefined && (value as Record<string, any>)['base_url'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function ScimConfigurationPublicFromJSON(json: any): ScimConfigurationPublic {
    return ScimConfigurationPublicFromJSONTyped(json, false);
}

export function ScimConfigurationPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScimConfigurationPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'baseUrl': json['base_url'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function ScimConfigurationPublicToJSON(json: any): ScimConfigurationPublic {
    return ScimConfigurationPublicToJSONTyped(json, false);
}

export function ScimConfigurationPublicToJSONTyped(value?: Omit<ScimConfigurationPublic, 'id'|'baseUrl'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

