/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScimConfiguration
 */
export interface ScimConfiguration {
    /**
     * ユーザープロビジョニングID
     * @type {string}
     * @memberof ScimConfiguration
     */
    readonly id: string;
    /**
     * ユーザープロビジョニング名
     * @type {string}
     * @memberof ScimConfiguration
     */
    name: string;
    /**
     * ユーザープロビジョニングエンドポイントのベースURL（ユーザープロビジョニングIDを含む）
     * @type {string}
     * @memberof ScimConfiguration
     */
    readonly baseUrl: string;
    /**
     * 作成日時
     * @type {string}
     * @memberof ScimConfiguration
     */
    readonly createdAt: string;
    /**
     * 更新日時
     * @type {string}
     * @memberof ScimConfiguration
     */
    readonly updatedAt: string;
    /**
     * ユーザープロビジョニングの認証に使用するシークレットトークン
     * @type {string}
     * @memberof ScimConfiguration
     */
    readonly secretToken: string;
}

/**
 * Check if a given object implements the ScimConfiguration interface.
 */
export function instanceOfScimConfiguration(value: object): value is ScimConfiguration {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('baseUrl' in (value as Record<string, any>)) && !('base_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['baseUrl'] === undefined && (value as Record<string, any>)['base_url'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if ((!('secretToken' in (value as Record<string, any>)) && !('secret_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['secretToken'] === undefined && (value as Record<string, any>)['secret_token'] === undefined)) return false;
    return true;
}

export function ScimConfigurationFromJSON(json: any): ScimConfiguration {
    return ScimConfigurationFromJSONTyped(json, false);
}

export function ScimConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScimConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'baseUrl': json['base_url'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'secretToken': json['secret_token'],
    };
}

export function ScimConfigurationToJSON(json: any): ScimConfiguration {
    return ScimConfigurationToJSONTyped(json, false);
}

export function ScimConfigurationToJSONTyped(value?: Omit<ScimConfiguration, 'id'|'baseUrl'|'createdAt'|'updatedAt'|'secretToken'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

