/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServicePrincipal
 */
export interface ServicePrincipal {
    /**
     * サービスプリンシパルID
     * @type {number}
     * @memberof ServicePrincipal
     */
    readonly id: number;
    /**
     * プロジェクトID
     * @type {number}
     * @memberof ServicePrincipal
     */
    projectId: number;
    /**
     * サービスプリンシパル名
     * @type {string}
     * @memberof ServicePrincipal
     */
    name: string;
    /**
     * サービスプリンシパルの説明
     * @type {string}
     * @memberof ServicePrincipal
     */
    description: string;
    /**
     * 作成日時
     * @type {string}
     * @memberof ServicePrincipal
     */
    createdAt?: string;
    /**
     * 更新日時
     * @type {string}
     * @memberof ServicePrincipal
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ServicePrincipal interface.
 */
export function instanceOfServicePrincipal(value: object): value is ServicePrincipal {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ServicePrincipalFromJSON(json: any): ServicePrincipal {
    return ServicePrincipalFromJSONTyped(json, false);
}

export function ServicePrincipalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicePrincipal {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'name': json['name'],
        'description': json['description'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ServicePrincipalToJSON(json: any): ServicePrincipal {
    return ServicePrincipalToJSONTyped(json, false);
}

export function ServicePrincipalToJSONTyped(value?: Omit<ServicePrincipal, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'name': value['name'],
        'description': value['description'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

