/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServicePrincipalKey
 */
export interface ServicePrincipalKey {
    /**
     * サービスプリンシパルキーID
     * @type {string}
     * @memberof ServicePrincipalKey
     */
    readonly id: string;
    /**
     * 公開鍵のkid
     * @type {string}
     * @memberof ServicePrincipalKey
     */
    readonly kid: string;
    /**
     * サービスプリンシパルキーの状態
     * * enabled 有効
     * * disabled 無効
     * 
     * @type {ServicePrincipalKeyStatusEnum}
     * @memberof ServicePrincipalKey
     */
    status: ServicePrincipalKeyStatusEnum;
    /**
     * 鍵の生成元
     * 
     * @type {ServicePrincipalKeyKeyOriginEnum}
     * @memberof ServicePrincipalKey
     */
    readonly keyOrigin: ServicePrincipalKeyKeyOriginEnum;
    /**
     * PEM形式の公開鍵文字列
     * RSA鍵のみをサポート
     * 鍵長は2048ビット以上かつ4096ビット以下をサポート
     * 
     * @type {string}
     * @memberof ServicePrincipalKey
     */
    publicKey: string;
    /**
     * 作成日時
     * @type {string}
     * @memberof ServicePrincipalKey
     */
    createdAt: string;
    /**
     * 有効期限
     * @type {string}
     * @memberof ServicePrincipalKey
     */
    keyExpiresAt?: string | null;
}


/**
 * @export
 */
export const ServicePrincipalKeyStatusEnum = {
    Enabled: 'enabled',
    Disabled: 'disabled'
} as const;
export type ServicePrincipalKeyStatusEnum = typeof ServicePrincipalKeyStatusEnum[keyof typeof ServicePrincipalKeyStatusEnum];

/**
 * @export
 */
export const ServicePrincipalKeyKeyOriginEnum = {
    User: 'user'
} as const;
export type ServicePrincipalKeyKeyOriginEnum = typeof ServicePrincipalKeyKeyOriginEnum[keyof typeof ServicePrincipalKeyKeyOriginEnum];


/**
 * Check if a given object implements the ServicePrincipalKey interface.
 */
export function instanceOfServicePrincipalKey(value: object): value is ServicePrincipalKey {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kid' in value) || value['kid'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('keyOrigin' in (value as Record<string, any>)) && !('key_origin' in (value as Record<string, any>))) || ((value as Record<string, any>)['keyOrigin'] === undefined && (value as Record<string, any>)['key_origin'] === undefined)) return false;
    if ((value as Record<string, any>)['keyOrigin'] !== 'user' && (value as Record<string, any>)['key_origin'] !== 'user') return false;
    
    if ((!('publicKey' in (value as Record<string, any>)) && !('public_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['publicKey'] === undefined && (value as Record<string, any>)['public_key'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function ServicePrincipalKeyFromJSON(json: any): ServicePrincipalKey {
    return ServicePrincipalKeyFromJSONTyped(json, false);
}

export function ServicePrincipalKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicePrincipalKey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kid': json['kid'],
        'status': json['status'],
        'keyOrigin': json['key_origin'],
        'publicKey': json['public_key'],
        'createdAt': json['created_at'],
        'keyExpiresAt': json['key_expires_at'] === undefined ? undefined : json['key_expires_at'] === null ? null : json['key_expires_at'],
    };
}

export function ServicePrincipalKeyToJSON(json: any): ServicePrincipalKey {
    return ServicePrincipalKeyToJSONTyped(json, false);
}

export function ServicePrincipalKeyToJSONTyped(value?: Omit<ServicePrincipalKey, 'id'|'kid'|'keyOrigin'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'public_key': value['publicKey'],
        'created_at': value['createdAt'],
        'key_expires_at': value['keyExpiresAt'],
    };
}

