/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Rule } from './Rule';
import {
    RuleFromJSON,
    RuleFromJSONTyped,
    RuleToJSON,
    RuleToJSONTyped,
} from './Rule';

/**
 * 
 * @export
 * @interface UpdateOrganizationServicePolicyRequest
 */
export interface UpdateOrganizationServicePolicyRequest {
    /**
     * 
     * @type {Array<Rule>}
     * @memberof UpdateOrganizationServicePolicyRequest
     */
    rules: Array<Rule>;
}

/**
 * Check if a given object implements the UpdateOrganizationServicePolicyRequest interface.
 */
export function instanceOfUpdateOrganizationServicePolicyRequest(value: object): value is UpdateOrganizationServicePolicyRequest {
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function UpdateOrganizationServicePolicyRequestFromJSON(json: any): UpdateOrganizationServicePolicyRequest {
    return UpdateOrganizationServicePolicyRequestFromJSONTyped(json, false);
}

export function UpdateOrganizationServicePolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationServicePolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rules': ((json['rules'] as Array<any>).map(RuleFromJSON)),
    };
}

export function UpdateOrganizationServicePolicyRequestToJSON(json: any): UpdateOrganizationServicePolicyRequest {
    return UpdateOrganizationServicePolicyRequestToJSONTyped(json, false);
}

export function UpdateOrganizationServicePolicyRequestToJSONTyped(value?: UpdateOrganizationServicePolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rules': ((value['rules'] as Array<any>).map(RuleToJSON)),
    };
}

