/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFolderRequest
 */
export interface UpdateFolderRequest {
    /**
     * フォルダ名
     * @type {string}
     * @memberof UpdateFolderRequest
     */
    name: string;
    /**
     * フォルダの説明
     * @type {string}
     * @memberof UpdateFolderRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateFolderRequest interface.
 */
export function instanceOfUpdateFolderRequest(value: object): value is UpdateFolderRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateFolderRequestFromJSON(json: any): UpdateFolderRequest {
    return UpdateFolderRequestFromJSONTyped(json, false);
}

export function UpdateFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFolderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateFolderRequestToJSON(json: any): UpdateFolderRequest {
    return UpdateFolderRequestToJSONTyped(json, false);
}

export function UpdateFolderRequestToJSONTyped(value?: UpdateFolderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

