/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateMembershipsRequestCompatUsersInner } from './UpdateMembershipsRequestCompatUsersInner';
import {
    UpdateMembershipsRequestCompatUsersInnerFromJSON,
    UpdateMembershipsRequestCompatUsersInnerFromJSONTyped,
    UpdateMembershipsRequestCompatUsersInnerToJSON,
    UpdateMembershipsRequestCompatUsersInnerToJSONTyped,
} from './UpdateMembershipsRequestCompatUsersInner';

/**
 * 
 * @export
 * @interface UpdateMembershipsRequest
 */
export interface UpdateMembershipsRequest {
    /**
     * 
     * @type {Array<UpdateMembershipsRequestCompatUsersInner>}
     * @memberof UpdateMembershipsRequest
     */
    compatUsers: Array<UpdateMembershipsRequestCompatUsersInner>;
}

/**
 * Check if a given object implements the UpdateMembershipsRequest interface.
 */
export function instanceOfUpdateMembershipsRequest(value: object): value is UpdateMembershipsRequest {
    if ((!('compatUsers' in (value as Record<string, any>)) && !('compat_users' in (value as Record<string, any>))) || ((value as Record<string, any>)['compatUsers'] === undefined && (value as Record<string, any>)['compat_users'] === undefined)) return false;
    return true;
}

export function UpdateMembershipsRequestFromJSON(json: any): UpdateMembershipsRequest {
    return UpdateMembershipsRequestFromJSONTyped(json, false);
}

export function UpdateMembershipsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMembershipsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'compatUsers': ((json['compat_users'] as Array<any>).map(UpdateMembershipsRequestCompatUsersInnerFromJSON)),
    };
}

export function UpdateMembershipsRequestToJSON(json: any): UpdateMembershipsRequest {
    return UpdateMembershipsRequestToJSONTyped(json, false);
}

export function UpdateMembershipsRequestToJSONTyped(value?: UpdateMembershipsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'compat_users': ((value['compatUsers'] as Array<any>).map(UpdateMembershipsRequestCompatUsersInnerToJSON)),
    };
}

