/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOtp
 */
export interface UserOtp {
    /**
     * OTP設定状態
     * * deactivated OTP無効状態
     * * activated OTP有効状態
     * * activating OTP有効化中
     * 
     * @type {UserOtpStatusEnum}
     * @memberof UserOtp
     */
    status: UserOtpStatusEnum;
    /**
     * リカバリーコード作成済みかどうか
     * @type {boolean}
     * @memberof UserOtp
     */
    hasRecoveryCode: boolean;
}


/**
 * @export
 */
export const UserOtpStatusEnum = {
    Deactivated: 'deactivated',
    Activated: 'activated',
    Activating: 'activating'
} as const;
export type UserOtpStatusEnum = typeof UserOtpStatusEnum[keyof typeof UserOtpStatusEnum];


/**
 * Check if a given object implements the UserOtp interface.
 */
export function instanceOfUserOtp(value: object): value is UserOtp {
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('hasRecoveryCode' in (value as Record<string, any>)) && !('has_recovery_code' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasRecoveryCode'] === undefined && (value as Record<string, any>)['has_recovery_code'] === undefined)) return false;
    return true;
}

export function UserOtpFromJSON(json: any): UserOtp {
    return UserOtpFromJSONTyped(json, false);
}

export function UserOtpFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOtp {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'hasRecoveryCode': json['has_recovery_code'],
    };
}

export function UserOtpToJSON(json: any): UserOtp {
    return UserOtpToJSONTyped(json, false);
}

export function UserOtpToJSONTyped(value?: UserOtp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'has_recovery_code': value['hasRecoveryCode'],
    };
}

