/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMember } from './UserMember';
import {
    UserMemberFromJSON,
    UserMemberFromJSONTyped,
    UserMemberToJSON,
    UserMemberToJSONTyped,
} from './UserMember';
import type { UserOtp } from './UserOtp';
import {
    UserOtpFromJSON,
    UserOtpFromJSONTyped,
    UserOtpToJSON,
    UserOtpToJSONTyped,
} from './UserOtp';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * ユーザID
     * @type {number}
     * @memberof User
     */
    readonly id: number;
    /**
     * 
     * @type {UserMember}
     * @memberof User
     */
    member: UserMember;
    /**
     * ユーザ名
     * @type {string}
     * @memberof User
     */
    name: string;
    /**
     * ユーザコード
     * @type {string}
     * @memberof User
     */
    readonly code: string;
    /**
     * ユーザのステータス
     * @type {UserStatusEnum}
     * @memberof User
     */
    readonly status: UserStatusEnum;
    /**
     * ユーザの説明
     * @type {string}
     * @memberof User
     */
    description: string;
    /**
     * 
     * @type {UserOtp}
     * @memberof User
     */
    otp: UserOtp;
    /**
     * セキュリティキーを登録済みかどうか
     * @type {boolean}
     * @memberof User
     */
    isSecurityKeyRegistered: boolean;
    /**
     * メールアドレス
     * @type {string}
     * @memberof User
     */
    readonly email: string;
    /**
     * パスワードレス認証かどうか
     * @type {boolean}
     * @memberof User
     */
    readonly isPasswordless: boolean;
    /**
     * 作成日時
     * @type {string}
     * @memberof User
     */
    readonly createdAt: string;
    /**
     * 更新日時
     * @type {string}
     * @memberof User
     */
    readonly updatedAt: string;
}


/**
 * @export
 */
export const UserStatusEnum = {
    Available: 'available'
} as const;
export type UserStatusEnum = typeof UserStatusEnum[keyof typeof UserStatusEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('member' in value) || value['member'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'available') return false;
    
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('otp' in value) || value['otp'] === undefined) return false;
    if ((!('isSecurityKeyRegistered' in (value as Record<string, any>)) && !('is_security_key_registered' in (value as Record<string, any>))) || ((value as Record<string, any>)['isSecurityKeyRegistered'] === undefined && (value as Record<string, any>)['is_security_key_registered'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('isPasswordless' in (value as Record<string, any>)) && !('is_passwordless' in (value as Record<string, any>))) || ((value as Record<string, any>)['isPasswordless'] === undefined && (value as Record<string, any>)['is_passwordless'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'member': UserMemberFromJSON(json['member']),
        'name': json['name'],
        'code': json['code'],
        'status': json['status'],
        'description': json['description'],
        'otp': UserOtpFromJSON(json['otp']),
        'isSecurityKeyRegistered': json['is_security_key_registered'],
        'email': json['email'],
        'isPasswordless': json['is_passwordless'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: Omit<User, 'id'|'code'|'status'|'email'|'isPasswordless'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': UserMemberToJSON(value['member']),
        'name': value['name'],
        'description': value['description'],
        'otp': UserOtpToJSON(value['otp']),
        'is_security_key_registered': value['isSecurityKeyRegistered'],
    };
}

