/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonServiceItemDestinationSettings
 */
export interface CommonServiceItemDestinationSettings {
    /**
     * 
     * @type {CommonServiceItemDestinationSettingsTypeEnum}
     * @memberof CommonServiceItemDestinationSettings
     */
    type: CommonServiceItemDestinationSettingsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItemDestinationSettings
     */
    value: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommonServiceItemDestinationSettings
     */
    disabled?: boolean;
}


/**
 * @export
 */
export const CommonServiceItemDestinationSettingsTypeEnum = {
    Email: 'email',
    Webhook: 'webhook'
} as const;
export type CommonServiceItemDestinationSettingsTypeEnum = typeof CommonServiceItemDestinationSettingsTypeEnum[keyof typeof CommonServiceItemDestinationSettingsTypeEnum];


/**
 * Check if a given object implements the CommonServiceItemDestinationSettings interface.
 */
export function instanceOfCommonServiceItemDestinationSettings(value: object): value is CommonServiceItemDestinationSettings {
    if ((!('type' in (value as Record<string, any>)) && !('Type' in (value as Record<string, any>))) || ((value as Record<string, any>)['type'] === undefined && (value as Record<string, any>)['Type'] === undefined)) return false;
    if ((!('value' in (value as Record<string, any>)) && !('Value' in (value as Record<string, any>))) || ((value as Record<string, any>)['value'] === undefined && (value as Record<string, any>)['Value'] === undefined)) return false;
    return true;
}

export function CommonServiceItemDestinationSettingsFromJSON(json: any): CommonServiceItemDestinationSettings {
    return CommonServiceItemDestinationSettingsFromJSONTyped(json, false);
}

export function CommonServiceItemDestinationSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonServiceItemDestinationSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['Type'],
        'value': json['Value'],
        'disabled': json['Disabled'] == null ? undefined : json['Disabled'],
    };
}

export function CommonServiceItemDestinationSettingsToJSON(json: any): CommonServiceItemDestinationSettings {
    return CommonServiceItemDestinationSettingsToJSONTyped(json, false);
}

export function CommonServiceItemDestinationSettingsToJSONTyped(value?: CommonServiceItemDestinationSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Type': value['type'],
        'Value': value['value'],
        'Disabled': value['disabled'],
    };
}

