/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonServiceItemRoutingSettingsMatchLabelsInner } from './CommonServiceItemRoutingSettingsMatchLabelsInner';
import {
    CommonServiceItemRoutingSettingsMatchLabelsInnerFromJSON,
    CommonServiceItemRoutingSettingsMatchLabelsInnerFromJSONTyped,
    CommonServiceItemRoutingSettingsMatchLabelsInnerToJSON,
    CommonServiceItemRoutingSettingsMatchLabelsInnerToJSONTyped,
} from './CommonServiceItemRoutingSettingsMatchLabelsInner';

/**
 * 
 * @export
 * @interface CommonServiceItemRoutingSettings
 */
export interface CommonServiceItemRoutingSettings {
    /**
     * 
     * @type {Array<CommonServiceItemRoutingSettingsMatchLabelsInner>}
     * @memberof CommonServiceItemRoutingSettings
     */
    matchLabels: Array<CommonServiceItemRoutingSettingsMatchLabelsInner>;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItemRoutingSettings
     */
    sourceID: string;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItemRoutingSettings
     */
    targetGroupID: string;
    /**
     * 
     * @type {number}
     * @memberof CommonServiceItemRoutingSettings
     */
    readonly priorityRank: number;
}

/**
 * Check if a given object implements the CommonServiceItemRoutingSettings interface.
 */
export function instanceOfCommonServiceItemRoutingSettings(value: object): value is CommonServiceItemRoutingSettings {
    if ((!('matchLabels' in (value as Record<string, any>)) && !('MatchLabels' in (value as Record<string, any>))) || ((value as Record<string, any>)['matchLabels'] === undefined && (value as Record<string, any>)['MatchLabels'] === undefined)) return false;
    if ((!('sourceID' in (value as Record<string, any>)) && !('SourceID' in (value as Record<string, any>))) || ((value as Record<string, any>)['sourceID'] === undefined && (value as Record<string, any>)['SourceID'] === undefined)) return false;
    if ((!('targetGroupID' in (value as Record<string, any>)) && !('TargetGroupID' in (value as Record<string, any>))) || ((value as Record<string, any>)['targetGroupID'] === undefined && (value as Record<string, any>)['TargetGroupID'] === undefined)) return false;
    if ((!('priorityRank' in (value as Record<string, any>)) && !('PriorityRank' in (value as Record<string, any>))) || ((value as Record<string, any>)['priorityRank'] === undefined && (value as Record<string, any>)['PriorityRank'] === undefined)) return false;
    return true;
}

export function CommonServiceItemRoutingSettingsFromJSON(json: any): CommonServiceItemRoutingSettings {
    return CommonServiceItemRoutingSettingsFromJSONTyped(json, false);
}

export function CommonServiceItemRoutingSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonServiceItemRoutingSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'matchLabels': ((json['MatchLabels'] as Array<any>).map(CommonServiceItemRoutingSettingsMatchLabelsInnerFromJSON)),
        'sourceID': json['SourceID'],
        'targetGroupID': json['TargetGroupID'],
        'priorityRank': json['PriorityRank'],
    };
}

export function CommonServiceItemRoutingSettingsToJSON(json: any): CommonServiceItemRoutingSettings {
    return CommonServiceItemRoutingSettingsToJSONTyped(json, false);
}

export function CommonServiceItemRoutingSettingsToJSONTyped(value?: Omit<CommonServiceItemRoutingSettings, 'priorityRank'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MatchLabels': ((value['matchLabels'] as Array<any>).map(CommonServiceItemRoutingSettingsMatchLabelsInnerToJSON)),
        'SourceID': value['sourceID'],
        'TargetGroupID': value['targetGroupID'],
    };
}

