/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonServiceItemSettings } from './CommonServiceItemSettings';
import {
    CommonServiceItemSettingsFromJSON,
    CommonServiceItemSettingsFromJSONTyped,
    CommonServiceItemSettingsToJSON,
    CommonServiceItemSettingsToJSONTyped,
} from './CommonServiceItemSettings';
import type { CommonServiceItemProvider } from './CommonServiceItemProvider';
import {
    CommonServiceItemProviderFromJSON,
    CommonServiceItemProviderFromJSONTyped,
    CommonServiceItemProviderToJSON,
    CommonServiceItemProviderToJSONTyped,
} from './CommonServiceItemProvider';
import type { CommonServiceItemIcon } from './CommonServiceItemIcon';
import {
    CommonServiceItemIconFromJSON,
    CommonServiceItemIconFromJSONTyped,
    CommonServiceItemIconToJSON,
    CommonServiceItemIconToJSONTyped,
} from './CommonServiceItemIcon';

/**
 * 
 * @export
 * @interface CommonServiceItem
 */
export interface CommonServiceItem {
    /**
     * 
     * @type {number}
     * @memberof CommonServiceItem
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItem
     */
    iD: string;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItem
     */
    description: string;
    /**
     * 
     * @type {CommonServiceItemSettings}
     * @memberof CommonServiceItem
     */
    settings: CommonServiceItemSettings;
    /**
     * 
     * @type {Date}
     * @memberof CommonServiceItem
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommonServiceItem
     */
    modifiedAt: Date;
    /**
     * 
     * @type {CommonServiceItemProvider}
     * @memberof CommonServiceItem
     */
    provider: CommonServiceItemProvider;
    /**
     * 
     * @type {CommonServiceItemIcon}
     * @memberof CommonServiceItem
     */
    icon: CommonServiceItemIcon | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonServiceItem
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the CommonServiceItem interface.
 */
export function instanceOfCommonServiceItem(value: object): value is CommonServiceItem {
    if ((!('iD' in (value as Record<string, any>)) && !('ID' in (value as Record<string, any>))) || ((value as Record<string, any>)['iD'] === undefined && (value as Record<string, any>)['ID'] === undefined)) return false;
    if ((!('name' in (value as Record<string, any>)) && !('Name' in (value as Record<string, any>))) || ((value as Record<string, any>)['name'] === undefined && (value as Record<string, any>)['Name'] === undefined)) return false;
    if ((!('description' in (value as Record<string, any>)) && !('Description' in (value as Record<string, any>))) || ((value as Record<string, any>)['description'] === undefined && (value as Record<string, any>)['Description'] === undefined)) return false;
    if ((!('settings' in (value as Record<string, any>)) && !('Settings' in (value as Record<string, any>))) || ((value as Record<string, any>)['settings'] === undefined && (value as Record<string, any>)['Settings'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('CreatedAt' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['CreatedAt'] === undefined)) return false;
    if ((!('modifiedAt' in (value as Record<string, any>)) && !('ModifiedAt' in (value as Record<string, any>))) || ((value as Record<string, any>)['modifiedAt'] === undefined && (value as Record<string, any>)['ModifiedAt'] === undefined)) return false;
    if ((!('provider' in (value as Record<string, any>)) && !('Provider' in (value as Record<string, any>))) || ((value as Record<string, any>)['provider'] === undefined && (value as Record<string, any>)['Provider'] === undefined)) return false;
    if ((!('icon' in (value as Record<string, any>)) && !('Icon' in (value as Record<string, any>))) || ((value as Record<string, any>)['icon'] === undefined && (value as Record<string, any>)['Icon'] === undefined)) return false;
    if ((!('tags' in (value as Record<string, any>)) && !('Tags' in (value as Record<string, any>))) || ((value as Record<string, any>)['tags'] === undefined && (value as Record<string, any>)['Tags'] === undefined)) return false;
    return true;
}

export function CommonServiceItemFromJSON(json: any): CommonServiceItem {
    return CommonServiceItemFromJSONTyped(json, false);
}

export function CommonServiceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonServiceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['Index'] == null ? undefined : json['Index'],
        'iD': json['ID'],
        'name': json['Name'],
        'description': json['Description'],
        'settings': CommonServiceItemSettingsFromJSON(json['Settings']),
        'createdAt': (new Date(json['CreatedAt'])),
        'modifiedAt': (new Date(json['ModifiedAt'])),
        'provider': CommonServiceItemProviderFromJSON(json['Provider']),
        'icon': CommonServiceItemIconFromJSON(json['Icon']),
        'tags': json['Tags'],
    };
}

export function CommonServiceItemToJSON(json: any): CommonServiceItem {
    return CommonServiceItemToJSONTyped(json, false);
}

export function CommonServiceItemToJSONTyped(value?: CommonServiceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Index': value['index'],
        'ID': value['iD'],
        'Name': value['name'],
        'Description': value['description'],
        'Settings': CommonServiceItemSettingsToJSON(value['settings']),
        'CreatedAt': value['createdAt'].toISOString(),
        'ModifiedAt': value['modifiedAt'].toISOString(),
        'Provider': CommonServiceItemProviderToJSON(value['provider']),
        'Icon': CommonServiceItemIconToJSON(value['icon']),
        'Tags': value['tags'],
    };
}

