/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonServiceItemIcon
 */
export interface CommonServiceItemIcon {
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItemIcon
     */
    iD: string;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItemIcon
     */
    uRL?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItemIcon
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonServiceItemIcon
     */
    scope?: string;
}

/**
 * Check if a given object implements the CommonServiceItemIcon interface.
 */
export function instanceOfCommonServiceItemIcon(value: object): value is CommonServiceItemIcon {
    if ((!('iD' in (value as Record<string, any>)) && !('ID' in (value as Record<string, any>))) || ((value as Record<string, any>)['iD'] === undefined && (value as Record<string, any>)['ID'] === undefined)) return false;
    return true;
}

export function CommonServiceItemIconFromJSON(json: any): CommonServiceItemIcon {
    return CommonServiceItemIconFromJSONTyped(json, false);
}

export function CommonServiceItemIconFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonServiceItemIcon {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'uRL': json['URL'] == null ? undefined : json['URL'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'scope': json['Scope'] == null ? undefined : json['Scope'],
    };
}

export function CommonServiceItemIconToJSON(json: any): CommonServiceItemIcon {
    return CommonServiceItemIconToJSONTyped(json, false);
}

export function CommonServiceItemIconToJSONTyped(value?: CommonServiceItemIcon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
        'URL': value['uRL'],
        'Name': value['name'],
        'Scope': value['scope'],
    };
}

