/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonServiceItem } from './CommonServiceItem';
import {
    CommonServiceItemFromJSON,
    CommonServiceItemFromJSONTyped,
    CommonServiceItemToJSON,
    CommonServiceItemToJSONTyped,
} from './CommonServiceItem';

/**
 * 
 * @export
 * @interface CreateCommonServiceItem201Response
 */
export interface CreateCommonServiceItem201Response {
    /**
     * 
     * @type {CommonServiceItem}
     * @memberof CreateCommonServiceItem201Response
     */
    commonServiceItem: CommonServiceItem;
}

/**
 * Check if a given object implements the CreateCommonServiceItem201Response interface.
 */
export function instanceOfCreateCommonServiceItem201Response(value: object): value is CreateCommonServiceItem201Response {
    if ((!('commonServiceItem' in (value as Record<string, any>)) && !('CommonServiceItem' in (value as Record<string, any>))) || ((value as Record<string, any>)['commonServiceItem'] === undefined && (value as Record<string, any>)['CommonServiceItem'] === undefined)) return false;
    return true;
}

export function CreateCommonServiceItem201ResponseFromJSON(json: any): CreateCommonServiceItem201Response {
    return CreateCommonServiceItem201ResponseFromJSONTyped(json, false);
}

export function CreateCommonServiceItem201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommonServiceItem201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'commonServiceItem': CommonServiceItemFromJSON(json['CommonServiceItem']),
    };
}

export function CreateCommonServiceItem201ResponseToJSON(json: any): CreateCommonServiceItem201Response {
    return CreateCommonServiceItem201ResponseToJSONTyped(json, false);
}

export function CreateCommonServiceItem201ResponseToJSONTyped(value?: CreateCommonServiceItem201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CommonServiceItem': CommonServiceItemToJSON(value['commonServiceItem']),
    };
}

