/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonServiceItem } from './CommonServiceItem';
import {
    CommonServiceItemFromJSON,
    CommonServiceItemFromJSONTyped,
    CommonServiceItemToJSON,
    CommonServiceItemToJSONTyped,
} from './CommonServiceItem';

/**
 * 
 * @export
 * @interface ListCommonServiceItemsResponse
 */
export interface ListCommonServiceItemsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListCommonServiceItemsResponse
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof ListCommonServiceItemsResponse
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof ListCommonServiceItemsResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<CommonServiceItem>}
     * @memberof ListCommonServiceItemsResponse
     */
    commonServiceItems: Array<CommonServiceItem>;
}

/**
 * Check if a given object implements the ListCommonServiceItemsResponse interface.
 */
export function instanceOfListCommonServiceItemsResponse(value: object): value is ListCommonServiceItemsResponse {
    if ((!('commonServiceItems' in (value as Record<string, any>)) && !('CommonServiceItems' in (value as Record<string, any>))) || ((value as Record<string, any>)['commonServiceItems'] === undefined && (value as Record<string, any>)['CommonServiceItems'] === undefined)) return false;
    return true;
}

export function ListCommonServiceItemsResponseFromJSON(json: any): ListCommonServiceItemsResponse {
    return ListCommonServiceItemsResponseFromJSONTyped(json, false);
}

export function ListCommonServiceItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCommonServiceItemsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['From'] == null ? undefined : json['From'],
        'count': json['Count'] == null ? undefined : json['Count'],
        'total': json['Total'] == null ? undefined : json['Total'],
        'commonServiceItems': ((json['CommonServiceItems'] as Array<any>).map(CommonServiceItemFromJSON)),
    };
}

export function ListCommonServiceItemsResponseToJSON(json: any): ListCommonServiceItemsResponse {
    return ListCommonServiceItemsResponseToJSONTyped(json, false);
}

export function ListCommonServiceItemsResponseToJSONTyped(value?: ListCommonServiceItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'From': value['from'],
        'Count': value['count'],
        'Total': value['total'],
        'CommonServiceItems': ((value['commonServiceItems'] as Array<any>).map(CommonServiceItemToJSON)),
    };
}

