/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNotificationSourcesResponseSourcesInner
 */
export interface ListNotificationSourcesResponseSourcesInner {
    /**
     * 
     * @type {string}
     * @memberof ListNotificationSourcesResponseSourcesInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListNotificationSourcesResponseSourcesInner
     */
    name: string;
}

/**
 * Check if a given object implements the ListNotificationSourcesResponseSourcesInner interface.
 */
export function instanceOfListNotificationSourcesResponseSourcesInner(value: object): value is ListNotificationSourcesResponseSourcesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ListNotificationSourcesResponseSourcesInnerFromJSON(json: any): ListNotificationSourcesResponseSourcesInner {
    return ListNotificationSourcesResponseSourcesInnerFromJSONTyped(json, false);
}

export function ListNotificationSourcesResponseSourcesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNotificationSourcesResponseSourcesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ListNotificationSourcesResponseSourcesInnerToJSON(json: any): ListNotificationSourcesResponseSourcesInner {
    return ListNotificationSourcesResponseSourcesInnerToJSONTyped(json, false);
}

export function ListNotificationSourcesResponseSourcesInnerToJSONTyped(value?: ListNotificationSourcesResponseSourcesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

