/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {boolean}
     * @memberof ModelError
     */
    isFatal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    serial?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    errorMsg?: string;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'isFatal': json['is_fatal'] == null ? undefined : json['is_fatal'],
        'serial': json['serial'] == null ? undefined : json['serial'],
        'status': json['status'] == null ? undefined : json['status'],
        'errorCode': json['error_code'] == null ? undefined : json['error_code'],
        'errorMsg': json['error_msg'] == null ? undefined : json['error_msg'],
    };
}

export function ModelErrorToJSON(json: any): ModelError {
    return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(value?: ModelError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_fatal': value['isFatal'],
        'serial': value['serial'],
        'status': value['status'],
        'error_code': value['errorCode'],
        'error_msg': value['errorMsg'],
    };
}

