/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonServiceItemSettings } from './CommonServiceItemSettings';
import {
    CommonServiceItemSettingsFromJSON,
    CommonServiceItemSettingsFromJSONTyped,
    CommonServiceItemSettingsToJSON,
    CommonServiceItemSettingsToJSONTyped,
} from './CommonServiceItemSettings';
import type { PostCommonServiceItemRequestCommonServiceItemProvider } from './PostCommonServiceItemRequestCommonServiceItemProvider';
import {
    PostCommonServiceItemRequestCommonServiceItemProviderFromJSON,
    PostCommonServiceItemRequestCommonServiceItemProviderFromJSONTyped,
    PostCommonServiceItemRequestCommonServiceItemProviderToJSON,
    PostCommonServiceItemRequestCommonServiceItemProviderToJSONTyped,
} from './PostCommonServiceItemRequestCommonServiceItemProvider';
import type { CommonServiceItemIcon } from './CommonServiceItemIcon';
import {
    CommonServiceItemIconFromJSON,
    CommonServiceItemIconFromJSONTyped,
    CommonServiceItemIconToJSON,
    CommonServiceItemIconToJSONTyped,
} from './CommonServiceItemIcon';

/**
 * 
 * @export
 * @interface PostCommonServiceItemRequestCommonServiceItem
 */
export interface PostCommonServiceItemRequestCommonServiceItem {
    /**
     * 
     * @type {string}
     * @memberof PostCommonServiceItemRequestCommonServiceItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PostCommonServiceItemRequestCommonServiceItem
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PostCommonServiceItemRequestCommonServiceItem
     */
    tags: Array<string>;
    /**
     * 
     * @type {CommonServiceItemIcon}
     * @memberof PostCommonServiceItemRequestCommonServiceItem
     */
    icon: CommonServiceItemIcon | null;
    /**
     * 
     * @type {PostCommonServiceItemRequestCommonServiceItemProvider}
     * @memberof PostCommonServiceItemRequestCommonServiceItem
     */
    provider: PostCommonServiceItemRequestCommonServiceItemProvider;
    /**
     * 
     * @type {CommonServiceItemSettings}
     * @memberof PostCommonServiceItemRequestCommonServiceItem
     */
    settings: CommonServiceItemSettings;
    /**
     * 
     * @type {PostCommonServiceItemRequestCommonServiceItemServiceClassEnum}
     * @memberof PostCommonServiceItemRequestCommonServiceItem
     */
    serviceClass: PostCommonServiceItemRequestCommonServiceItemServiceClassEnum;
}


/**
 * @export
 */
export const PostCommonServiceItemRequestCommonServiceItemServiceClassEnum = {
    CloudSaknoticedestination2: 'cloud/saknoticedestination/2',
    CloudSaknoticegroup2: 'cloud/saknoticegroup/2',
    CloudSaknoticerouting2: 'cloud/saknoticerouting/2'
} as const;
export type PostCommonServiceItemRequestCommonServiceItemServiceClassEnum = typeof PostCommonServiceItemRequestCommonServiceItemServiceClassEnum[keyof typeof PostCommonServiceItemRequestCommonServiceItemServiceClassEnum];


/**
 * Check if a given object implements the PostCommonServiceItemRequestCommonServiceItem interface.
 */
export function instanceOfPostCommonServiceItemRequestCommonServiceItem(value: object): value is PostCommonServiceItemRequestCommonServiceItem {
    if ((!('name' in (value as Record<string, any>)) && !('Name' in (value as Record<string, any>))) || ((value as Record<string, any>)['name'] === undefined && (value as Record<string, any>)['Name'] === undefined)) return false;
    if ((!('description' in (value as Record<string, any>)) && !('Description' in (value as Record<string, any>))) || ((value as Record<string, any>)['description'] === undefined && (value as Record<string, any>)['Description'] === undefined)) return false;
    if ((!('tags' in (value as Record<string, any>)) && !('Tags' in (value as Record<string, any>))) || ((value as Record<string, any>)['tags'] === undefined && (value as Record<string, any>)['Tags'] === undefined)) return false;
    if ((!('icon' in (value as Record<string, any>)) && !('Icon' in (value as Record<string, any>))) || ((value as Record<string, any>)['icon'] === undefined && (value as Record<string, any>)['Icon'] === undefined)) return false;
    if ((!('provider' in (value as Record<string, any>)) && !('Provider' in (value as Record<string, any>))) || ((value as Record<string, any>)['provider'] === undefined && (value as Record<string, any>)['Provider'] === undefined)) return false;
    if ((!('settings' in (value as Record<string, any>)) && !('Settings' in (value as Record<string, any>))) || ((value as Record<string, any>)['settings'] === undefined && (value as Record<string, any>)['Settings'] === undefined)) return false;
    if ((!('serviceClass' in (value as Record<string, any>)) && !('ServiceClass' in (value as Record<string, any>))) || ((value as Record<string, any>)['serviceClass'] === undefined && (value as Record<string, any>)['ServiceClass'] === undefined)) return false;
    return true;
}

export function PostCommonServiceItemRequestCommonServiceItemFromJSON(json: any): PostCommonServiceItemRequestCommonServiceItem {
    return PostCommonServiceItemRequestCommonServiceItemFromJSONTyped(json, false);
}

export function PostCommonServiceItemRequestCommonServiceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCommonServiceItemRequestCommonServiceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['Name'],
        'description': json['Description'],
        'tags': json['Tags'],
        'icon': CommonServiceItemIconFromJSON(json['Icon']),
        'provider': PostCommonServiceItemRequestCommonServiceItemProviderFromJSON(json['Provider']),
        'settings': CommonServiceItemSettingsFromJSON(json['Settings']),
        'serviceClass': json['ServiceClass'],
    };
}

export function PostCommonServiceItemRequestCommonServiceItemToJSON(json: any): PostCommonServiceItemRequestCommonServiceItem {
    return PostCommonServiceItemRequestCommonServiceItemToJSONTyped(json, false);
}

export function PostCommonServiceItemRequestCommonServiceItemToJSONTyped(value?: PostCommonServiceItemRequestCommonServiceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Name': value['name'],
        'Description': value['description'],
        'Tags': value['tags'],
        'Icon': CommonServiceItemIconToJSON(value['icon']),
        'Provider': PostCommonServiceItemRequestCommonServiceItemProviderToJSON(value['provider']),
        'Settings': CommonServiceItemSettingsToJSON(value['settings']),
        'ServiceClass': value['serviceClass'],
    };
}

