/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCommonServiceItemRequestCommonServiceItemProvider
 */
export interface PostCommonServiceItemRequestCommonServiceItemProvider {
    /**
     * 
     * @type {PostCommonServiceItemRequestCommonServiceItemProviderClassEnum}
     * @memberof PostCommonServiceItemRequestCommonServiceItemProvider
     */
    _class: PostCommonServiceItemRequestCommonServiceItemProviderClassEnum;
    /**
     * 
     * @type {string}
     * @memberof PostCommonServiceItemRequestCommonServiceItemProvider
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PostCommonServiceItemRequestCommonServiceItemProvider
     */
    serviceClass?: string;
}


/**
 * @export
 */
export const PostCommonServiceItemRequestCommonServiceItemProviderClassEnum = {
    Saknoticedestination: 'saknoticedestination',
    Saknoticegroup: 'saknoticegroup',
    Saknoticerouting: 'saknoticerouting'
} as const;
export type PostCommonServiceItemRequestCommonServiceItemProviderClassEnum = typeof PostCommonServiceItemRequestCommonServiceItemProviderClassEnum[keyof typeof PostCommonServiceItemRequestCommonServiceItemProviderClassEnum];


/**
 * Check if a given object implements the PostCommonServiceItemRequestCommonServiceItemProvider interface.
 */
export function instanceOfPostCommonServiceItemRequestCommonServiceItemProvider(value: object): value is PostCommonServiceItemRequestCommonServiceItemProvider {
    if ((!('_class' in (value as Record<string, any>)) && !('Class' in (value as Record<string, any>))) || ((value as Record<string, any>)['_class'] === undefined && (value as Record<string, any>)['Class'] === undefined)) return false;
    return true;
}

export function PostCommonServiceItemRequestCommonServiceItemProviderFromJSON(json: any): PostCommonServiceItemRequestCommonServiceItemProvider {
    return PostCommonServiceItemRequestCommonServiceItemProviderFromJSONTyped(json, false);
}

export function PostCommonServiceItemRequestCommonServiceItemProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCommonServiceItemRequestCommonServiceItemProvider {
    if (json == null) {
        return json;
    }
    return {
        
        '_class': json['Class'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'serviceClass': json['ServiceClass'] == null ? undefined : json['ServiceClass'],
    };
}

export function PostCommonServiceItemRequestCommonServiceItemProviderToJSON(json: any): PostCommonServiceItemRequestCommonServiceItemProvider {
    return PostCommonServiceItemRequestCommonServiceItemProviderToJSONTyped(json, false);
}

export function PostCommonServiceItemRequestCommonServiceItemProviderToJSONTyped(value?: PostCommonServiceItemRequestCommonServiceItemProvider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Class': value['_class'],
        'Name': value['name'],
        'ServiceClass': value['serviceClass'],
    };
}

