/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PutCommonServiceItemRequestCommonServiceItem } from './PutCommonServiceItemRequestCommonServiceItem';
import {
    PutCommonServiceItemRequestCommonServiceItemFromJSON,
    PutCommonServiceItemRequestCommonServiceItemFromJSONTyped,
    PutCommonServiceItemRequestCommonServiceItemToJSON,
    PutCommonServiceItemRequestCommonServiceItemToJSONTyped,
} from './PutCommonServiceItemRequestCommonServiceItem';

/**
 * 
 * @export
 * @interface PutCommonServiceItemRequest
 */
export interface PutCommonServiceItemRequest {
    /**
     * 
     * @type {PutCommonServiceItemRequestCommonServiceItem}
     * @memberof PutCommonServiceItemRequest
     */
    commonServiceItem: PutCommonServiceItemRequestCommonServiceItem;
}

/**
 * Check if a given object implements the PutCommonServiceItemRequest interface.
 */
export function instanceOfPutCommonServiceItemRequest(value: object): value is PutCommonServiceItemRequest {
    if ((!('commonServiceItem' in (value as Record<string, any>)) && !('CommonServiceItem' in (value as Record<string, any>))) || ((value as Record<string, any>)['commonServiceItem'] === undefined && (value as Record<string, any>)['CommonServiceItem'] === undefined)) return false;
    return true;
}

export function PutCommonServiceItemRequestFromJSON(json: any): PutCommonServiceItemRequest {
    return PutCommonServiceItemRequestFromJSONTyped(json, false);
}

export function PutCommonServiceItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutCommonServiceItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'commonServiceItem': PutCommonServiceItemRequestCommonServiceItemFromJSON(json['CommonServiceItem']),
    };
}

export function PutCommonServiceItemRequestToJSON(json: any): PutCommonServiceItemRequest {
    return PutCommonServiceItemRequestToJSONTyped(json, false);
}

export function PutCommonServiceItemRequestToJSONTyped(value?: PutCommonServiceItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CommonServiceItem': PutCommonServiceItemRequestCommonServiceItemToJSON(value['commonServiceItem']),
    };
}

