/* tslint:disable */
/* eslint-disable */
/**
 * シンプル通知 API
 * --- Copyright SAKURA internet Inc.  # はじめに 「シンプル通知」は、メールや Webhook を利用し、任意のタイミングで通知を送信するサービスです。  # 基本的な使い方 ## APIキーの発行 APIを利用するためには、認証のための「APIキー」が必要です。事前にキーを発行しておきます。 APIキーは「ユーザーID」「パスワード」に相当する「トークン」と呼ばれる認証情報で構成されています。 |   項目名   | APIキー発行時の項目名        | このドキュメント内での例             | |------------|------------------------------|--------------------------------------| | ユーザーID | アクセストークン(UUID)       | 01234567-89ab-cdef-0123-456789abcdef | | パスワード | アクセストークンシークレット | SAMPLETOKENSAMPLETOKENSAMPLETOKENSAM | <div class=\"warning\">   <b>操作マニュアル</b><br />   <ul><li><a href=\"https://manual.sakura.ad.jp/cloud/api/apikey.html\">APIキー | さくらのクラウド ドキュメント</a></li></ul> </div>  ## APIエンドポイント https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReorderNotificationRouting202Response
 */
export interface ReorderNotificationRouting202Response {
    /**
     * 
     * @type {boolean}
     * @memberof ReorderNotificationRouting202Response
     */
    isOk?: boolean;
}

/**
 * Check if a given object implements the ReorderNotificationRouting202Response interface.
 */
export function instanceOfReorderNotificationRouting202Response(value: object): value is ReorderNotificationRouting202Response {
    return true;
}

export function ReorderNotificationRouting202ResponseFromJSON(json: any): ReorderNotificationRouting202Response {
    return ReorderNotificationRouting202ResponseFromJSONTyped(json, false);
}

export function ReorderNotificationRouting202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderNotificationRouting202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'isOk': json['is_ok'] == null ? undefined : json['is_ok'],
    };
}

export function ReorderNotificationRouting202ResponseToJSON(json: any): ReorderNotificationRouting202Response {
    return ReorderNotificationRouting202ResponseToJSONTyped(json, false);
}

export function ReorderNotificationRouting202ResponseToJSONTyped(value?: ReorderNotificationRouting202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_ok': value['isOk'],
    };
}

