/* tslint:disable */
/* eslint-disable */
/**
 * シンプルMQ API
 * --- Copyright SAKURA internet Inc.  # はじめに  「シンプルMQ」は、ソフトウェア同士を非同期に連携するために、ソフトウェアコンポーネント間でのデータの送受信ができる、マネージド型のメッセージキューサービスです。 シンプルMQを使うには、さくらのクラウド コントロールパネルもしくは [シンプルMQ さくらのクラウドAPI](https://manual.sakura.ad.jp/api/cloud/portal/?api=simplemq-sacloud-api) でシンプルMQのキューを作成します。 キューを作成するとAPIキーが発行されます。 APIリクエストは、そのキーを `Authorization header` の `Bearer token` に使用します。  APIエンドポイント：https://simplemq.tk1b.api.sacloud.jp 
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * メッセージID
     * @type {string}
     * @memberof Message
     */
    id: string;
    /**
     * メッセージ本文
     * @type {string}
     * @memberof Message
     */
    content: string;
    /**
     * 登録時刻 (Epochからのミリ秒)
     * @type {number}
     * @memberof Message
     */
    createdAt: number;
    /**
     * 更新時刻 (Epochからのミリ秒)
     * @type {number}
     * @memberof Message
     */
    updatedAt: number;
    /**
     * 未処理メッセージ保存期間が過ぎる時点 (Epochからのミリ秒)
     * @type {number}
     * @memberof Message
     */
    expiresAt: number;
    /**
     * 最新のメッセージ取得時刻 (Epochからのミリ秒)
     * @type {number}
     * @memberof Message
     */
    acquiredAt: number;
    /**
     * 可視性タイムアウトする時点 (Epochからのミリ秒)
     * @type {number}
     * @memberof Message
     */
    visibilityTimeoutAt: number;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): value is Message {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if ((!('expiresAt' in (value as Record<string, any>)) && !('expires_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresAt'] === undefined && (value as Record<string, any>)['expires_at'] === undefined)) return false;
    if ((!('acquiredAt' in (value as Record<string, any>)) && !('acquired_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['acquiredAt'] === undefined && (value as Record<string, any>)['acquired_at'] === undefined)) return false;
    if ((!('visibilityTimeoutAt' in (value as Record<string, any>)) && !('visibility_timeout_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['visibilityTimeoutAt'] === undefined && (value as Record<string, any>)['visibility_timeout_at'] === undefined)) return false;
    return true;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'expiresAt': json['expires_at'],
        'acquiredAt': json['acquired_at'],
        'visibilityTimeoutAt': json['visibility_timeout_at'],
    };
}

export function MessageToJSON(json: any): Message {
    return MessageToJSONTyped(json, false);
}

export function MessageToJSONTyped(value?: Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'expires_at': value['expiresAt'],
        'acquired_at': value['acquiredAt'],
        'visibility_timeout_at': value['visibilityTimeoutAt'],
    };
}

