/* tslint:disable */
/* eslint-disable */
/**
 * シンプルMQ API
 * --- Copyright SAKURA internet Inc.  # はじめに  「シンプルMQ」は、ソフトウェア同士を非同期に連携するために、ソフトウェアコンポーネント間でのデータの送受信ができる、マネージド型のメッセージキューサービスです。 シンプルMQを使うには、さくらのクラウド コントロールパネルもしくは [シンプルMQ さくらのクラウドAPI](https://manual.sakura.ad.jp/api/cloud/portal/?api=simplemq-sacloud-api) でシンプルMQのキューを作成します。 キューを作成するとAPIキーが発行されます。 APIリクエストは、そのキーを `Authorization header` の `Bearer token` に使用します。  APIエンドポイント：https://simplemq.tk1b.api.sacloud.jp 
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';

/**
 * 
 * @export
 * @interface ReceiveMessage200Response
 */
export interface ReceiveMessage200Response {
    /**
     * 
     * @type {string}
     * @memberof ReceiveMessage200Response
     */
    result: string;
    /**
     * 
     * @type {Array<Message>}
     * @memberof ReceiveMessage200Response
     */
    messages: Array<Message>;
}

/**
 * Check if a given object implements the ReceiveMessage200Response interface.
 */
export function instanceOfReceiveMessage200Response(value: object): value is ReceiveMessage200Response {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ReceiveMessage200ResponseFromJSON(json: any): ReceiveMessage200Response {
    return ReceiveMessage200ResponseFromJSONTyped(json, false);
}

export function ReceiveMessage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiveMessage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
        'messages': ((json['messages'] as Array<any>).map(MessageFromJSON)),
    };
}

export function ReceiveMessage200ResponseToJSON(json: any): ReceiveMessage200Response {
    return ReceiveMessage200ResponseToJSONTyped(json, false);
}

export function ReceiveMessage200ResponseToJSONTyped(value?: ReceiveMessage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'messages': ((value['messages'] as Array<any>).map(MessageToJSON)),
    };
}

