/* tslint:disable */
/* eslint-disable */
/**
 * シンプルMQ API
 * --- Copyright SAKURA internet Inc.  # はじめに  「シンプルMQ」は、ソフトウェア同士を非同期に連携するために、ソフトウェアコンポーネント間でのデータの送受信ができる、マネージド型のメッセージキューサービスです。 シンプルMQを使うには、さくらのクラウド コントロールパネルもしくは [シンプルMQ さくらのクラウドAPI](https://manual.sakura.ad.jp/api/cloud/portal/?api=simplemq-sacloud-api) でシンプルMQのキューを作成します。 キューを作成するとAPIキーが発行されます。 APIリクエストは、そのキーを `Authorization header` の `Bearer token` に使用します。  APIエンドポイント：https://simplemq.tk1b.api.sacloud.jp 
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendRequest
 */
export interface SendRequest {
    /**
     * メッセージ本文
     * @type {string}
     * @memberof SendRequest
     */
    content: string;
}

/**
 * Check if a given object implements the SendRequest interface.
 */
export function instanceOfSendRequest(value: object): value is SendRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SendRequestFromJSON(json: any): SendRequest {
    return SendRequestFromJSONTyped(json, false);
}

export function SendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function SendRequestToJSON(json: any): SendRequest {
    return SendRequestToJSONTyped(json, false);
}

export function SendRequestToJSONTyped(value?: SendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

