/* tslint:disable */
/* eslint-disable */
/**
 * シンプルMQ API
 * --- Copyright SAKURA internet Inc.  # はじめに  「シンプルMQ」は、ソフトウェア同士を非同期に連携するために、ソフトウェアコンポーネント間でのデータの送受信ができる、マネージド型のメッセージキューサービスです。 シンプルMQを使うには、さくらのクラウド コントロールパネルもしくは [シンプルMQ さくらのクラウドAPI](https://manual.sakura.ad.jp/api/cloud/portal/?api=simplemq-sacloud-api) でシンプルMQのキューを作成します。 キューを作成するとAPIキーが発行されます。 APIリクエストは、そのキーを `Authorization header` の `Bearer token` に使用します。  APIエンドポイント：https://simplemq.tk1b.api.sacloud.jp 
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewMessage } from './NewMessage';
import {
    NewMessageFromJSON,
    NewMessageFromJSONTyped,
    NewMessageToJSON,
    NewMessageToJSONTyped,
} from './NewMessage';

/**
 * 
 * @export
 * @interface SendMessage200Response
 */
export interface SendMessage200Response {
    /**
     * 
     * @type {string}
     * @memberof SendMessage200Response
     */
    result: string;
    /**
     * 
     * @type {NewMessage}
     * @memberof SendMessage200Response
     */
    message: NewMessage;
}

/**
 * Check if a given object implements the SendMessage200Response interface.
 */
export function instanceOfSendMessage200Response(value: object): value is SendMessage200Response {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SendMessage200ResponseFromJSON(json: any): SendMessage200Response {
    return SendMessage200ResponseFromJSONTyped(json, false);
}

export function SendMessage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
        'message': NewMessageFromJSON(json['message']),
    };
}

export function SendMessage200ResponseToJSON(json: any): SendMessage200Response {
    return SendMessage200ResponseToJSONTyped(json, false);
}

export function SendMessage200ResponseToJSONTyped(value?: SendMessage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'message': NewMessageToJSON(value['message']),
    };
}

