/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateFolderRequest,
    CreateFolderRequestFromJSON,
    CreateFolderRequestToJSON,
} from '../models/CreateFolderRequest';
import {
    type Folder,
    FolderFromJSON,
    FolderToJSON,
} from '../models/Folder';
import {
    type Http400BadRequest,
    Http400BadRequestFromJSON,
    Http400BadRequestToJSON,
} from '../models/Http400BadRequest';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type Http503ServiceUnavailable,
    Http503ServiceUnavailableFromJSON,
    Http503ServiceUnavailableToJSON,
} from '../models/Http503ServiceUnavailable';
import {
    type ListFolders200Response,
    ListFolders200ResponseFromJSON,
    ListFolders200ResponseToJSON,
} from '../models/ListFolders200Response';
import {
    type MoveFolders,
    MoveFoldersFromJSON,
    MoveFoldersToJSON,
} from '../models/MoveFolders';
import {
    type UpdateFolderRequest,
    UpdateFolderRequestFromJSON,
    UpdateFolderRequestToJSON,
} from '../models/UpdateFolderRequest';

export interface CreateFolderOperationRequest {
    createFolderRequest: CreateFolderRequest;
}

export interface DeleteFolderRequest {
    folderId: number;
}

export interface ListFoldersRequest {
    page?: number;
    perPage?: number;
    folderName?: string;
    parentId?: number;
}

export interface MoveFoldersRequest {
    moveFolders: MoveFolders;
}

export interface ReadFolderRequest {
    folderId: number;
}

export interface UpdateFolderOperationRequest {
    folderId: number;
    updateFolderRequest: UpdateFolderRequest;
}

/**
 * FolderApi - interface
 * 
 * @export
 * @interface FolderApiInterface
 */
export interface FolderApiInterface {
    /**
     * Creates request options for createFolder without sending the request
     * @param {CreateFolderRequest} createFolderRequest 
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    createFolderRequestOpts(requestParameters: CreateFolderOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary フォルダを作成する
     * @param {CreateFolderRequest} createFolderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    createFolderRaw(requestParameters: CreateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Folder>>;

    /**
     * フォルダを作成する
     */
    createFolder(requestParameters: CreateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Folder>;

    /**
     * Creates request options for deleteFolder without sending the request
     * @param {number} folderId フォルダID
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    deleteFolderRequestOpts(requestParameters: DeleteFolderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary フォルダを削除する
     * @param {number} folderId フォルダID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    deleteFolderRaw(requestParameters: DeleteFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * フォルダを削除する
     */
    deleteFolder(requestParameters: DeleteFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listFolders without sending the request
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {string} [folderName] フォルダ名での絞り込み。
     * @param {number} [parentId] 親のフォルダIDでの絞り込み。
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    listFoldersRequestOpts(requestParameters: ListFoldersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary フォルダ一覧を取得する
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {string} [folderName] フォルダ名での絞り込み。
     * @param {number} [parentId] 親のフォルダIDでの絞り込み。
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    listFoldersRaw(requestParameters: ListFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFolders200Response>>;

    /**
     * フォルダ一覧を取得する
     */
    listFolders(requestParameters: ListFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFolders200Response>;

    /**
     * Creates request options for moveFolders without sending the request
     * @param {MoveFolders} moveFolders 
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    moveFoldersRequestOpts(requestParameters: MoveFoldersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary フォルダを移動する
     * @param {MoveFolders} moveFolders 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    moveFoldersRaw(requestParameters: MoveFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * フォルダを移動する
     */
    moveFolders(requestParameters: MoveFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for readFolder without sending the request
     * @param {number} folderId フォルダID
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    readFolderRequestOpts(requestParameters: ReadFolderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 特定のフォルダの情報を取得する
     * @param {number} folderId フォルダID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    readFolderRaw(requestParameters: ReadFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Folder>>;

    /**
     * 特定のフォルダの情報を取得する
     */
    readFolder(requestParameters: ReadFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Folder>;

    /**
     * Creates request options for updateFolder without sending the request
     * @param {number} folderId フォルダID
     * @param {UpdateFolderRequest} updateFolderRequest 
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    updateFolderRequestOpts(requestParameters: UpdateFolderOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 特定のフォルダの情報を更新する
     * @param {number} folderId フォルダID
     * @param {UpdateFolderRequest} updateFolderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FolderApiInterface
     */
    updateFolderRaw(requestParameters: UpdateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Folder>>;

    /**
     * 特定のフォルダの情報を更新する
     */
    updateFolder(requestParameters: UpdateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Folder>;

}

/**
 * 
 */
export class FolderApi extends runtime.BaseAPI implements FolderApiInterface {

    /**
     * Creates request options for createFolder without sending the request
     */
    async createFolderRequestOpts(requestParameters: CreateFolderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createFolderRequest'] == null) {
            throw new runtime.RequiredError(
                'createFolderRequest',
                'Required parameter "createFolderRequest" was null or undefined when calling createFolder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/folders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFolderRequestToJSON(requestParameters['createFolderRequest']),
        };
    }

    /**
     * フォルダを作成する
     */
    async createFolderRaw(requestParameters: CreateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Folder>> {
        const requestOptions = await this.createFolderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FolderFromJSON(jsonValue));
    }

    /**
     * フォルダを作成する
     */
    async createFolder(requestParameters: CreateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Folder> {
        const response = await this.createFolderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteFolder without sending the request
     */
    async deleteFolderRequestOpts(requestParameters: DeleteFolderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['folderId'] == null) {
            throw new runtime.RequiredError(
                'folderId',
                'Required parameter "folderId" was null or undefined when calling deleteFolder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/folders/{folder_id}`;
        urlPath = urlPath.replace('{folder_id}', encodeURIComponent(String(requestParameters['folderId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * フォルダを削除する
     */
    async deleteFolderRaw(requestParameters: DeleteFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteFolderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * フォルダを削除する
     */
    async deleteFolder(requestParameters: DeleteFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFolderRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listFolders without sending the request
     */
    async listFoldersRequestOpts(requestParameters: ListFoldersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['folderName'] != null) {
            queryParameters['folder_name'] = requestParameters['folderName'];
        }

        if (requestParameters['parentId'] != null) {
            queryParameters['parent_id'] = requestParameters['parentId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/folders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * フォルダ一覧を取得する
     */
    async listFoldersRaw(requestParameters: ListFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFolders200Response>> {
        const requestOptions = await this.listFoldersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFolders200ResponseFromJSON(jsonValue));
    }

    /**
     * フォルダ一覧を取得する
     */
    async listFolders(requestParameters: ListFoldersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFolders200Response> {
        const response = await this.listFoldersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for moveFolders without sending the request
     */
    async moveFoldersRequestOpts(requestParameters: MoveFoldersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['moveFolders'] == null) {
            throw new runtime.RequiredError(
                'moveFolders',
                'Required parameter "moveFolders" was null or undefined when calling moveFolders().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/move-folders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MoveFoldersToJSON(requestParameters['moveFolders']),
        };
    }

    /**
     * フォルダを移動する
     */
    async moveFoldersRaw(requestParameters: MoveFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.moveFoldersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * フォルダを移動する
     */
    async moveFolders(requestParameters: MoveFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.moveFoldersRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for readFolder without sending the request
     */
    async readFolderRequestOpts(requestParameters: ReadFolderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['folderId'] == null) {
            throw new runtime.RequiredError(
                'folderId',
                'Required parameter "folderId" was null or undefined when calling readFolder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/folders/{folder_id}`;
        urlPath = urlPath.replace('{folder_id}', encodeURIComponent(String(requestParameters['folderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 特定のフォルダの情報を取得する
     */
    async readFolderRaw(requestParameters: ReadFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Folder>> {
        const requestOptions = await this.readFolderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FolderFromJSON(jsonValue));
    }

    /**
     * 特定のフォルダの情報を取得する
     */
    async readFolder(requestParameters: ReadFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Folder> {
        const response = await this.readFolderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateFolder without sending the request
     */
    async updateFolderRequestOpts(requestParameters: UpdateFolderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['folderId'] == null) {
            throw new runtime.RequiredError(
                'folderId',
                'Required parameter "folderId" was null or undefined when calling updateFolder().'
            );
        }

        if (requestParameters['updateFolderRequest'] == null) {
            throw new runtime.RequiredError(
                'updateFolderRequest',
                'Required parameter "updateFolderRequest" was null or undefined when calling updateFolder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/folders/{folder_id}`;
        urlPath = urlPath.replace('{folder_id}', encodeURIComponent(String(requestParameters['folderId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFolderRequestToJSON(requestParameters['updateFolderRequest']),
        };
    }

    /**
     * 特定のフォルダの情報を更新する
     */
    async updateFolderRaw(requestParameters: UpdateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Folder>> {
        const requestOptions = await this.updateFolderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FolderFromJSON(jsonValue));
    }

    /**
     * 特定のフォルダの情報を更新する
     */
    async updateFolder(requestParameters: UpdateFolderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Folder> {
        const response = await this.updateFolderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
