/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type IdRole,
    IdRoleFromJSON,
    IdRoleToJSON,
} from '../models/IdRole';
import {
    type ListIdRoles200Response,
    ListIdRoles200ResponseFromJSON,
    ListIdRoles200ResponseToJSON,
} from '../models/ListIdRoles200Response';

export interface ListIdRolesRequest {
    page?: number;
    perPage?: number;
}

export interface ReadIdRoleRequest {
    idRoleId: string;
}

/**
 * IdRoleApi - interface
 * 
 * @export
 * @interface IdRoleApiInterface
 */
export interface IdRoleApiInterface {
    /**
     * Creates request options for listIdRoles without sending the request
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @throws {RequiredError}
     * @memberof IdRoleApiInterface
     */
    listIdRolesRequestOpts(requestParameters: ListIdRolesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary IDロール一覧を取得する
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdRoleApiInterface
     */
    listIdRolesRaw(requestParameters: ListIdRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListIdRoles200Response>>;

    /**
     * IDロール一覧を取得する
     */
    listIdRoles(requestParameters: ListIdRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListIdRoles200Response>;

    /**
     * Creates request options for readIdRole without sending the request
     * @param {string} idRoleId IDロールID
     * @throws {RequiredError}
     * @memberof IdRoleApiInterface
     */
    readIdRoleRequestOpts(requestParameters: ReadIdRoleRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したIDロールを取得する
     * @param {string} idRoleId IDロールID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdRoleApiInterface
     */
    readIdRoleRaw(requestParameters: ReadIdRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdRole>>;

    /**
     * 指定したIDロールを取得する
     */
    readIdRole(requestParameters: ReadIdRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdRole>;

}

/**
 * 
 */
export class IdRoleApi extends runtime.BaseAPI implements IdRoleApiInterface {

    /**
     * Creates request options for listIdRoles without sending the request
     */
    async listIdRolesRequestOpts(requestParameters: ListIdRolesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/id-roles`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * IDロール一覧を取得する
     */
    async listIdRolesRaw(requestParameters: ListIdRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListIdRoles200Response>> {
        const requestOptions = await this.listIdRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListIdRoles200ResponseFromJSON(jsonValue));
    }

    /**
     * IDロール一覧を取得する
     */
    async listIdRoles(requestParameters: ListIdRolesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListIdRoles200Response> {
        const response = await this.listIdRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readIdRole without sending the request
     */
    async readIdRoleRequestOpts(requestParameters: ReadIdRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idRoleId'] == null) {
            throw new runtime.RequiredError(
                'idRoleId',
                'Required parameter "idRoleId" was null or undefined when calling readIdRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/id-roles/{id_role_id}`;
        urlPath = urlPath.replace('{id_role_id}', encodeURIComponent(String(requestParameters['idRoleId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したIDロールを取得する
     */
    async readIdRoleRaw(requestParameters: ReadIdRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdRole>> {
        const requestOptions = await this.readIdRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdRoleFromJSON(jsonValue));
    }

    /**
     * 指定したIDロールを取得する
     */
    async readIdRole(requestParameters: ReadIdRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdRole> {
        const response = await this.readIdRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
