/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateApiKeyRequest,
    CreateApiKeyRequestFromJSON,
    CreateApiKeyRequestToJSON,
} from '../models/CreateApiKeyRequest';
import {
    type Http400BadRequest,
    Http400BadRequestFromJSON,
    Http400BadRequestToJSON,
} from '../models/Http400BadRequest';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type Http503ServiceUnavailable,
    Http503ServiceUnavailableFromJSON,
    Http503ServiceUnavailableToJSON,
} from '../models/Http503ServiceUnavailable';
import {
    type ListApiKeys200Response,
    ListApiKeys200ResponseFromJSON,
    ListApiKeys200ResponseToJSON,
} from '../models/ListApiKeys200Response';
import {
    type ProjectApiKey,
    ProjectApiKeyFromJSON,
    ProjectApiKeyToJSON,
} from '../models/ProjectApiKey';
import {
    type ProjectApiKeyWithSecret,
    ProjectApiKeyWithSecretFromJSON,
    ProjectApiKeyWithSecretToJSON,
} from '../models/ProjectApiKeyWithSecret';
import {
    type UpdateApiKeyRequest,
    UpdateApiKeyRequestFromJSON,
    UpdateApiKeyRequestToJSON,
} from '../models/UpdateApiKeyRequest';

export interface CreateApiKeyOperationRequest {
    createApiKeyRequest: CreateApiKeyRequest;
}

export interface DeleteApiKeyRequest {
    apikeyId: number;
}

export interface ListApiKeysRequest {
    page?: number;
    perPage?: number;
    ordering?: ListApiKeysOrderingEnum;
}

export interface ReadApiKeyRequest {
    apikeyId: number;
}

export interface UpdateApiKeyOperationRequest {
    apikeyId: number;
    updateApiKeyRequest: UpdateApiKeyRequest;
}

/**
 * ProjectApikeyApi - interface
 * 
 * @export
 * @interface ProjectApikeyApiInterface
 */
export interface ProjectApikeyApiInterface {
    /**
     * Creates request options for createApiKey without sending the request
     * @param {CreateApiKeyRequest} createApiKeyRequest APIキーの情報
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    createApiKeyRequestOpts(requestParameters: CreateApiKeyOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * @summary APIキーを作成する
     * @param {CreateApiKeyRequest} createApiKeyRequest APIキーの情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    createApiKeyRaw(requestParameters: CreateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectApiKeyWithSecret>>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * APIキーを作成する
     */
    createApiKey(requestParameters: CreateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectApiKeyWithSecret>;

    /**
     * Creates request options for deleteApiKey without sending the request
     * @param {number} apikeyId APIキーID
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    deleteApiKeyRequestOpts(requestParameters: DeleteApiKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * @summary 指定したAPIキーを削除する
     * @param {number} apikeyId APIキーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    deleteApiKeyRaw(requestParameters: DeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを削除する
     */
    deleteApiKey(requestParameters: DeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listApiKeys without sending the request
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'name' | '-name'} [ordering] 並び替えキー * &#x60;name&#x60; - APIキー名昇順 * &#x60;-name&#x60; - APIキー名降順 
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    listApiKeysRequestOpts(requestParameters: ListApiKeysRequest): Promise<runtime.RequestOpts>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * @summary APIキー一覧を取得する
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'name' | '-name'} [ordering] 並び替えキー * &#x60;name&#x60; - APIキー名昇順 * &#x60;-name&#x60; - APIキー名降順 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    listApiKeysRaw(requestParameters: ListApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApiKeys200Response>>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * APIキー一覧を取得する
     */
    listApiKeys(requestParameters: ListApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApiKeys200Response>;

    /**
     * Creates request options for readApiKey without sending the request
     * @param {number} apikeyId APIキーID
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    readApiKeyRequestOpts(requestParameters: ReadApiKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * @summary 指定したAPIキーを取得する
     * @param {number} apikeyId APIキーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    readApiKeyRaw(requestParameters: ReadApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectApiKey>>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを取得する
     */
    readApiKey(requestParameters: ReadApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectApiKey>;

    /**
     * Creates request options for updateApiKey without sending the request
     * @param {number} apikeyId APIキーID
     * @param {UpdateApiKeyRequest} updateApiKeyRequest 
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    updateApiKeyRequestOpts(requestParameters: UpdateApiKeyOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * @summary 指定したAPIキーを更新する
     * @param {number} apikeyId APIキーID
     * @param {UpdateApiKeyRequest} updateApiKeyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApikeyApiInterface
     */
    updateApiKeyRaw(requestParameters: UpdateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectApiKey>>;

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを更新する
     */
    updateApiKey(requestParameters: UpdateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectApiKey>;

}

/**
 * 
 */
export class ProjectApikeyApi extends runtime.BaseAPI implements ProjectApikeyApiInterface {

    /**
     * Creates request options for createApiKey without sending the request
     */
    async createApiKeyRequestOpts(requestParameters: CreateApiKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createApiKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'createApiKeyRequest',
                'Required parameter "createApiKeyRequest" was null or undefined when calling createApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/api-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateApiKeyRequestToJSON(requestParameters['createApiKeyRequest']),
        };
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * APIキーを作成する
     */
    async createApiKeyRaw(requestParameters: CreateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectApiKeyWithSecret>> {
        const requestOptions = await this.createApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectApiKeyWithSecretFromJSON(jsonValue));
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * APIキーを作成する
     */
    async createApiKey(requestParameters: CreateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectApiKeyWithSecret> {
        const response = await this.createApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiKey without sending the request
     */
    async deleteApiKeyRequestOpts(requestParameters: DeleteApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['apikeyId'] == null) {
            throw new runtime.RequiredError(
                'apikeyId',
                'Required parameter "apikeyId" was null or undefined when calling deleteApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/api-keys/{apikey_id}`;
        urlPath = urlPath.replace('{apikey_id}', encodeURIComponent(String(requestParameters['apikeyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを削除する
     */
    async deleteApiKeyRaw(requestParameters: DeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを削除する
     */
    async deleteApiKey(requestParameters: DeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiKeyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listApiKeys without sending the request
     */
    async listApiKeysRequestOpts(requestParameters: ListApiKeysRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/api-keys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * APIキー一覧を取得する
     */
    async listApiKeysRaw(requestParameters: ListApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApiKeys200Response>> {
        const requestOptions = await this.listApiKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListApiKeys200ResponseFromJSON(jsonValue));
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * APIキー一覧を取得する
     */
    async listApiKeys(requestParameters: ListApiKeysRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApiKeys200Response> {
        const response = await this.listApiKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readApiKey without sending the request
     */
    async readApiKeyRequestOpts(requestParameters: ReadApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['apikeyId'] == null) {
            throw new runtime.RequiredError(
                'apikeyId',
                'Required parameter "apikeyId" was null or undefined when calling readApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/api-keys/{apikey_id}`;
        urlPath = urlPath.replace('{apikey_id}', encodeURIComponent(String(requestParameters['apikeyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを取得する
     */
    async readApiKeyRaw(requestParameters: ReadApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectApiKey>> {
        const requestOptions = await this.readApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectApiKeyFromJSON(jsonValue));
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを取得する
     */
    async readApiKey(requestParameters: ReadApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectApiKey> {
        const response = await this.readApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiKey without sending the request
     */
    async updateApiKeyRequestOpts(requestParameters: UpdateApiKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['apikeyId'] == null) {
            throw new runtime.RequiredError(
                'apikeyId',
                'Required parameter "apikeyId" was null or undefined when calling updateApiKey().'
            );
        }

        if (requestParameters['updateApiKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'updateApiKeyRequest',
                'Required parameter "updateApiKeyRequest" was null or undefined when calling updateApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/api-keys/{apikey_id}`;
        urlPath = urlPath.replace('{apikey_id}', encodeURIComponent(String(requestParameters['apikeyId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateApiKeyRequestToJSON(requestParameters['updateApiKeyRequest']),
        };
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを更新する
     */
    async updateApiKeyRaw(requestParameters: UpdateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectApiKey>> {
        const requestOptions = await this.updateApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectApiKeyFromJSON(jsonValue));
    }

    /**
     * サービスプリンシパルによる操作の場合、サービスプリンシパルが所属するプロジェクトとは異なるプロジェクトのAPIキーは操作できません。
     * 指定したAPIキーを更新する
     */
    async updateApiKey(requestParameters: UpdateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectApiKey> {
        const response = await this.updateApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListApiKeysOrderingEnum = {
    Name: 'name',
    Name2: '-name'
} as const;
export type ListApiKeysOrderingEnum = typeof ListApiKeysOrderingEnum[keyof typeof ListApiKeysOrderingEnum];
