/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateProjectRequest,
    CreateProjectRequestFromJSON,
    CreateProjectRequestToJSON,
} from '../models/CreateProjectRequest';
import {
    type Http400BadRequest,
    Http400BadRequestFromJSON,
    Http400BadRequestToJSON,
} from '../models/Http400BadRequest';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http409Conflict,
    Http409ConflictFromJSON,
    Http409ConflictToJSON,
} from '../models/Http409Conflict';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type Http503ServiceUnavailable,
    Http503ServiceUnavailableFromJSON,
    Http503ServiceUnavailableToJSON,
} from '../models/Http503ServiceUnavailable';
import {
    type ListProjects200Response,
    ListProjects200ResponseFromJSON,
    ListProjects200ResponseToJSON,
} from '../models/ListProjects200Response';
import {
    type MoveProjects,
    MoveProjectsFromJSON,
    MoveProjectsToJSON,
} from '../models/MoveProjects';
import {
    type Project,
    ProjectFromJSON,
    ProjectToJSON,
} from '../models/Project';
import {
    type UpdateProjectRequest,
    UpdateProjectRequestFromJSON,
    UpdateProjectRequestToJSON,
} from '../models/UpdateProjectRequest';

export interface CreateProjectOperationRequest {
    createProjectRequest: CreateProjectRequest;
}

export interface DeleteProjectRequest {
    projectId: number;
}

export interface ListProjectsRequest {
    page?: number;
    perPage?: number;
    ordering?: ListProjectsOrderingEnum;
    iamRole?: string;
    parentFolderId?: number;
}

export interface MoveProjectsRequest {
    moveProjects: MoveProjects;
}

export interface ReadProjectRequest {
    projectId: number;
}

export interface UpdateProjectOperationRequest {
    projectId: number;
    updateProjectRequest: UpdateProjectRequest;
}

/**
 * ProjectApi - interface
 * 
 * @export
 * @interface ProjectApiInterface
 */
export interface ProjectApiInterface {
    /**
     * Creates request options for createProject without sending the request
     * @param {CreateProjectRequest} createProjectRequest 
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    createProjectRequestOpts(requestParameters: CreateProjectOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary プロジェクトを作成する
     * @param {CreateProjectRequest} createProjectRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    createProjectRaw(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>>;

    /**
     * プロジェクトを作成する
     */
    createProject(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project>;

    /**
     * Creates request options for deleteProject without sending the request
     * @param {number} projectId プロジェクトID
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    deleteProjectRequestOpts(requestParameters: DeleteProjectRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したプロジェクトを削除する
     * @param {number} projectId プロジェクトID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    deleteProjectRaw(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 指定したプロジェクトを削除する
     */
    deleteProject(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listProjects without sending the request
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'code' | '-code'} [ordering] 並び替えキー  * &#x60;code&#x60; - プロジェクトコード昇順 * &#x60;-code&#x60; - プロジェクトコード降順 
     * @param {string} [iamRole] IAMロールでの絞り込み。カンマ区切りで複数指定可能
     * @param {number} [parentFolderId] 親のフォルダIDでの絞り込み。
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    listProjectsRequestOpts(requestParameters: ListProjectsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary プロジェクト一覧を取得する
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'code' | '-code'} [ordering] 並び替えキー  * &#x60;code&#x60; - プロジェクトコード昇順 * &#x60;-code&#x60; - プロジェクトコード降順 
     * @param {string} [iamRole] IAMロールでの絞り込み。カンマ区切りで複数指定可能
     * @param {number} [parentFolderId] 親のフォルダIDでの絞り込み。
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    listProjectsRaw(requestParameters: ListProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProjects200Response>>;

    /**
     * プロジェクト一覧を取得する
     */
    listProjects(requestParameters: ListProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProjects200Response>;

    /**
     * Creates request options for moveProjects without sending the request
     * @param {MoveProjects} moveProjects 
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    moveProjectsRequestOpts(requestParameters: MoveProjectsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary プロジェクトを一括で移動する
     * @param {MoveProjects} moveProjects 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    moveProjectsRaw(requestParameters: MoveProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * プロジェクトを一括で移動する
     */
    moveProjects(requestParameters: MoveProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for readProject without sending the request
     * @param {number} projectId プロジェクトID
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    readProjectRequestOpts(requestParameters: ReadProjectRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したプロジェクトを取得する
     * @param {number} projectId プロジェクトID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    readProjectRaw(requestParameters: ReadProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>>;

    /**
     * 指定したプロジェクトを取得する
     */
    readProject(requestParameters: ReadProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project>;

    /**
     * Creates request options for updateProject without sending the request
     * @param {number} projectId プロジェクトID
     * @param {UpdateProjectRequest} updateProjectRequest 
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    updateProjectRequestOpts(requestParameters: UpdateProjectOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したプロジェクトを更新する
     * @param {number} projectId プロジェクトID
     * @param {UpdateProjectRequest} updateProjectRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    updateProjectRaw(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>>;

    /**
     * 指定したプロジェクトを更新する
     */
    updateProject(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project>;

}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI implements ProjectApiInterface {

    /**
     * Creates request options for createProject without sending the request
     */
    async createProjectRequestOpts(requestParameters: CreateProjectOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectRequest',
                'Required parameter "createProjectRequest" was null or undefined when calling createProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectRequestToJSON(requestParameters['createProjectRequest']),
        };
    }

    /**
     * プロジェクトを作成する
     */
    async createProjectRaw(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        const requestOptions = await this.createProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * プロジェクトを作成する
     */
    async createProject(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.createProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteProject without sending the request
     */
    async deleteProjectRequestOpts(requestParameters: DeleteProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したプロジェクトを削除する
     */
    async deleteProjectRaw(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 指定したプロジェクトを削除する
     */
    async deleteProject(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProjectRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listProjects without sending the request
     */
    async listProjectsRequestOpts(requestParameters: ListProjectsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['iamRole'] != null) {
            queryParameters['iam_role'] = requestParameters['iamRole'];
        }

        if (requestParameters['parentFolderId'] != null) {
            queryParameters['parent_folder_id'] = requestParameters['parentFolderId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * プロジェクト一覧を取得する
     */
    async listProjectsRaw(requestParameters: ListProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProjects200Response>> {
        const requestOptions = await this.listProjectsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListProjects200ResponseFromJSON(jsonValue));
    }

    /**
     * プロジェクト一覧を取得する
     */
    async listProjects(requestParameters: ListProjectsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProjects200Response> {
        const response = await this.listProjectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for moveProjects without sending the request
     */
    async moveProjectsRequestOpts(requestParameters: MoveProjectsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['moveProjects'] == null) {
            throw new runtime.RequiredError(
                'moveProjects',
                'Required parameter "moveProjects" was null or undefined when calling moveProjects().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/move-projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MoveProjectsToJSON(requestParameters['moveProjects']),
        };
    }

    /**
     * プロジェクトを一括で移動する
     */
    async moveProjectsRaw(requestParameters: MoveProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.moveProjectsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * プロジェクトを一括で移動する
     */
    async moveProjects(requestParameters: MoveProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.moveProjectsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for readProject without sending the request
     */
    async readProjectRequestOpts(requestParameters: ReadProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling readProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したプロジェクトを取得する
     */
    async readProjectRaw(requestParameters: ReadProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        const requestOptions = await this.readProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * 指定したプロジェクトを取得する
     */
    async readProject(requestParameters: ReadProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.readProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProject without sending the request
     */
    async updateProjectRequestOpts(requestParameters: UpdateProjectOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProject().'
            );
        }

        if (requestParameters['updateProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProjectRequest',
                'Required parameter "updateProjectRequest" was null or undefined when calling updateProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectRequestToJSON(requestParameters['updateProjectRequest']),
        };
    }

    /**
     * 指定したプロジェクトを更新する
     */
    async updateProjectRaw(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        const requestOptions = await this.updateProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * 指定したプロジェクトを更新する
     */
    async updateProject(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.updateProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListProjectsOrderingEnum = {
    Code: 'code',
    Code2: '-code'
} as const;
export type ListProjectsOrderingEnum = typeof ListProjectsOrderingEnum[keyof typeof ListProjectsOrderingEnum];
