/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateScimConfigurationRequest,
    CreateScimConfigurationRequestFromJSON,
    CreateScimConfigurationRequestToJSON,
} from '../models/CreateScimConfigurationRequest';
import {
    type Http400BadRequest,
    Http400BadRequestFromJSON,
    Http400BadRequestToJSON,
} from '../models/Http400BadRequest';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http409Conflict,
    Http409ConflictFromJSON,
    Http409ConflictToJSON,
} from '../models/Http409Conflict';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type ListScimConfigurations200Response,
    ListScimConfigurations200ResponseFromJSON,
    ListScimConfigurations200ResponseToJSON,
} from '../models/ListScimConfigurations200Response';
import {
    type RegenerateScimConfigurationToken200Response,
    RegenerateScimConfigurationToken200ResponseFromJSON,
    RegenerateScimConfigurationToken200ResponseToJSON,
} from '../models/RegenerateScimConfigurationToken200Response';
import {
    type ScimConfiguration,
    ScimConfigurationFromJSON,
    ScimConfigurationToJSON,
} from '../models/ScimConfiguration';
import {
    type ScimConfigurationPublic,
    ScimConfigurationPublicFromJSON,
    ScimConfigurationPublicToJSON,
} from '../models/ScimConfigurationPublic';

export interface CreateScimConfigurationOperationRequest {
    createScimConfigurationRequest: CreateScimConfigurationRequest;
}

export interface DeleteScimConfigurationRequest {
    id: string;
}

export interface ListScimConfigurationsRequest {
    page?: number;
    perPage?: number;
}

export interface ReadScimConfigurationRequest {
    id: string;
}

export interface RegenerateScimConfigurationTokenRequest {
    id: string;
}

export interface UpdateScimConfigurationRequest {
    id: string;
    createScimConfigurationRequest: CreateScimConfigurationRequest;
}

/**
 * ScimApi - interface
 * 
 * @export
 * @interface ScimApiInterface
 */
export interface ScimApiInterface {
    /**
     * Creates request options for createScimConfiguration without sending the request
     * @param {CreateScimConfigurationRequest} createScimConfigurationRequest 
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    createScimConfigurationRequestOpts(requestParameters: CreateScimConfigurationOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザープロビジョニングを作成する
     * @param {CreateScimConfigurationRequest} createScimConfigurationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    createScimConfigurationRaw(requestParameters: CreateScimConfigurationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScimConfiguration>>;

    /**
     * ユーザープロビジョニングを作成する
     */
    createScimConfiguration(requestParameters: CreateScimConfigurationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScimConfiguration>;

    /**
     * Creates request options for deleteScimConfiguration without sending the request
     * @param {string} id ユーザープロビジョニングID
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    deleteScimConfigurationRequestOpts(requestParameters: DeleteScimConfigurationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザープロビジョニングを削除する
     * @param {string} id ユーザープロビジョニングID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    deleteScimConfigurationRaw(requestParameters: DeleteScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * ユーザープロビジョニングを削除する
     */
    deleteScimConfiguration(requestParameters: DeleteScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listScimConfigurations without sending the request
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    listScimConfigurationsRequestOpts(requestParameters: ListScimConfigurationsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザープロビジョニングを取得する
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    listScimConfigurationsRaw(requestParameters: ListScimConfigurationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListScimConfigurations200Response>>;

    /**
     * ユーザープロビジョニングを取得する
     */
    listScimConfigurations(requestParameters: ListScimConfigurationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListScimConfigurations200Response>;

    /**
     * Creates request options for readScimConfiguration without sending the request
     * @param {string} id ユーザープロビジョニングID
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    readScimConfigurationRequestOpts(requestParameters: ReadScimConfigurationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザープロビジョニングを取得する
     * @param {string} id ユーザープロビジョニングID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    readScimConfigurationRaw(requestParameters: ReadScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScimConfigurationPublic>>;

    /**
     * ユーザープロビジョニングを取得する
     */
    readScimConfiguration(requestParameters: ReadScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScimConfigurationPublic>;

    /**
     * Creates request options for regenerateScimConfigurationToken without sending the request
     * @param {string} id ユーザープロビジョニングID
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    regenerateScimConfigurationTokenRequestOpts(requestParameters: RegenerateScimConfigurationTokenRequest): Promise<runtime.RequestOpts>;

    /**
     * この操作によって既にあるシークレットトークンは無効化されます。ユーザープロビジョニングのクライアント側に新しいシークレットトークンを再設定する必要があります。 
     * @summary ユーザープロビジョニングのシークレットトークンを再発行する
     * @param {string} id ユーザープロビジョニングID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    regenerateScimConfigurationTokenRaw(requestParameters: RegenerateScimConfigurationTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegenerateScimConfigurationToken200Response>>;

    /**
     * この操作によって既にあるシークレットトークンは無効化されます。ユーザープロビジョニングのクライアント側に新しいシークレットトークンを再設定する必要があります。 
     * ユーザープロビジョニングのシークレットトークンを再発行する
     */
    regenerateScimConfigurationToken(requestParameters: RegenerateScimConfigurationTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegenerateScimConfigurationToken200Response>;

    /**
     * Creates request options for updateScimConfiguration without sending the request
     * @param {string} id ユーザープロビジョニングID
     * @param {CreateScimConfigurationRequest} createScimConfigurationRequest 
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    updateScimConfigurationRequestOpts(requestParameters: UpdateScimConfigurationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザープロビジョニングを更新する
     * @param {string} id ユーザープロビジョニングID
     * @param {CreateScimConfigurationRequest} createScimConfigurationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScimApiInterface
     */
    updateScimConfigurationRaw(requestParameters: UpdateScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScimConfigurationPublic>>;

    /**
     * ユーザープロビジョニングを更新する
     */
    updateScimConfiguration(requestParameters: UpdateScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScimConfigurationPublic>;

}

/**
 * 
 */
export class ScimApi extends runtime.BaseAPI implements ScimApiInterface {

    /**
     * Creates request options for createScimConfiguration without sending the request
     */
    async createScimConfigurationRequestOpts(requestParameters: CreateScimConfigurationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createScimConfigurationRequest'] == null) {
            throw new runtime.RequiredError(
                'createScimConfigurationRequest',
                'Required parameter "createScimConfigurationRequest" was null or undefined when calling createScimConfiguration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/scim-configurations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateScimConfigurationRequestToJSON(requestParameters['createScimConfigurationRequest']),
        };
    }

    /**
     * ユーザープロビジョニングを作成する
     */
    async createScimConfigurationRaw(requestParameters: CreateScimConfigurationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScimConfiguration>> {
        const requestOptions = await this.createScimConfigurationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScimConfigurationFromJSON(jsonValue));
    }

    /**
     * ユーザープロビジョニングを作成する
     */
    async createScimConfiguration(requestParameters: CreateScimConfigurationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScimConfiguration> {
        const response = await this.createScimConfigurationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteScimConfiguration without sending the request
     */
    async deleteScimConfigurationRequestOpts(requestParameters: DeleteScimConfigurationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteScimConfiguration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/scim-configurations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザープロビジョニングを削除する
     */
    async deleteScimConfigurationRaw(requestParameters: DeleteScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteScimConfigurationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ユーザープロビジョニングを削除する
     */
    async deleteScimConfiguration(requestParameters: DeleteScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteScimConfigurationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listScimConfigurations without sending the request
     */
    async listScimConfigurationsRequestOpts(requestParameters: ListScimConfigurationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/scim-configurations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザープロビジョニングを取得する
     */
    async listScimConfigurationsRaw(requestParameters: ListScimConfigurationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListScimConfigurations200Response>> {
        const requestOptions = await this.listScimConfigurationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListScimConfigurations200ResponseFromJSON(jsonValue));
    }

    /**
     * ユーザープロビジョニングを取得する
     */
    async listScimConfigurations(requestParameters: ListScimConfigurationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListScimConfigurations200Response> {
        const response = await this.listScimConfigurationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readScimConfiguration without sending the request
     */
    async readScimConfigurationRequestOpts(requestParameters: ReadScimConfigurationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readScimConfiguration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/scim-configurations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザープロビジョニングを取得する
     */
    async readScimConfigurationRaw(requestParameters: ReadScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScimConfigurationPublic>> {
        const requestOptions = await this.readScimConfigurationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScimConfigurationPublicFromJSON(jsonValue));
    }

    /**
     * ユーザープロビジョニングを取得する
     */
    async readScimConfiguration(requestParameters: ReadScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScimConfigurationPublic> {
        const response = await this.readScimConfigurationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for regenerateScimConfigurationToken without sending the request
     */
    async regenerateScimConfigurationTokenRequestOpts(requestParameters: RegenerateScimConfigurationTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling regenerateScimConfigurationToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/scim-configurations/{id}/regenerate-token`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * この操作によって既にあるシークレットトークンは無効化されます。ユーザープロビジョニングのクライアント側に新しいシークレットトークンを再設定する必要があります。 
     * ユーザープロビジョニングのシークレットトークンを再発行する
     */
    async regenerateScimConfigurationTokenRaw(requestParameters: RegenerateScimConfigurationTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegenerateScimConfigurationToken200Response>> {
        const requestOptions = await this.regenerateScimConfigurationTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegenerateScimConfigurationToken200ResponseFromJSON(jsonValue));
    }

    /**
     * この操作によって既にあるシークレットトークンは無効化されます。ユーザープロビジョニングのクライアント側に新しいシークレットトークンを再設定する必要があります。 
     * ユーザープロビジョニングのシークレットトークンを再発行する
     */
    async regenerateScimConfigurationToken(requestParameters: RegenerateScimConfigurationTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegenerateScimConfigurationToken200Response> {
        const response = await this.regenerateScimConfigurationTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateScimConfiguration without sending the request
     */
    async updateScimConfigurationRequestOpts(requestParameters: UpdateScimConfigurationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateScimConfiguration().'
            );
        }

        if (requestParameters['createScimConfigurationRequest'] == null) {
            throw new runtime.RequiredError(
                'createScimConfigurationRequest',
                'Required parameter "createScimConfigurationRequest" was null or undefined when calling updateScimConfiguration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/scim-configurations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateScimConfigurationRequestToJSON(requestParameters['createScimConfigurationRequest']),
        };
    }

    /**
     * ユーザープロビジョニングを更新する
     */
    async updateScimConfigurationRaw(requestParameters: UpdateScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScimConfigurationPublic>> {
        const requestOptions = await this.updateScimConfigurationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScimConfigurationPublicFromJSON(jsonValue));
    }

    /**
     * ユーザープロビジョニングを更新する
     */
    async updateScimConfiguration(requestParameters: UpdateScimConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScimConfigurationPublic> {
        const response = await this.updateScimConfigurationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
