/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateServicePrincipalRequest,
    CreateServicePrincipalRequestFromJSON,
    CreateServicePrincipalRequestToJSON,
} from '../models/CreateServicePrincipalRequest';
import {
    type Http400BadRequest,
    Http400BadRequestFromJSON,
    Http400BadRequestToJSON,
} from '../models/Http400BadRequest';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http409Conflict,
    Http409ConflictFromJSON,
    Http409ConflictToJSON,
} from '../models/Http409Conflict';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type ListServicePrincipalKeys200Response,
    ListServicePrincipalKeys200ResponseFromJSON,
    ListServicePrincipalKeys200ResponseToJSON,
} from '../models/ListServicePrincipalKeys200Response';
import {
    type ListServicePrincipals200Response,
    ListServicePrincipals200ResponseFromJSON,
    ListServicePrincipals200ResponseToJSON,
} from '../models/ListServicePrincipals200Response';
import {
    type ServicePrincipal,
    ServicePrincipalFromJSON,
    ServicePrincipalToJSON,
} from '../models/ServicePrincipal';
import {
    type ServicePrincipalKey,
    ServicePrincipalKeyFromJSON,
    ServicePrincipalKeyToJSON,
} from '../models/ServicePrincipalKey';
import {
    type ServicePrincipalOAuth2AccessToken,
    ServicePrincipalOAuth2AccessTokenFromJSON,
    ServicePrincipalOAuth2AccessTokenToJSON,
} from '../models/ServicePrincipalOAuth2AccessToken';
import {
    type UpdateServicePrincipalRequest,
    UpdateServicePrincipalRequestFromJSON,
    UpdateServicePrincipalRequestToJSON,
} from '../models/UpdateServicePrincipalRequest';
import {
    type UploadServicePrincipalKeyRequest,
    UploadServicePrincipalKeyRequestFromJSON,
    UploadServicePrincipalKeyRequestToJSON,
} from '../models/UploadServicePrincipalKeyRequest';

export interface CreateServicePrincipalOperationRequest {
    createServicePrincipalRequest: CreateServicePrincipalRequest;
}

export interface DeleteServicePrincipalRequest {
    servicePrincipalId: number;
}

export interface DeleteServicePrincipalKeyRequest {
    servicePrincipalId: number;
    servicePrincipalKeyId: string;
}

export interface DisableServicePrincipalKeyRequest {
    servicePrincipalId: number;
    servicePrincipalKeyId: string;
}

export interface EnableServicePrincipalKeyRequest {
    servicePrincipalId: number;
    servicePrincipalKeyId: string;
}

export interface IssueServicePrincipalTokenRequest {
    grantType: IssueServicePrincipalTokenGrantTypeEnum;
    assertion: string;
}

export interface ListServicePrincipalKeysRequest {
    servicePrincipalId: number;
    page?: number;
    perPage?: number;
    ordering?: ListServicePrincipalKeysOrderingEnum;
}

export interface ListServicePrincipalsRequest {
    page?: number;
    perPage?: number;
    projectId?: number;
    ordering?: ListServicePrincipalsOrderingEnum;
}

export interface ReadServicePrincipalRequest {
    servicePrincipalId: number;
}

export interface UpdateServicePrincipalOperationRequest {
    servicePrincipalId: number;
    updateServicePrincipalRequest: UpdateServicePrincipalRequest;
}

export interface UploadServicePrincipalKeyOperationRequest {
    servicePrincipalId: number;
    uploadServicePrincipalKeyRequest?: UploadServicePrincipalKeyRequest;
}

/**
 * ServicePrincipalApi - interface
 * 
 * @export
 * @interface ServicePrincipalApiInterface
 */
export interface ServicePrincipalApiInterface {
    /**
     * Creates request options for createServicePrincipal without sending the request
     * @param {CreateServicePrincipalRequest} createServicePrincipalRequest サービスプリンシパルの情報
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    createServicePrincipalRequestOpts(requestParameters: CreateServicePrincipalOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary サービスプリンシパルを作成する
     * @param {CreateServicePrincipalRequest} createServicePrincipalRequest サービスプリンシパルの情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    createServicePrincipalRaw(requestParameters: CreateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipal>>;

    /**
     * サービスプリンシパルを作成する
     */
    createServicePrincipal(requestParameters: CreateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipal>;

    /**
     * Creates request options for deleteServicePrincipal without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    deleteServicePrincipalRequestOpts(requestParameters: DeleteServicePrincipalRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したサービスプリンシパルを削除する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    deleteServicePrincipalRaw(requestParameters: DeleteServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 指定したサービスプリンシパルを削除する
     */
    deleteServicePrincipal(requestParameters: DeleteServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteServicePrincipalKey without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {string} servicePrincipalKeyId サービスプリンシパルキーID
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    deleteServicePrincipalKeyRequestOpts(requestParameters: DeleteServicePrincipalKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したサービスプリンシパルキーを削除する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {string} servicePrincipalKeyId サービスプリンシパルキーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    deleteServicePrincipalKeyRaw(requestParameters: DeleteServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 指定したサービスプリンシパルキーを削除する
     */
    deleteServicePrincipalKey(requestParameters: DeleteServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for disableServicePrincipalKey without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {string} servicePrincipalKeyId サービスプリンシパルキーID
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    disableServicePrincipalKeyRequestOpts(requestParameters: DisableServicePrincipalKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したサービスプリンシパルキーを無効化する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {string} servicePrincipalKeyId サービスプリンシパルキーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    disableServicePrincipalKeyRaw(requestParameters: DisableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalKey>>;

    /**
     * 指定したサービスプリンシパルキーを無効化する
     */
    disableServicePrincipalKey(requestParameters: DisableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalKey>;

    /**
     * Creates request options for enableServicePrincipalKey without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {string} servicePrincipalKeyId サービスプリンシパルキーID
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    enableServicePrincipalKeyRequestOpts(requestParameters: EnableServicePrincipalKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したサービスプリンシパルキーを有効化する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {string} servicePrincipalKeyId サービスプリンシパルキーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    enableServicePrincipalKeyRaw(requestParameters: EnableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalKey>>;

    /**
     * 指定したサービスプリンシパルキーを有効化する
     */
    enableServicePrincipalKey(requestParameters: EnableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalKey>;

    /**
     * Creates request options for issueServicePrincipalToken without sending the request
     * @param {string} grantType 固定値 JWT Bearer Grant Type
     * @param {string} assertion サービスプリンシパルキーで署名されたJWT
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    issueServicePrincipalTokenRequestOpts(requestParameters: IssueServicePrincipalTokenRequest): Promise<runtime.RequestOpts>;

    /**
     * 登録済みサービスプリンシパルキーの秘密鍵を使い、以下のようなJWTを署名してください。  #### JWTのヘッダー  ```json {   \"alg\": \"RS256\",   \"kid\": \"$SERVICE_PRINCIPAL_KEY_KID\",   \"typ\": \"JWT\" } ```  ### JWTのペイロード  ```json {   \"aud\": \"https://secure.sakura.ad.jp/cloud/api/iam/1.0/service-principals/oauth2/token\",   \"exp\": 現在のUnix time + 5分,   \"iat\": 現在のUnix time,   \"iss\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\",   \"sub\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\" } ``` 
     * @summary RFC 7523 (JWT Bearer Token Grant) に基づき、署名済みJWTを使って一時的なサービスプリンシパルトークンを取得する
     * @param {string} grantType 固定値 JWT Bearer Grant Type
     * @param {string} assertion サービスプリンシパルキーで署名されたJWT
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    issueServicePrincipalTokenRaw(requestParameters: IssueServicePrincipalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalOAuth2AccessToken>>;

    /**
     * 登録済みサービスプリンシパルキーの秘密鍵を使い、以下のようなJWTを署名してください。  #### JWTのヘッダー  ```json {   \"alg\": \"RS256\",   \"kid\": \"$SERVICE_PRINCIPAL_KEY_KID\",   \"typ\": \"JWT\" } ```  ### JWTのペイロード  ```json {   \"aud\": \"https://secure.sakura.ad.jp/cloud/api/iam/1.0/service-principals/oauth2/token\",   \"exp\": 現在のUnix time + 5分,   \"iat\": 現在のUnix time,   \"iss\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\",   \"sub\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\" } ``` 
     * RFC 7523 (JWT Bearer Token Grant) に基づき、署名済みJWTを使って一時的なサービスプリンシパルトークンを取得する
     */
    issueServicePrincipalToken(requestParameters: IssueServicePrincipalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalOAuth2AccessToken>;

    /**
     * Creates request options for listServicePrincipalKeys without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'created_at' | '-created_at' | 'key_expires_at' | '-key_expires_at'} [ordering] 並び替えキー * &#x60;created_at&#x60; - 作成日時昇順 * &#x60;-created_at&#x60; - 作成日時降順 * &#x60;key_expires_at&#x60; - 有効期限昇順 * &#x60;-key_expires_at&#x60; - 有効期限降順 
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    listServicePrincipalKeysRequestOpts(requestParameters: ListServicePrincipalKeysRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary サービスプリンシパルキー一覧を取得する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'created_at' | '-created_at' | 'key_expires_at' | '-key_expires_at'} [ordering] 並び替えキー * &#x60;created_at&#x60; - 作成日時昇順 * &#x60;-created_at&#x60; - 作成日時降順 * &#x60;key_expires_at&#x60; - 有効期限昇順 * &#x60;-key_expires_at&#x60; - 有効期限降順 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    listServicePrincipalKeysRaw(requestParameters: ListServicePrincipalKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListServicePrincipalKeys200Response>>;

    /**
     * サービスプリンシパルキー一覧を取得する
     */
    listServicePrincipalKeys(requestParameters: ListServicePrincipalKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListServicePrincipalKeys200Response>;

    /**
     * Creates request options for listServicePrincipals without sending the request
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {number} [projectId] プロジェクトID
     * @param {'name' | '-name'} [ordering] 並び替えキー * &#x60;name&#x60; - サービスプリンシパル名昇順 * &#x60;-name&#x60; - サービスプリンシパル名降順 
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    listServicePrincipalsRequestOpts(requestParameters: ListServicePrincipalsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary サービスプリンシパル一覧を取得する
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {number} [projectId] プロジェクトID
     * @param {'name' | '-name'} [ordering] 並び替えキー * &#x60;name&#x60; - サービスプリンシパル名昇順 * &#x60;-name&#x60; - サービスプリンシパル名降順 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    listServicePrincipalsRaw(requestParameters: ListServicePrincipalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListServicePrincipals200Response>>;

    /**
     * サービスプリンシパル一覧を取得する
     */
    listServicePrincipals(requestParameters: ListServicePrincipalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListServicePrincipals200Response>;

    /**
     * Creates request options for readServicePrincipal without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    readServicePrincipalRequestOpts(requestParameters: ReadServicePrincipalRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したサービスプリンシパルを取得する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    readServicePrincipalRaw(requestParameters: ReadServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipal>>;

    /**
     * 指定したサービスプリンシパルを取得する
     */
    readServicePrincipal(requestParameters: ReadServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipal>;

    /**
     * Creates request options for updateServicePrincipal without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {UpdateServicePrincipalRequest} updateServicePrincipalRequest 
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    updateServicePrincipalRequestOpts(requestParameters: UpdateServicePrincipalOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したサービスプリンシパルを更新する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {UpdateServicePrincipalRequest} updateServicePrincipalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    updateServicePrincipalRaw(requestParameters: UpdateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipal>>;

    /**
     * 指定したサービスプリンシパルを更新する
     */
    updateServicePrincipal(requestParameters: UpdateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipal>;

    /**
     * Creates request options for uploadServicePrincipalKey without sending the request
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {UploadServicePrincipalKeyRequest} [uploadServicePrincipalKeyRequest] 
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    uploadServicePrincipalKeyRequestOpts(requestParameters: UploadServicePrincipalKeyOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザ生成の鍵をサービスプリンシパルキーとして登録する
     * @param {number} servicePrincipalId サービスプリンシパルID
     * @param {UploadServicePrincipalKeyRequest} [uploadServicePrincipalKeyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServicePrincipalApiInterface
     */
    uploadServicePrincipalKeyRaw(requestParameters: UploadServicePrincipalKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalKey>>;

    /**
     * ユーザ生成の鍵をサービスプリンシパルキーとして登録する
     */
    uploadServicePrincipalKey(requestParameters: UploadServicePrincipalKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalKey>;

}

/**
 * 
 */
export class ServicePrincipalApi extends runtime.BaseAPI implements ServicePrincipalApiInterface {

    /**
     * Creates request options for createServicePrincipal without sending the request
     */
    async createServicePrincipalRequestOpts(requestParameters: CreateServicePrincipalOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createServicePrincipalRequest'] == null) {
            throw new runtime.RequiredError(
                'createServicePrincipalRequest',
                'Required parameter "createServicePrincipalRequest" was null or undefined when calling createServicePrincipal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateServicePrincipalRequestToJSON(requestParameters['createServicePrincipalRequest']),
        };
    }

    /**
     * サービスプリンシパルを作成する
     */
    async createServicePrincipalRaw(requestParameters: CreateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipal>> {
        const requestOptions = await this.createServicePrincipalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePrincipalFromJSON(jsonValue));
    }

    /**
     * サービスプリンシパルを作成する
     */
    async createServicePrincipal(requestParameters: CreateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipal> {
        const response = await this.createServicePrincipalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteServicePrincipal without sending the request
     */
    async deleteServicePrincipalRequestOpts(requestParameters: DeleteServicePrincipalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling deleteServicePrincipal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したサービスプリンシパルを削除する
     */
    async deleteServicePrincipalRaw(requestParameters: DeleteServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteServicePrincipalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 指定したサービスプリンシパルを削除する
     */
    async deleteServicePrincipal(requestParameters: DeleteServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteServicePrincipalRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteServicePrincipalKey without sending the request
     */
    async deleteServicePrincipalKeyRequestOpts(requestParameters: DeleteServicePrincipalKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling deleteServicePrincipalKey().'
            );
        }

        if (requestParameters['servicePrincipalKeyId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalKeyId',
                'Required parameter "servicePrincipalKeyId" was null or undefined when calling deleteServicePrincipalKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}/keys/{service_principal_key_id}`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));
        urlPath = urlPath.replace('{service_principal_key_id}', encodeURIComponent(String(requestParameters['servicePrincipalKeyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したサービスプリンシパルキーを削除する
     */
    async deleteServicePrincipalKeyRaw(requestParameters: DeleteServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteServicePrincipalKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 指定したサービスプリンシパルキーを削除する
     */
    async deleteServicePrincipalKey(requestParameters: DeleteServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteServicePrincipalKeyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for disableServicePrincipalKey without sending the request
     */
    async disableServicePrincipalKeyRequestOpts(requestParameters: DisableServicePrincipalKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling disableServicePrincipalKey().'
            );
        }

        if (requestParameters['servicePrincipalKeyId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalKeyId',
                'Required parameter "servicePrincipalKeyId" was null or undefined when calling disableServicePrincipalKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}/keys/{service_principal_key_id}/disable`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));
        urlPath = urlPath.replace('{service_principal_key_id}', encodeURIComponent(String(requestParameters['servicePrincipalKeyId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したサービスプリンシパルキーを無効化する
     */
    async disableServicePrincipalKeyRaw(requestParameters: DisableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalKey>> {
        const requestOptions = await this.disableServicePrincipalKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePrincipalKeyFromJSON(jsonValue));
    }

    /**
     * 指定したサービスプリンシパルキーを無効化する
     */
    async disableServicePrincipalKey(requestParameters: DisableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalKey> {
        const response = await this.disableServicePrincipalKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for enableServicePrincipalKey without sending the request
     */
    async enableServicePrincipalKeyRequestOpts(requestParameters: EnableServicePrincipalKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling enableServicePrincipalKey().'
            );
        }

        if (requestParameters['servicePrincipalKeyId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalKeyId',
                'Required parameter "servicePrincipalKeyId" was null or undefined when calling enableServicePrincipalKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}/keys/{service_principal_key_id}/enable`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));
        urlPath = urlPath.replace('{service_principal_key_id}', encodeURIComponent(String(requestParameters['servicePrincipalKeyId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したサービスプリンシパルキーを有効化する
     */
    async enableServicePrincipalKeyRaw(requestParameters: EnableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalKey>> {
        const requestOptions = await this.enableServicePrincipalKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePrincipalKeyFromJSON(jsonValue));
    }

    /**
     * 指定したサービスプリンシパルキーを有効化する
     */
    async enableServicePrincipalKey(requestParameters: EnableServicePrincipalKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalKey> {
        const response = await this.enableServicePrincipalKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for issueServicePrincipalToken without sending the request
     */
    async issueServicePrincipalTokenRequestOpts(requestParameters: IssueServicePrincipalTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['grantType'] == null) {
            throw new runtime.RequiredError(
                'grantType',
                'Required parameter "grantType" was null or undefined when calling issueServicePrincipalToken().'
            );
        }

        if (requestParameters['assertion'] == null) {
            throw new runtime.RequiredError(
                'assertion',
                'Required parameter "assertion" was null or undefined when calling issueServicePrincipalToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }

        if (requestParameters['assertion'] != null) {
            formParams.append('assertion', requestParameters['assertion'] as any);
        }


        let urlPath = `/service-principals/oauth2/token`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * 登録済みサービスプリンシパルキーの秘密鍵を使い、以下のようなJWTを署名してください。  #### JWTのヘッダー  ```json {   \"alg\": \"RS256\",   \"kid\": \"$SERVICE_PRINCIPAL_KEY_KID\",   \"typ\": \"JWT\" } ```  ### JWTのペイロード  ```json {   \"aud\": \"https://secure.sakura.ad.jp/cloud/api/iam/1.0/service-principals/oauth2/token\",   \"exp\": 現在のUnix time + 5分,   \"iat\": 現在のUnix time,   \"iss\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\",   \"sub\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\" } ``` 
     * RFC 7523 (JWT Bearer Token Grant) に基づき、署名済みJWTを使って一時的なサービスプリンシパルトークンを取得する
     */
    async issueServicePrincipalTokenRaw(requestParameters: IssueServicePrincipalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalOAuth2AccessToken>> {
        const requestOptions = await this.issueServicePrincipalTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePrincipalOAuth2AccessTokenFromJSON(jsonValue));
    }

    /**
     * 登録済みサービスプリンシパルキーの秘密鍵を使い、以下のようなJWTを署名してください。  #### JWTのヘッダー  ```json {   \"alg\": \"RS256\",   \"kid\": \"$SERVICE_PRINCIPAL_KEY_KID\",   \"typ\": \"JWT\" } ```  ### JWTのペイロード  ```json {   \"aud\": \"https://secure.sakura.ad.jp/cloud/api/iam/1.0/service-principals/oauth2/token\",   \"exp\": 現在のUnix time + 5分,   \"iat\": 現在のUnix time,   \"iss\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\",   \"sub\": \"$SERVICE_PRINCIPAL_RESOURCE_ID\" } ``` 
     * RFC 7523 (JWT Bearer Token Grant) に基づき、署名済みJWTを使って一時的なサービスプリンシパルトークンを取得する
     */
    async issueServicePrincipalToken(requestParameters: IssueServicePrincipalTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalOAuth2AccessToken> {
        const response = await this.issueServicePrincipalTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listServicePrincipalKeys without sending the request
     */
    async listServicePrincipalKeysRequestOpts(requestParameters: ListServicePrincipalKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling listServicePrincipalKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}/keys`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * サービスプリンシパルキー一覧を取得する
     */
    async listServicePrincipalKeysRaw(requestParameters: ListServicePrincipalKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListServicePrincipalKeys200Response>> {
        const requestOptions = await this.listServicePrincipalKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListServicePrincipalKeys200ResponseFromJSON(jsonValue));
    }

    /**
     * サービスプリンシパルキー一覧を取得する
     */
    async listServicePrincipalKeys(requestParameters: ListServicePrincipalKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListServicePrincipalKeys200Response> {
        const response = await this.listServicePrincipalKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listServicePrincipals without sending the request
     */
    async listServicePrincipalsRequestOpts(requestParameters: ListServicePrincipalsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * サービスプリンシパル一覧を取得する
     */
    async listServicePrincipalsRaw(requestParameters: ListServicePrincipalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListServicePrincipals200Response>> {
        const requestOptions = await this.listServicePrincipalsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListServicePrincipals200ResponseFromJSON(jsonValue));
    }

    /**
     * サービスプリンシパル一覧を取得する
     */
    async listServicePrincipals(requestParameters: ListServicePrincipalsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListServicePrincipals200Response> {
        const response = await this.listServicePrincipalsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readServicePrincipal without sending the request
     */
    async readServicePrincipalRequestOpts(requestParameters: ReadServicePrincipalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling readServicePrincipal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したサービスプリンシパルを取得する
     */
    async readServicePrincipalRaw(requestParameters: ReadServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipal>> {
        const requestOptions = await this.readServicePrincipalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePrincipalFromJSON(jsonValue));
    }

    /**
     * 指定したサービスプリンシパルを取得する
     */
    async readServicePrincipal(requestParameters: ReadServicePrincipalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipal> {
        const response = await this.readServicePrincipalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateServicePrincipal without sending the request
     */
    async updateServicePrincipalRequestOpts(requestParameters: UpdateServicePrincipalOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling updateServicePrincipal().'
            );
        }

        if (requestParameters['updateServicePrincipalRequest'] == null) {
            throw new runtime.RequiredError(
                'updateServicePrincipalRequest',
                'Required parameter "updateServicePrincipalRequest" was null or undefined when calling updateServicePrincipal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateServicePrincipalRequestToJSON(requestParameters['updateServicePrincipalRequest']),
        };
    }

    /**
     * 指定したサービスプリンシパルを更新する
     */
    async updateServicePrincipalRaw(requestParameters: UpdateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipal>> {
        const requestOptions = await this.updateServicePrincipalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePrincipalFromJSON(jsonValue));
    }

    /**
     * 指定したサービスプリンシパルを更新する
     */
    async updateServicePrincipal(requestParameters: UpdateServicePrincipalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipal> {
        const response = await this.updateServicePrincipalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadServicePrincipalKey without sending the request
     */
    async uploadServicePrincipalKeyRequestOpts(requestParameters: UploadServicePrincipalKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['servicePrincipalId'] == null) {
            throw new runtime.RequiredError(
                'servicePrincipalId',
                'Required parameter "servicePrincipalId" was null or undefined when calling uploadServicePrincipalKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/service-principals/{service_principal_id}/upload-key`;
        urlPath = urlPath.replace('{service_principal_id}', encodeURIComponent(String(requestParameters['servicePrincipalId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadServicePrincipalKeyRequestToJSON(requestParameters['uploadServicePrincipalKeyRequest']),
        };
    }

    /**
     * ユーザ生成の鍵をサービスプリンシパルキーとして登録する
     */
    async uploadServicePrincipalKeyRaw(requestParameters: UploadServicePrincipalKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePrincipalKey>> {
        const requestOptions = await this.uploadServicePrincipalKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePrincipalKeyFromJSON(jsonValue));
    }

    /**
     * ユーザ生成の鍵をサービスプリンシパルキーとして登録する
     */
    async uploadServicePrincipalKey(requestParameters: UploadServicePrincipalKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePrincipalKey> {
        const response = await this.uploadServicePrincipalKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const IssueServicePrincipalTokenGrantTypeEnum = {
    UrnIetfParamsOauthGrantTypeJwtBearer: 'urn:ietf:params:oauth:grant-type:jwt-bearer'
} as const;
export type IssueServicePrincipalTokenGrantTypeEnum = typeof IssueServicePrincipalTokenGrantTypeEnum[keyof typeof IssueServicePrincipalTokenGrantTypeEnum];
/**
 * @export
 */
export const ListServicePrincipalKeysOrderingEnum = {
    CreatedAt: 'created_at',
    CreatedAt2: '-created_at',
    KeyExpiresAt: 'key_expires_at',
    KeyExpiresAt2: '-key_expires_at'
} as const;
export type ListServicePrincipalKeysOrderingEnum = typeof ListServicePrincipalKeysOrderingEnum[keyof typeof ListServicePrincipalKeysOrderingEnum];
/**
 * @export
 */
export const ListServicePrincipalsOrderingEnum = {
    Name: 'name',
    Name2: '-name'
} as const;
export type ListServicePrincipalsOrderingEnum = typeof ListServicePrincipalsOrderingEnum[keyof typeof ListServicePrincipalsOrderingEnum];
