/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateSsoProfileRequest,
    CreateSsoProfileRequestFromJSON,
    CreateSsoProfileRequestToJSON,
} from '../models/CreateSsoProfileRequest';
import {
    type Http400BadRequest,
    Http400BadRequestFromJSON,
    Http400BadRequestToJSON,
} from '../models/Http400BadRequest';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http409Conflict,
    Http409ConflictFromJSON,
    Http409ConflictToJSON,
} from '../models/Http409Conflict';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type ListSsoProfiles200Response,
    ListSsoProfiles200ResponseFromJSON,
    ListSsoProfiles200ResponseToJSON,
} from '../models/ListSsoProfiles200Response';
import {
    type SSOProfile,
    SSOProfileFromJSON,
    SSOProfileToJSON,
} from '../models/SSOProfile';
import {
    type UpdateSsoProfileRequest,
    UpdateSsoProfileRequestFromJSON,
    UpdateSsoProfileRequestToJSON,
} from '../models/UpdateSsoProfileRequest';

export interface AssignSsoProfileRequest {
    ssoProfileId: number;
}

export interface CreateSsoProfileOperationRequest {
    createSsoProfileRequest: CreateSsoProfileRequest;
}

export interface DeleteSsoProfileRequest {
    ssoProfileId: number;
}

export interface ListSsoProfilesRequest {
    page?: number;
    perPage?: number;
}

export interface ReadSsoProfileRequest {
    ssoProfileId: number;
}

export interface UnassignSsoProfileRequest {
    ssoProfileId: number;
}

export interface UpdateSsoProfileOperationRequest {
    ssoProfileId: number;
    updateSsoProfileRequest: UpdateSsoProfileRequest;
}

/**
 * SsoApi - interface
 * 
 * @export
 * @interface SsoApiInterface
 */
export interface SsoApiInterface {
    /**
     * Creates request options for assignSsoProfile without sending the request
     * @param {number} ssoProfileId SSOプロファイルID
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    assignSsoProfileRequestOpts(requestParameters: AssignSsoProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 割当を行うと会員配下のクラウドユーザすべてで該当SSOプロファイルが有効になります。
     * @summary 指定したSSOプロファイルを割り当てる
     * @param {number} ssoProfileId SSOプロファイルID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    assignSsoProfileRaw(requestParameters: AssignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>>;

    /**
     * 割当を行うと会員配下のクラウドユーザすべてで該当SSOプロファイルが有効になります。
     * 指定したSSOプロファイルを割り当てる
     */
    assignSsoProfile(requestParameters: AssignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile>;

    /**
     * Creates request options for createSsoProfile without sending the request
     * @param {CreateSsoProfileRequest} createSsoProfileRequest IdPの情報
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    createSsoProfileRequestOpts(requestParameters: CreateSsoProfileOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary SSOプロファイルを作成する
     * @param {CreateSsoProfileRequest} createSsoProfileRequest IdPの情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    createSsoProfileRaw(requestParameters: CreateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>>;

    /**
     * SSOプロファイルを作成する
     */
    createSsoProfile(requestParameters: CreateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile>;

    /**
     * Creates request options for deleteSsoProfile without sending the request
     * @param {number} ssoProfileId SSOプロファイルID
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    deleteSsoProfileRequestOpts(requestParameters: DeleteSsoProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したSSOプロファイルを削除する
     * @param {number} ssoProfileId SSOプロファイルID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    deleteSsoProfileRaw(requestParameters: DeleteSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 指定したSSOプロファイルを削除する
     */
    deleteSsoProfile(requestParameters: DeleteSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listSsoProfiles without sending the request
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    listSsoProfilesRequestOpts(requestParameters: ListSsoProfilesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary SSOプロファイル一覧を取得する
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    listSsoProfilesRaw(requestParameters: ListSsoProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSsoProfiles200Response>>;

    /**
     * SSOプロファイル一覧を取得する
     */
    listSsoProfiles(requestParameters: ListSsoProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSsoProfiles200Response>;

    /**
     * Creates request options for readSsoProfile without sending the request
     * @param {number} ssoProfileId SSOプロファイルID
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    readSsoProfileRequestOpts(requestParameters: ReadSsoProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したSSOプロファイルを取得する
     * @param {number} ssoProfileId SSOプロファイルID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    readSsoProfileRaw(requestParameters: ReadSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>>;

    /**
     * 指定したSSOプロファイルを取得する
     */
    readSsoProfile(requestParameters: ReadSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile>;

    /**
     * Creates request options for unassignSsoProfile without sending the request
     * @param {number} ssoProfileId SSOプロファイルID
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    unassignSsoProfileRequestOpts(requestParameters: UnassignSsoProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したSSOプロファイルの割り当てを外す
     * @param {number} ssoProfileId SSOプロファイルID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    unassignSsoProfileRaw(requestParameters: UnassignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>>;

    /**
     * 指定したSSOプロファイルの割り当てを外す
     */
    unassignSsoProfile(requestParameters: UnassignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile>;

    /**
     * Creates request options for updateSsoProfile without sending the request
     * @param {number} ssoProfileId SSOプロファイルID
     * @param {UpdateSsoProfileRequest} updateSsoProfileRequest 
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    updateSsoProfileRequestOpts(requestParameters: UpdateSsoProfileOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary 指定したSSOプロファイルを更新する
     * @param {number} ssoProfileId SSOプロファイルID
     * @param {UpdateSsoProfileRequest} updateSsoProfileRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SsoApiInterface
     */
    updateSsoProfileRaw(requestParameters: UpdateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>>;

    /**
     * 指定したSSOプロファイルを更新する
     */
    updateSsoProfile(requestParameters: UpdateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile>;

}

/**
 * 
 */
export class SsoApi extends runtime.BaseAPI implements SsoApiInterface {

    /**
     * Creates request options for assignSsoProfile without sending the request
     */
    async assignSsoProfileRequestOpts(requestParameters: AssignSsoProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ssoProfileId'] == null) {
            throw new runtime.RequiredError(
                'ssoProfileId',
                'Required parameter "ssoProfileId" was null or undefined when calling assignSsoProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sso-profiles/{sso_profile_id}/assign`;
        urlPath = urlPath.replace('{sso_profile_id}', encodeURIComponent(String(requestParameters['ssoProfileId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 割当を行うと会員配下のクラウドユーザすべてで該当SSOプロファイルが有効になります。
     * 指定したSSOプロファイルを割り当てる
     */
    async assignSsoProfileRaw(requestParameters: AssignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>> {
        const requestOptions = await this.assignSsoProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSOProfileFromJSON(jsonValue));
    }

    /**
     * 割当を行うと会員配下のクラウドユーザすべてで該当SSOプロファイルが有効になります。
     * 指定したSSOプロファイルを割り当てる
     */
    async assignSsoProfile(requestParameters: AssignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile> {
        const response = await this.assignSsoProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSsoProfile without sending the request
     */
    async createSsoProfileRequestOpts(requestParameters: CreateSsoProfileOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSsoProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'createSsoProfileRequest',
                'Required parameter "createSsoProfileRequest" was null or undefined when calling createSsoProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sso-profiles`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSsoProfileRequestToJSON(requestParameters['createSsoProfileRequest']),
        };
    }

    /**
     * SSOプロファイルを作成する
     */
    async createSsoProfileRaw(requestParameters: CreateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>> {
        const requestOptions = await this.createSsoProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSOProfileFromJSON(jsonValue));
    }

    /**
     * SSOプロファイルを作成する
     */
    async createSsoProfile(requestParameters: CreateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile> {
        const response = await this.createSsoProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSsoProfile without sending the request
     */
    async deleteSsoProfileRequestOpts(requestParameters: DeleteSsoProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ssoProfileId'] == null) {
            throw new runtime.RequiredError(
                'ssoProfileId',
                'Required parameter "ssoProfileId" was null or undefined when calling deleteSsoProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sso-profiles/{sso_profile_id}`;
        urlPath = urlPath.replace('{sso_profile_id}', encodeURIComponent(String(requestParameters['ssoProfileId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したSSOプロファイルを削除する
     */
    async deleteSsoProfileRaw(requestParameters: DeleteSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSsoProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 指定したSSOプロファイルを削除する
     */
    async deleteSsoProfile(requestParameters: DeleteSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSsoProfileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listSsoProfiles without sending the request
     */
    async listSsoProfilesRequestOpts(requestParameters: ListSsoProfilesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sso-profiles`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * SSOプロファイル一覧を取得する
     */
    async listSsoProfilesRaw(requestParameters: ListSsoProfilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSsoProfiles200Response>> {
        const requestOptions = await this.listSsoProfilesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSsoProfiles200ResponseFromJSON(jsonValue));
    }

    /**
     * SSOプロファイル一覧を取得する
     */
    async listSsoProfiles(requestParameters: ListSsoProfilesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSsoProfiles200Response> {
        const response = await this.listSsoProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readSsoProfile without sending the request
     */
    async readSsoProfileRequestOpts(requestParameters: ReadSsoProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ssoProfileId'] == null) {
            throw new runtime.RequiredError(
                'ssoProfileId',
                'Required parameter "ssoProfileId" was null or undefined when calling readSsoProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sso-profiles/{sso_profile_id}`;
        urlPath = urlPath.replace('{sso_profile_id}', encodeURIComponent(String(requestParameters['ssoProfileId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したSSOプロファイルを取得する
     */
    async readSsoProfileRaw(requestParameters: ReadSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>> {
        const requestOptions = await this.readSsoProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSOProfileFromJSON(jsonValue));
    }

    /**
     * 指定したSSOプロファイルを取得する
     */
    async readSsoProfile(requestParameters: ReadSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile> {
        const response = await this.readSsoProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unassignSsoProfile without sending the request
     */
    async unassignSsoProfileRequestOpts(requestParameters: UnassignSsoProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ssoProfileId'] == null) {
            throw new runtime.RequiredError(
                'ssoProfileId',
                'Required parameter "ssoProfileId" was null or undefined when calling unassignSsoProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sso-profiles/{sso_profile_id}/unassign`;
        urlPath = urlPath.replace('{sso_profile_id}', encodeURIComponent(String(requestParameters['ssoProfileId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したSSOプロファイルの割り当てを外す
     */
    async unassignSsoProfileRaw(requestParameters: UnassignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>> {
        const requestOptions = await this.unassignSsoProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSOProfileFromJSON(jsonValue));
    }

    /**
     * 指定したSSOプロファイルの割り当てを外す
     */
    async unassignSsoProfile(requestParameters: UnassignSsoProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile> {
        const response = await this.unassignSsoProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSsoProfile without sending the request
     */
    async updateSsoProfileRequestOpts(requestParameters: UpdateSsoProfileOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ssoProfileId'] == null) {
            throw new runtime.RequiredError(
                'ssoProfileId',
                'Required parameter "ssoProfileId" was null or undefined when calling updateSsoProfile().'
            );
        }

        if (requestParameters['updateSsoProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSsoProfileRequest',
                'Required parameter "updateSsoProfileRequest" was null or undefined when calling updateSsoProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sso-profiles/{sso_profile_id}`;
        urlPath = urlPath.replace('{sso_profile_id}', encodeURIComponent(String(requestParameters['ssoProfileId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSsoProfileRequestToJSON(requestParameters['updateSsoProfileRequest']),
        };
    }

    /**
     * 指定したSSOプロファイルを更新する
     */
    async updateSsoProfileRaw(requestParameters: UpdateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SSOProfile>> {
        const requestOptions = await this.updateSsoProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SSOProfileFromJSON(jsonValue));
    }

    /**
     * 指定したSSOプロファイルを更新する
     */
    async updateSsoProfile(requestParameters: UpdateSsoProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SSOProfile> {
        const response = await this.updateSsoProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
