/* tslint:disable */
/* eslint-disable */
/**
 * さくらのクラウドIAM API
 * さくらのクラウドIAMのAPIドキュメントです
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Http401Unauthorized,
    Http401UnauthorizedFromJSON,
    Http401UnauthorizedToJSON,
} from '../models/Http401Unauthorized';
import {
    type Http403Forbidden,
    Http403ForbiddenFromJSON,
    Http403ForbiddenToJSON,
} from '../models/Http403Forbidden';
import {
    type Http404NotFound,
    Http404NotFoundFromJSON,
    Http404NotFoundToJSON,
} from '../models/Http404NotFound';
import {
    type Http429TooManyRequests,
    Http429TooManyRequestsFromJSON,
    Http429TooManyRequestsToJSON,
} from '../models/Http429TooManyRequests';
import {
    type ListSecurityKeys200Response,
    ListSecurityKeys200ResponseFromJSON,
    ListSecurityKeys200ResponseToJSON,
} from '../models/ListSecurityKeys200Response';
import {
    type ListTrustedDevices200Response,
    ListTrustedDevices200ResponseFromJSON,
    ListTrustedDevices200ResponseToJSON,
} from '../models/ListTrustedDevices200Response';
import {
    type UserSecurityKey,
    UserSecurityKeyFromJSON,
    UserSecurityKeyToJSON,
} from '../models/UserSecurityKey';

export interface ClearTrustedDevicesRequest {
    userId: number;
}

export interface DeactivateOtpRequest {
    userId: number;
}

export interface DeleteSecurityKeyRequest {
    userId: number;
    securityKeyId: number;
}

export interface DeleteTrustedDeviceRequest {
    userId: number;
    trustedDeviceId: number;
}

export interface ListSecurityKeysRequest {
    userId: number;
}

export interface ListTrustedDevicesRequest {
    userId: number;
}

export interface ReadSecurityKeyRequest {
    userId: number;
    securityKeyId: number;
}

/**
 * User2faApi - interface
 * 
 * @export
 * @interface User2faApiInterface
 */
export interface User2faApiInterface {
    /**
     * Creates request options for clearTrustedDevices without sending the request
     * @param {number} userId ユーザID
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    clearTrustedDevicesRequestOpts(requestParameters: ClearTrustedDevicesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザの全信頼済みデバイスを削除する
     * @param {number} userId ユーザID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    clearTrustedDevicesRaw(requestParameters: ClearTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * ユーザの全信頼済みデバイスを削除する
     */
    clearTrustedDevices(requestParameters: ClearTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deactivateOtp without sending the request
     * @param {number} userId ユーザID
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    deactivateOtpRequestOpts(requestParameters: DeactivateOtpRequest): Promise<runtime.RequestOpts>;

    /**
     * 指定したユーザのワンタイムパスワード認証を無効化します。 
     * @summary ユーザのOTPを無効化する
     * @param {number} userId ユーザID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    deactivateOtpRaw(requestParameters: DeactivateOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 指定したユーザのワンタイムパスワード認証を無効化します。 
     * ユーザのOTPを無効化する
     */
    deactivateOtp(requestParameters: DeactivateOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteSecurityKey without sending the request
     * @param {number} userId ユーザID
     * @param {number} securityKeyId セキュリティキーID
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    deleteSecurityKeyRequestOpts(requestParameters: DeleteSecurityKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザのセキュリティキーを削除する
     * @param {number} userId ユーザID
     * @param {number} securityKeyId セキュリティキーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    deleteSecurityKeyRaw(requestParameters: DeleteSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * ユーザのセキュリティキーを削除する
     */
    deleteSecurityKey(requestParameters: DeleteSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteTrustedDevice without sending the request
     * @param {number} userId ユーザID
     * @param {number} trustedDeviceId ユーザID
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    deleteTrustedDeviceRequestOpts(requestParameters: DeleteTrustedDeviceRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザの信頼済みデバイスを削除する
     * @param {number} userId ユーザID
     * @param {number} trustedDeviceId ユーザID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    deleteTrustedDeviceRaw(requestParameters: DeleteTrustedDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * ユーザの信頼済みデバイスを削除する
     */
    deleteTrustedDevice(requestParameters: DeleteTrustedDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listSecurityKeys without sending the request
     * @param {number} userId ユーザID
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    listSecurityKeysRequestOpts(requestParameters: ListSecurityKeysRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザのセキュリティキー一覧を取得する
     * @param {number} userId ユーザID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    listSecurityKeysRaw(requestParameters: ListSecurityKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSecurityKeys200Response>>;

    /**
     * ユーザのセキュリティキー一覧を取得する
     */
    listSecurityKeys(requestParameters: ListSecurityKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSecurityKeys200Response>;

    /**
     * Creates request options for listTrustedDevices without sending the request
     * @param {number} userId ユーザID
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    listTrustedDevicesRequestOpts(requestParameters: ListTrustedDevicesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザの信頼済みデバイス一覧を取得する
     * @param {number} userId ユーザID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    listTrustedDevicesRaw(requestParameters: ListTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTrustedDevices200Response>>;

    /**
     * ユーザの信頼済みデバイス一覧を取得する
     */
    listTrustedDevices(requestParameters: ListTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTrustedDevices200Response>;

    /**
     * Creates request options for readSecurityKey without sending the request
     * @param {number} userId ユーザID
     * @param {number} securityKeyId セキュリティキーID
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    readSecurityKeyRequestOpts(requestParameters: ReadSecurityKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary ユーザのセキュリティキーを取得する
     * @param {number} userId ユーザID
     * @param {number} securityKeyId セキュリティキーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof User2faApiInterface
     */
    readSecurityKeyRaw(requestParameters: ReadSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSecurityKey>>;

    /**
     * ユーザのセキュリティキーを取得する
     */
    readSecurityKey(requestParameters: ReadSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSecurityKey>;

}

/**
 * 
 */
export class User2faApi extends runtime.BaseAPI implements User2faApiInterface {

    /**
     * Creates request options for clearTrustedDevices without sending the request
     */
    async clearTrustedDevicesRequestOpts(requestParameters: ClearTrustedDevicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling clearTrustedDevices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/users/{user_id}/clear-trusted-devices`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザの全信頼済みデバイスを削除する
     */
    async clearTrustedDevicesRaw(requestParameters: ClearTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.clearTrustedDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ユーザの全信頼済みデバイスを削除する
     */
    async clearTrustedDevices(requestParameters: ClearTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.clearTrustedDevicesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deactivateOtp without sending the request
     */
    async deactivateOtpRequestOpts(requestParameters: DeactivateOtpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deactivateOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/users/{user_id}/deactivate-otp`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 指定したユーザのワンタイムパスワード認証を無効化します。 
     * ユーザのOTPを無効化する
     */
    async deactivateOtpRaw(requestParameters: DeactivateOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deactivateOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 指定したユーザのワンタイムパスワード認証を無効化します。 
     * ユーザのOTPを無効化する
     */
    async deactivateOtp(requestParameters: DeactivateOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deactivateOtpRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteSecurityKey without sending the request
     */
    async deleteSecurityKeyRequestOpts(requestParameters: DeleteSecurityKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteSecurityKey().'
            );
        }

        if (requestParameters['securityKeyId'] == null) {
            throw new runtime.RequiredError(
                'securityKeyId',
                'Required parameter "securityKeyId" was null or undefined when calling deleteSecurityKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/users/{user_id}/security-keys/{security_key_id}`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{security_key_id}', encodeURIComponent(String(requestParameters['securityKeyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザのセキュリティキーを削除する
     */
    async deleteSecurityKeyRaw(requestParameters: DeleteSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSecurityKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ユーザのセキュリティキーを削除する
     */
    async deleteSecurityKey(requestParameters: DeleteSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSecurityKeyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteTrustedDevice without sending the request
     */
    async deleteTrustedDeviceRequestOpts(requestParameters: DeleteTrustedDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteTrustedDevice().'
            );
        }

        if (requestParameters['trustedDeviceId'] == null) {
            throw new runtime.RequiredError(
                'trustedDeviceId',
                'Required parameter "trustedDeviceId" was null or undefined when calling deleteTrustedDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/users/{user_id}/trusted-devices/{trusted_device_id}`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{trusted_device_id}', encodeURIComponent(String(requestParameters['trustedDeviceId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザの信頼済みデバイスを削除する
     */
    async deleteTrustedDeviceRaw(requestParameters: DeleteTrustedDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTrustedDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ユーザの信頼済みデバイスを削除する
     */
    async deleteTrustedDevice(requestParameters: DeleteTrustedDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTrustedDeviceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listSecurityKeys without sending the request
     */
    async listSecurityKeysRequestOpts(requestParameters: ListSecurityKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listSecurityKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/users/{user_id}/security-keys`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザのセキュリティキー一覧を取得する
     */
    async listSecurityKeysRaw(requestParameters: ListSecurityKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSecurityKeys200Response>> {
        const requestOptions = await this.listSecurityKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSecurityKeys200ResponseFromJSON(jsonValue));
    }

    /**
     * ユーザのセキュリティキー一覧を取得する
     */
    async listSecurityKeys(requestParameters: ListSecurityKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSecurityKeys200Response> {
        const response = await this.listSecurityKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTrustedDevices without sending the request
     */
    async listTrustedDevicesRequestOpts(requestParameters: ListTrustedDevicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listTrustedDevices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/users/{user_id}/trusted-devices`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザの信頼済みデバイス一覧を取得する
     */
    async listTrustedDevicesRaw(requestParameters: ListTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTrustedDevices200Response>> {
        const requestOptions = await this.listTrustedDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTrustedDevices200ResponseFromJSON(jsonValue));
    }

    /**
     * ユーザの信頼済みデバイス一覧を取得する
     */
    async listTrustedDevices(requestParameters: ListTrustedDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTrustedDevices200Response> {
        const response = await this.listTrustedDevicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readSecurityKey without sending the request
     */
    async readSecurityKeyRequestOpts(requestParameters: ReadSecurityKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling readSecurityKey().'
            );
        }

        if (requestParameters['securityKeyId'] == null) {
            throw new runtime.RequiredError(
                'securityKeyId',
                'Required parameter "securityKeyId" was null or undefined when calling readSecurityKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ServicePrincipalAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/compat/users/{user_id}/security-keys/{security_key_id}`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{security_key_id}', encodeURIComponent(String(requestParameters['securityKeyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザのセキュリティキーを取得する
     */
    async readSecurityKeyRaw(requestParameters: ReadSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSecurityKey>> {
        const requestOptions = await this.readSecurityKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSecurityKeyFromJSON(jsonValue));
    }

    /**
     * ユーザのセキュリティキーを取得する
     */
    async readSecurityKey(requestParameters: ReadSecurityKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSecurityKey> {
        const response = await this.readSecurityKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
